#### 문제
- selenium의 webdriver를 이용하여 `https://comp.wisereport.co.kr/company/c1010001.aspx` 주소로 접속
- 해당 페이지의 html 문서를 불러와서 BeaurifulSoup 타입으로 파싱
- div 태그 중 class의 값이 'fl_le' 태그들을 모두 찾는다
- 태그들 중 table의 정보가 주요지표, 어닝서프라이즈 태그들을 추출하여 문자로 변경
- pandas에 read_html()을 이용하여 데이터프레임으로 변환
- 해당 데이터프레임들을 DB server에 table1, table2라는 이름으로 저장 (to_sql() 사용)

In [1]:
import pandas as pd
from bs4 import BeautifulSoup as bs
from selenium import webdriver
from sqlalchemy import create_engine

In [2]:
driver = webdriver.Chrome()

In [3]:
driver.get('https://comp.wisereport.co.kr/company/c1010001.aspx')

In [4]:
# driver의 페이지소스를 python으로 로드
html_data = driver.page_source

In [5]:
soup = bs(html_data,'html.parser')

In [6]:
# div 태그중 class가 fl_le인 태그를 모두 찾는다
div_list = soup.find_all(
    'div',
    attrs = {
        'class' : 'fl_le'
    }
)
len(div_list)

5

In [7]:
# 이 영역중에 주요지표 테이블 영역이랑 어닝서프라이즈 테이블 영역만 확인
div_list[1]

<div class="fl_le" style="width: 45%">
<table class="gHead03" style="width: 95%" summary="기업 펀더멘털 실적, 컨센서스 정보 리스트입니다.P/E(지배), P/B(지배), EV/EBITDA. EV/Sales, EPS(지배), BPS(지배), EBITDA, EBIT, 수정DPS, 배당수익률에 대해서 보여주는 리스트입니다.">
<caption class="blind">기업 펀더멘털 실적, 컨센서스</caption>
<colgroup>
<col width="28%"/>
<col width="24%"/>
<col width="24%"/>
<col width="24%"/>
</colgroup>
<thead>
<tr>
<th style="padding: 0">주요지표</th>
<th style="padding: 0">2025/12(A)</th>
<th style="padding: 0">2026/12(E)</th>
<th class="no-line" style="padding: 0">Fwd. 12M(E)</th>
</tr>
</thead>
<tbody>
<tr>
<th class="left" scope="row">PER</th>
<td class="num">33.14</td>
<td class="num line">5.92</td>
<td class="num line">5.52</td>
</tr>
<tr>
<th class="left" scope="row">PBR</th>
<td class="num">3.40</td>
<td class="num line">2.19</td>
<td class="num line">1.92</td>
</tr>
<tr>
<th class="left" scope="row">PCR</th>
<td class="num">17.19</td>
<td class="num line">4.94</td>
<td class="num line">4.65</td>
</tr>
<tr>
<th class="left" scope="row">EV/EBITDA</th>
<td class="num">14.28</td>
<td class="num line">3.19</td>
<td class="num line">2.78</td>
</tr>
<tr>
<th class="left" scope="row">EPS</th>
<td class="num">6,564원</td>
<td class="num line">36,745원</td>
<td class="num line">39,438원</td>
</tr>
<tr>
<th class="left" scope="row">BPS</th>
<td class="num">63,997원</td>
<td class="num line">99,252원</td>
<td class="num line">113,104원</td>
</tr>
<tr>
<th class="left" scope="row">EBITDA</th>
<td class="num">905,276.4억원</td>
<td class="num line">3,534,695.2억원</td>
<td class="num line">3,768,787.8억원</td>
</tr>
<tr>
<th class="left" scope="row">현금DPS</th>
<td class="num">1,668원</td>
<td class="num line">3,292원</td>
<td class="num line">2,999원</td>
</tr>
<tr>
<th class="left" scope="row">현금배당수익률</th>
<td class="num">0.77%</td>
<td class="num line">1.51%</td>
<td class="num line">1.38%</td>
</tr>
<tr>
<th class="left" scope="row">회계기준</th>
<td class="num">연결</td>
<td class="num line">연결</td>
<td class="num line">연결</td>
</tr>
</tbody>
</table>
<dl class="annotation mb-16 per95">
<dd class="section01 cursor">
<ul>
<li>* Fwd. 12M : 익월부터 향후 12개월의 컨센서스 </li>
</ul>
</dd>
<dd class="section02">
<ul>
<li>* (A)는 실적, (E)는 컨센서스</li>
<li>* 컨센서스 : 최근 3개월간 증권사에서 발표한 추정치의 평균</li>
<li>* 지표 계산 시 주가 : 전 영업일 보통주 수정주가</li>
<li>* 연결 기업의 당기순이익 및 자본총계는 지배주주 기준</li>
</ul>
</dd>
<dd class="section03"><a class="off text-hide" href="javascript:;" title="주석 펼치기/접기">주석 펼치기/접기</a></dd>
</dl>
</div>

In [8]:
# Tag 안에 찾는 단어가 존재하는가?
# Tag 데이터에서 모든 컨텐츠 데이터를 추출 -> get_text()
# 우리가 원하는 단어가 존재하는가? -> find(), in 연산자

list(
    map(
        lambda x : '주요지표' in x.get_text() or '어닝서프라이즈' in x.get_text(),           # x에는 Tag 데이터들 대입
        div_list
    )
)

[False, True, True, False, False]

In [9]:
# read_html()함수를 이용해서 데이터프레임화
# read_html()함수의 결과 -> list -> [df,df,df]
# read_html() 함수는 첫번째 인자 : Tag로 이루어진 문자열
df1 = pd.read_html(str(div_list[1]))[0]
df1

C:\Users\lovek\AppData\Local\Temp\ipykernel_31268\3221323582.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df1 = pd.read_html(str(div_list[1]))[0]

        주요지표   2025/12(A)     2026/12(E)    Fwd. 12M(E)
0        PER        33.14           5.92           5.52
1        PBR         3.40           2.19           1.92
2        PCR        17.19           4.94           4.65
3  EV/EBITDA        14.28           3.19           2.78
4        EPS       6,564원        36,745원        39,438원
5        BPS      63,997원        99,252원       113,104원
6     EBITDA  905,276.4억원  3,534,695.2억원  3,768,787.8억원
7      현금DPS       1,668원         3,292원         2,999원
8    현금배당수익률        0.77%          1.51%          1.38%
9       회계기준           연결             연결             연결

In [10]:
df2 = pd.read_html(str(div_list[2]))[0]
df2

C:\Users\lovek\AppData\Local\Temp\ipykernel_31268\3789423633.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df2 = pd.read_html(str(div_list[2]))[0]

,"어닝서프라이즈 * 단위: 억원, %","어닝서프라이즈 * 단위: 억원, %.1","어닝서프라이즈 * 단위: 억원, %.2","어닝서프라이즈 * 단위: 억원, %.3","어닝서프라이즈 * 단위: 억원, %.4"
0,재무연월,재무연월,2025/09,2025/12,2026/03
1,영업이익,컨센서스,101922.8,185098.0,401923.4
2,영업이익,잠정치,121000.0,200000.0,572000.0
3,영업이익,Surprise,18.72,8.05,42.32
4,영업이익,전분기대비보기전년동기대비,31.76,208.04,755.61
5,NaN,전분기대비,158.77,64.39,184.95
6,NaN,NaN,NaN,NaN,NaN
7,당기순이익,컨센서스,96001.6,163415.8,314258.0
8,당기순이익,잠정치,"● 120,064.0","● 192,920.0",NaN
9,당기순이익,Surprise,25.06,18.05,NaN
10,당기순이익,전분기대비보기전년동기대비,22.75,154.64,NaN
11,NaN,전분기대비,143.34,60.68,NaN
12,잠정치발표(예정)일/회계기준,잠정치발표(예정)일/회계기준,2025/10/14(연결),2026/01/08(연결),2026/04/07(연결)

In [11]:
# 인덱스 6 제거
df2.drop(index = 6, inplace = True)

In [12]:
df2.iloc[:,0] = df2.iloc[:,0].ffill()

In [13]:
df2

,"어닝서프라이즈 * 단위: 억원, %","어닝서프라이즈 * 단위: 억원, %.1","어닝서프라이즈 * 단위: 억원, %.2","어닝서프라이즈 * 단위: 억원, %.3","어닝서프라이즈 * 단위: 억원, %.4"
0,재무연월,재무연월,2025/09,2025/12,2026/03
1,영업이익,컨센서스,101922.8,185098.0,401923.4
2,영업이익,잠정치,121000.0,200000.0,572000.0
3,영업이익,Surprise,18.72,8.05,42.32
4,영업이익,전분기대비보기전년동기대비,31.76,208.04,755.61
5,영업이익,전분기대비,158.77,64.39,184.95
7,당기순이익,컨센서스,96001.6,163415.8,314258.0
8,당기순이익,잠정치,"● 120,064.0","● 192,920.0",NaN
9,당기순이익,Surprise,25.06,18.05,NaN
10,당기순이익,전분기대비보기전년동기대비,22.75,154.64,NaN
11,당기순이익,전분기대비,143.34,60.68,NaN
12,잠정치발표(예정)일/회계기준,잠정치발표(예정)일/회계기준,2025/10/14(연결),2026/01/08(연결),2026/04/07(연결)

In [14]:
df2.set_index([df2.columns[0],df2.columns[1]])

                                          어닝서프라이즈 * 단위: 억원, %.2  \
어닝서프라이즈 * 단위: 억원, % 어닝서프라이즈 * 단위: 억원, %.1
재무연월                재무연월                                2025/09
영업이익                컨센서스                               101922.8
                    잠정치                                121000.0
                    Surprise                              18.72
                    전분기대비보기전년동기대비                         31.76
                    전분기대비                                158.77
당기순이익               컨센서스                                96001.6
                    잠정치                             ● 120,064.0
                    Surprise                              25.06
                    전분기대비보기전년동기대비                         22.75
                    전분기대비                                143.34
잠정치발표(예정)일/회계기준     잠정치발표(예정)일/회계기준              2025/10/14(연결)

                                          어닝서프라이즈 * 단위: 억원, %.3  \
어닝서프라이즈 * 단위: 억원, % 어닝서프라이즈 * 단위: 억원, %.1
재무연월                재무연월                                2025/12
영업이익                컨센서스                               185098.0
                    잠정치                                200000.0
                    Surprise                               8.05
                    전분기대비보기전년동기대비                        208.04
                    전분기대비                                 64.39
당기순이익               컨센서스                               163415.8
                    잠정치                             ● 192,920.0
                    Surprise                              18.05
                    전분기대비보기전년동기대비                        154.64
                    전분기대비                                 60.68
잠정치발표(예정)일/회계기준     잠정치발표(예정)일/회계기준              2026/01/08(연결)

                                          어닝서프라이즈 * 단위: 억원, %.4
어닝서프라이즈 * 단위: 억원, % 어닝서프라이즈 * 단위: 억원, %.1
재무연월                재무연월                                2026/03
영업이익                컨센서스                               401923.4
                    잠정치                                572000.0
                    Surprise                              42.32
                    전분기대비보기전년동기대비                        755.61
                    전분기대비                                184.95
당기순이익               컨센서스                               314258.0
                    잠정치                                     NaN
                    Surprise                                NaN
                    전분기대비보기전년동기대비                           NaN
                    전분기대비                                   NaN
잠정치발표(예정)일/회계기준     잠정치발표(예정)일/회계기준              2026/04/07(연결)

In [15]:
# sqlalchemy
engine = create_engine(
    'mysql+pymysql://root:1234@localhost:3306/multicam'
)

In [ ]:
df1.to_sql(
    name = 'table1',
    con = engine
)

In [ ]:
df2.to_sql(
    name = 'table2',
    con = engine
)

12