In [1]:
import pandas as pd
from db import MyDB

In [2]:
# 로컬 데이터베이스 class 생성
db = MyDB()

In [3]:
# DataBase에 있는 emp, dept 테이블을 이용해서 select문 작성 // pandas를 이용해서 데이터프레임 생성
query_1 = """
    select * from `emp`
"""
sql_result = db.sql_query(query_1)

# sql_result -> [ {} ] 형태
sql_result

[{'EMPNO': 7369.0,
  'ENAME': 'SMITH',
  'JOB': 'CLERK',
  'MGR': 7902.0,
  'HIREDATE': '1980-12-17',
  'SAL': 800.0,
  'COMM': 0.0,
  'DEPTNO': 20.0},
 {'EMPNO': 7499.0,
  'ENAME': 'ALLEN',
  'JOB': 'SALESMAN',
  'MGR': 7698.0,
  'HIREDATE': '1981-02-20',
  'SAL': 1600.0,
  'COMM': 300.0,
  'DEPTNO': 30.0},
 {'EMPNO': 7521.0,
  'ENAME': 'WARD',
  'JOB': 'SALESMAN',
  'MGR': 7698.0,
  'HIREDATE': '1981-02-22',
  'SAL': 1250.0,
  'COMM': 500.0,
  'DEPTNO': 30.0},
 {'EMPNO': 7566.0,
  'ENAME': 'JONES',
  'JOB': 'MANAGER',
  'MGR': 7839.0,
  'HIREDATE': '1981-04-02',
  'SAL': 2975.0,
  'COMM': 0.0,
  'DEPTNO': 20.0},
 {'EMPNO': 7654.0,
  'ENAME': 'MARTIN',
  'JOB': 'SALESMAN',
  'MGR': 7698.0,
  'HIREDATE': '1981-09-28',
  'SAL': 1250.0,
  'COMM': 1400.0,
  'DEPTNO': 30.0},
 {'EMPNO': 7698.0,
  'ENAME': 'BLAKE',
  'JOB': 'MANAGER',
  'MGR': 7839.0,
  'HIREDATE': '1981-05-01',
  'SAL': 2850.0,
  'COMM': 0.0,
  'DEPTNO': 30.0},
 {'EMPNO': 7782.0,
  'ENAME': 'CLARK',
  'JOB': 'MANAGER',
  'MGR': 7839.0,
  'HIREDATE': '1981-06-09',
  'SAL': 2450.0,
  'COMM': 0.0,
  'DEPTNO': 10.0},
 {'EMPNO': 7788.0,
  'ENAME': 'SCOTT',
  'JOB': 'ANALYST',
  'MGR': 7566.0,
  'HIREDATE': '1987-06-28',
  'SAL': 3000.0,
  'COMM': 0.0,
  'DEPTNO': 20.0},
 {'EMPNO': 7839.0,
  'ENAME': 'KING',
  'JOB': 'PRESIDENT',
  'MGR': 0.0,
  'HIREDATE': '1981-11-17',
  'SAL': 5000.0,
  'COMM': 0.0,
  'DEPTNO': 10.0},
 {'EMPNO': 7844.0,
  'ENAME': 'TURNER',
  'JOB': 'SALESMAN',
  'MGR': 7698.0,
  'HIREDATE': '1981-09-08',
  'SAL': 1500.0,
  'COMM': 0.0,
  'DEPTNO': 30.0},
 {'EMPNO': 7876.0,
  'ENAME': 'ADAMS',
  'JOB': 'CLERK',
  'MGR': 7788.0,
  'HIREDATE': '1987-07-13',
  'SAL': 1100.0,
  'COMM': 0.0,
  'DEPTNO': 20.0},
 {'EMPNO': 7900.0,
  'ENAME': 'JAMES',
  'JOB': 'CLERK',
  'MGR': 7698.0,
  'HIREDATE': '1981-12-03',
  'SAL': 950.0,
  'COMM': 0.0,
  'DEPTNO': 30.0},
 {'EMPNO': 7902.0,
  'ENAME': 'FORD',
  'JOB': 'ANALYST',
  'MGR': 7566.0,
  'HIREDATE': '1981-12-03',
  'SAL': 3000.0,
  'COMM': 0.0,
  'DEPTNO': 20.0},
 {'EMPNO': 7934.0,
  'ENAME': 'MILLER',
  'JOB': 'CLERK',
  'MGR': 7782.0,
  'HIREDATE': '1982-01-23',
  'SAL': 1300.0,
  'COMM': 0.0,
  'DEPTNO': 10.0}]

In [4]:
emp_df = pd.DataFrame(sql_result)
emp_df

     EMPNO   ENAME        JOB     MGR    HIREDATE     SAL    COMM  DEPTNO
0   7369.0   SMITH      CLERK  7902.0  1980-12-17   800.0     0.0    20.0
1   7499.0   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0    30.0
2   7521.0    WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0    30.0
3   7566.0   JONES    MANAGER  7839.0  1981-04-02  2975.0     0.0    20.0
4   7654.0  MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0    30.0
5   7698.0   BLAKE    MANAGER  7839.0  1981-05-01  2850.0     0.0    30.0
6   7782.0   CLARK    MANAGER  7839.0  1981-06-09  2450.0     0.0    10.0
7   7788.0   SCOTT    ANALYST  7566.0  1987-06-28  3000.0     0.0    20.0
8   7839.0    KING  PRESIDENT     0.0  1981-11-17  5000.0     0.0    10.0
9   7844.0  TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0    30.0
10  7876.0   ADAMS      CLERK  7788.0  1987-07-13  1100.0     0.0    20.0
11  7900.0   JAMES      CLERK  7698.0  1981-12-03   950.0     0.0    30.0
12  7902.0    FORD    ANALYST  7566.0  1981-12-03  3000.0     0.0    20.0
13  7934.0  MILLER      CLERK  7782.0  1982-01-23  1300.0     0.0    10.0

In [5]:
# read_csv() 함수를 이용해서 csv 파일 로드
emp_df2 = pd.read_csv('../csv/emp.csv')
emp_df2

     EMPNO   ENAME        JOB     MGR    HIREDATE     SAL    COMM  DEPTNO
0   7369.0   SMITH      CLERK  7902.0  1980-12-17   800.0     0.0    20.0
1   7499.0   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0    30.0
2   7521.0    WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0    30.0
3   7566.0   JONES    MANAGER  7839.0  1981-04-02  2975.0     0.0    20.0
4   7654.0  MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0    30.0
5   7698.0   BLAKE    MANAGER  7839.0  1981-05-01  2850.0     0.0    30.0
6   7782.0   CLARK    MANAGER  7839.0  1981-06-09  2450.0     0.0    10.0
7   7788.0   SCOTT    ANALYST  7566.0  1987-06-28  3000.0     0.0    20.0
8   7839.0    KING  PRESIDENT     0.0  1981-11-17  5000.0     0.0    10.0
9   7844.0  TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0    30.0
10  7876.0   ADAMS      CLERK  7788.0  1987-07-13  1100.0     0.0    20.0
11  7900.0   JAMES      CLERK  7698.0  1981-12-03   950.0     0.0    30.0
12  7902.0    FORD    ANALYST  7566.0  1981-12-03  3000.0     0.0    20.0
13  7934.0  MILLER      CLERK  7782.0  1982-01-23  1300.0     0.0    10.0

In [6]:
dept_df = pd.read_csv('../csv/dept.csv')
dept_df

   DEPTNO       DNAME       LOC
0    10.0  ACCOUNTING  NEW YORK
1    20.0    RESEARCH    DALLAS
2    30.0       SALES   CHICAGO
3    40.0  OPERATIONS    BOSTON

In [7]:
query_2 = """
    select * from `dept`
"""

pd.DataFrame(
    db.sql_query(query_2)
)

접속된 서버가 존재함

   DEPTNO       DNAME       LOC
0    10.0  ACCOUNTING  NEW YORK
1    20.0    RESEARCH    DALLAS
2    30.0       SALES   CHICAGO
3    40.0  OPERATIONS    BOSTON

In [9]:
# emp_df에서 SAL 컬럼의 데이터가 1500 이상인 사원의 모든 정보를 확인
# DataFrame를 이용해서 확인

# 조건 -> SAL 컬럼의 데이터가 1500 이상(인덱스의 조건식) // 사원의 모든 정보(컬럼의 조건 : 모든 컬럼)
index_flag = emp_df['SAL'] >= 1500
index_flag

0     False
1      True
2     False
3      True
4     False
5      True
6      True
7      True
8      True
9      True
10    False
11    False
12     True
13    False
Name: SAL, dtype: bool

In [10]:
# 데이터프레임이 필터 -> loc[인덱스의 조건식, 컬럼의 조건식], iloc[인덱스의 위치, 컬럼의 위치]
emp_df.loc[index_flag]

     EMPNO   ENAME        JOB     MGR    HIREDATE     SAL   COMM  DEPTNO
1   7499.0   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0  300.0    30.0
3   7566.0   JONES    MANAGER  7839.0  1981-04-02  2975.0    0.0    20.0
5   7698.0   BLAKE    MANAGER  7839.0  1981-05-01  2850.0    0.0    30.0
6   7782.0   CLARK    MANAGER  7839.0  1981-06-09  2450.0    0.0    10.0
7   7788.0   SCOTT    ANALYST  7566.0  1987-06-28  3000.0    0.0    20.0
8   7839.0    KING  PRESIDENT     0.0  1981-11-17  5000.0    0.0    10.0
9   7844.0  TURNER   SALESMAN  7698.0  1981-09-08  1500.0    0.0    30.0
12  7902.0    FORD    ANALYST  7566.0  1981-12-03  3000.0    0.0    20.0

In [11]:
# SAL이 1500 이상인 사원 정보를 출력한다. SQL 쿼리문 이용
# select {컬럼의 선택 || 컬럼의 연산} from table명 where 인덱스의 조건식
query_3 = """
    select * from `emp`
    where `sal` >= 1500
"""

pd.DataFrame(
    db.sql_query(query_3)
)

접속된 서버가 존재함

    EMPNO   ENAME        JOB     MGR    HIREDATE     SAL   COMM  DEPTNO
0  7499.0   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0  300.0    30.0
1  7566.0   JONES    MANAGER  7839.0  1981-04-02  2975.0    0.0    20.0
2  7698.0   BLAKE    MANAGER  7839.0  1981-05-01  2850.0    0.0    30.0
3  7782.0   CLARK    MANAGER  7839.0  1981-06-09  2450.0    0.0    10.0
4  7788.0   SCOTT    ANALYST  7566.0  1987-06-28  3000.0    0.0    20.0
5  7839.0    KING  PRESIDENT     0.0  1981-11-17  5000.0    0.0    10.0
6  7844.0  TURNER   SALESMAN  7698.0  1981-09-08  1500.0    0.0    30.0
7  7902.0    FORD    ANALYST  7566.0  1981-12-03  3000.0    0.0    20.0

In [16]:
# pandas 버전
# SAL이 1500이상이고 JOB가 MANAGER인사원의 사원번호와 이름을 출력
# 인덱스의 조건 : SAL이 1500 이상 and JOB이 MANAGER
# 컬럼의 조건 : 사원 정보 중 사원번호, 사원이름
index_flag1 = emp_df['SAL'] >= 1500
index_flag2 = emp_df['JOB'] == 'MANAGER'
col_flag = ['EMPNO','ENAME']
emp_df.loc[
    index_flag1 & index_flag2, col_flag
]

    EMPNO  ENAME
3  7566.0  JONES
5  7698.0  BLAKE
6  7782.0  CLARK

In [19]:
# SQL 버전
query_4 = """
    select `empno`, `ename` from `emp`
    where `sal` >= 1500 and `JOB` = 'MANAGER'
"""
pd.DataFrame(
    db.sql_query(query_4)
)

접속된 서버가 존재함

    empno  ename
0  7566.0  JONES
1  7698.0  BLAKE
2  7782.0  CLARK

In [20]:
# sql 버전
# SAL 1500 이상 2500 이하인 사원의 모든 정보 확인
query_4 = """
    select * from emp
    where sal >= 1500 and sal <= 2500
"""
pd.DataFrame(
    db.sql_query(query_4)
)

접속된 서버가 존재함

    EMPNO   ENAME       JOB     MGR    HIREDATE     SAL   COMM  DEPTNO
0  7499.0   ALLEN  SALESMAN  7698.0  1981-02-20  1600.0  300.0    30.0
1  7782.0   CLARK   MANAGER  7839.0  1981-06-09  2450.0    0.0    10.0
2  7844.0  TURNER  SALESMAN  7698.0  1981-09-08  1500.0    0.0    30.0

In [22]:
query_5 = """
    select * from emp
    where sal between 1500 and 2500
"""
pd.DataFrame(
    db.sql_query(query_5)
)

접속된 서버가 존재함

    EMPNO   ENAME       JOB     MGR    HIREDATE     SAL   COMM  DEPTNO
0  7499.0   ALLEN  SALESMAN  7698.0  1981-02-20  1600.0  300.0    30.0
1  7782.0   CLARK   MANAGER  7839.0  1981-06-09  2450.0    0.0    10.0
2  7844.0  TURNER  SALESMAN  7698.0  1981-09-08  1500.0    0.0    30.0

In [23]:
# pandas 버전
# 인덱스 조건 : sal이 1500 이상 그리고 sal이 2500 이하
index_flag1 = emp_df['SAL'] >= 1500
index_flag2 = emp_df['SAL'] <= 2500
emp_df.loc[index_flag1 & index_flag2, ]

    EMPNO   ENAME       JOB     MGR    HIREDATE     SAL   COMM  DEPTNO
1  7499.0   ALLEN  SALESMAN  7698.0  1981-02-20  1600.0  300.0    30.0
6  7782.0   CLARK   MANAGER  7839.0  1981-06-09  2450.0    0.0    10.0
9  7844.0  TURNER  SALESMAN  7698.0  1981-09-08  1500.0    0.0    30.0

In [24]:
# 포함되어 있는가? 포함(in), 존재여부(is)
emp_df.loc[
    emp_df['SAL'].isin(range(1500,2501)),
]

    EMPNO   ENAME       JOB     MGR    HIREDATE     SAL   COMM  DEPTNO
1  7499.0   ALLEN  SALESMAN  7698.0  1981-02-20  1600.0  300.0    30.0
6  7782.0   CLARK   MANAGER  7839.0  1981-06-09  2450.0    0.0    10.0
9  7844.0  TURNER  SALESMAN  7698.0  1981-09-08  1500.0    0.0    30.0

In [25]:
# 사잇값 : between()
emp_df.loc[
    emp_df['SAL'].between(1500,2500),
]

    EMPNO   ENAME       JOB     MGR    HIREDATE     SAL   COMM  DEPTNO
1  7499.0   ALLEN  SALESMAN  7698.0  1981-02-20  1600.0  300.0    30.0
6  7782.0   CLARK   MANAGER  7839.0  1981-06-09  2450.0    0.0    10.0
9  7844.0  TURNER  SALESMAN  7698.0  1981-09-08  1500.0    0.0    30.0

In [26]:
# JOB이 MANAGER이거나 SALESMAN인 경우 모든 사원 정보를 확인
# SQL
query_6 = """
    select * from emp
    where job = 'MANAGER' or job = 'SALESMAN'
"""
pd.DataFrame(
    db.sql_query(query_6)
)

접속된 서버가 존재함

    EMPNO   ENAME       JOB     MGR    HIREDATE     SAL    COMM  DEPTNO
0  7499.0   ALLEN  SALESMAN  7698.0  1981-02-20  1600.0   300.0    30.0
1  7521.0    WARD  SALESMAN  7698.0  1981-02-22  1250.0   500.0    30.0
2  7566.0   JONES   MANAGER  7839.0  1981-04-02  2975.0     0.0    20.0
3  7654.0  MARTIN  SALESMAN  7698.0  1981-09-28  1250.0  1400.0    30.0
4  7698.0   BLAKE   MANAGER  7839.0  1981-05-01  2850.0     0.0    30.0
5  7782.0   CLARK   MANAGER  7839.0  1981-06-09  2450.0     0.0    10.0
6  7844.0  TURNER  SALESMAN  7698.0  1981-09-08  1500.0     0.0    30.0

In [27]:
query_7 = """
    select * from emp
    where job in ('MANAGER','SALESMAN')
"""
pd.DataFrame(
    db.sql_query(query_7)
)

접속된 서버가 존재함

    EMPNO   ENAME       JOB     MGR    HIREDATE     SAL    COMM  DEPTNO
0  7499.0   ALLEN  SALESMAN  7698.0  1981-02-20  1600.0   300.0    30.0
1  7521.0    WARD  SALESMAN  7698.0  1981-02-22  1250.0   500.0    30.0
2  7566.0   JONES   MANAGER  7839.0  1981-04-02  2975.0     0.0    20.0
3  7654.0  MARTIN  SALESMAN  7698.0  1981-09-28  1250.0  1400.0    30.0
4  7698.0   BLAKE   MANAGER  7839.0  1981-05-01  2850.0     0.0    30.0
5  7782.0   CLARK   MANAGER  7839.0  1981-06-09  2450.0     0.0    10.0
6  7844.0  TURNER  SALESMAN  7698.0  1981-09-08  1500.0     0.0    30.0

In [28]:
def sql(query):
    result = pd.DataFrame(
        db.sql_query(query)
    )
    return result

In [30]:
# pandas 버전
# 조건식을 2개 사용
flag1 = emp_df['JOB'] == 'MANAGER'
flag2 = emp_df['JOB'] == 'SALESMAN'
emp_df.loc[
    flag1 | flag2,
]

    EMPNO   ENAME       JOB     MGR    HIREDATE     SAL    COMM  DEPTNO
1  7499.0   ALLEN  SALESMAN  7698.0  1981-02-20  1600.0   300.0    30.0
2  7521.0    WARD  SALESMAN  7698.0  1981-02-22  1250.0   500.0    30.0
3  7566.0   JONES   MANAGER  7839.0  1981-04-02  2975.0     0.0    20.0
4  7654.0  MARTIN  SALESMAN  7698.0  1981-09-28  1250.0  1400.0    30.0
5  7698.0   BLAKE   MANAGER  7839.0  1981-05-01  2850.0     0.0    30.0
6  7782.0   CLARK   MANAGER  7839.0  1981-06-09  2450.0     0.0    10.0
9  7844.0  TURNER  SALESMAN  7698.0  1981-09-08  1500.0     0.0    30.0

In [33]:
# 포함 여부 -> isin()
flag1 = emp_df['JOB'].isin(['MANAGER','SALESMAN'])
emp_df.loc[flag1,]

    EMPNO   ENAME       JOB     MGR    HIREDATE     SAL    COMM  DEPTNO
1  7499.0   ALLEN  SALESMAN  7698.0  1981-02-20  1600.0   300.0    30.0
2  7521.0    WARD  SALESMAN  7698.0  1981-02-22  1250.0   500.0    30.0
3  7566.0   JONES   MANAGER  7839.0  1981-04-02  2975.0     0.0    20.0
4  7654.0  MARTIN  SALESMAN  7698.0  1981-09-28  1250.0  1400.0    30.0
5  7698.0   BLAKE   MANAGER  7839.0  1981-05-01  2850.0     0.0    30.0
6  7782.0   CLARK   MANAGER  7839.0  1981-06-09  2450.0     0.0    10.0
9  7844.0  TURNER  SALESMAN  7698.0  1981-09-08  1500.0     0.0    30.0

In [39]:
# emp table에서 ename이 s로 시작하는 사원의 정보를 확인
# % -> python 특수 기능 ( 경로에 \가 포함되어있으면 \\, /로 변경 (r-string) ) -> %%로 이용
query_8 = """
    select * from emp
    where ename like 's%%'
"""

sql(query_8)

접속된 서버가 존재함

    EMPNO  ENAME      JOB     MGR    HIREDATE     SAL  COMM  DEPTNO
0  7369.0  SMITH    CLERK  7902.0  1980-12-17   800.0   0.0    20.0
1  7788.0  SCOTT  ANALYST  7566.0  1987-06-28  3000.0   0.0    20.0

In [48]:
# pandas에서 ename이 s로 시작하는 사원의 정보를 출력하시오
# sql은 대소문자를 구분하지 않지만 python은 대소문자 구분

# 찾는 단어 s | S
word = 's'

flag_list = []

for name in emp_df['ENAME']:
    # print(name)
    # 문자의 시작이 word와 같은 경우라면? --> startswith() | 문자에서 처음부터 word 길이까지를 추출
    # print(name[:len(word)])
    # print(name[:len(word)].lower() == word.lower())
    # print(name.lower().startswith(word.lower()))
    flag_list.append(
        # 특정문자로 시작하는 경우
        # name.lower().startswith(word.lower())
        # 특정문자로 끝나는 경우
        # name.lower().endswith(word.lower())
        # 특정문자가 포함(in)되어 있는 경우 -> 특정문자가 name에 포함되어있는가?
        word.lower() in name.lower()
    )
    flag_list

In [49]:
emp_df.loc[
    flag_list,
]

     EMPNO  ENAME      JOB     MGR    HIREDATE     SAL  COMM  DEPTNO
0   7369.0  SMITH    CLERK  7902.0  1980-12-17   800.0   0.0    20.0
3   7566.0  JONES  MANAGER  7839.0  1981-04-02  2975.0   0.0    20.0
7   7788.0  SCOTT  ANALYST  7566.0  1987-06-28  3000.0   0.0    20.0
10  7876.0  ADAMS    CLERK  7788.0  1987-07-13  1100.0   0.0    20.0
11  7900.0  JAMES    CLERK  7698.0  1981-12-03   950.0   0.0    30.0

In [ ]:
word = 's'
# 특정 문자로 시작하는 조건식 생성
emp_df['ENAME'].str.lower().str.startswith(word.lower())

0      True
1     False
2     False
3     False
4     False
5     False
6     False
7      True
8     False
9     False
10    False
11    False
12    False
13    False
Name: ENAME, dtype: bool

In [54]:
word = 's'
# 특정 문자로 시작하는 조건식 생성
emp_df['ENAME'].str.lower().str.startswith(word.lower())

0      True
1     False
2     False
3     False
4     False
5     False
6     False
7      True
8     False
9     False
10    False
11    False
12    False
13    False
Name: ENAME, dtype: bool

In [53]:
# 특정문자로 끝나는 조건식 생성
emp_df['ENAME'].str.lower().str.endswith(word.lower())

0     False
1     False
2     False
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11     True
12    False
13    False
Name: ENAME, dtype: bool

In [56]:
# 특정문자가 포함되어 있는 조건식 생성
flag = emp_df['ENAME'].str.lower().str.contains(word.lower())
emp_df.loc[flag,]

     EMPNO  ENAME      JOB     MGR    HIREDATE     SAL  COMM  DEPTNO
0   7369.0  SMITH    CLERK  7902.0  1980-12-17   800.0   0.0    20.0
3   7566.0  JONES  MANAGER  7839.0  1981-04-02  2975.0   0.0    20.0
7   7788.0  SCOTT  ANALYST  7566.0  1987-06-28  3000.0   0.0    20.0
10  7876.0  ADAMS    CLERK  7788.0  1987-07-13  1100.0   0.0    20.0
11  7900.0  JAMES    CLERK  7698.0  1981-12-03   950.0   0.0    30.0

In [57]:
# emp, dept 테이블
# 테이블 간의 결합 -> 사원의 정보 테이블과 부서의 정보 테이블 -> 조건에 맞게 결합이 되는 형태 -> 조인 결합
# 조인 결합 -> pandas에서는 merge() 함수를 이용

- 유니언 결합
    - 단순 결합 ( 행, 열 )
    - pandas에서는 concat([데이터프레임,데이터프레임, ...]) 함수를 이용
    - 단순 결합의 형태이기 때문에 데이터프레임의 개수의 제한 x
        - 매개변수
            - axis
                - 행으로 결합할 것인가, 열로 결합할 것인가
            - ignore_index
                - 결합되는 축을 초기화 할것인가
    - SQL에서는 UNION 키워드를 이용해서 결합
        - SELECT문 UNION SELECT문
- 조인 결합
    - 특정한 조건에 맞춰서 열을 결합
    - 데이터프레임과 데이터프레임간의 결합 -> 특정 컬럼의 데이터들이 같은 값들로 이루어져있는 경우 열을 추가하는 방식
    - pandas, DataFrame에 내장된 merge() 함수를 이용
    - 조건에 맞춰서 결합이 되기 때문에 데이터프레임은 2개 결합
        - 매개변수
            - on
                - 조건식 -> 2개의 데이터프레임이 모두 가지고 있는 컬럼의 이름
                - 각 데이터프레임의 컬럼의 이름이 다른 경우에는 left_on, right_on 매개변수를 이용\
            - how
                - 조인 결합의 방식(left, right, inner, outer)
    - SQL에서는 JOIN 키워드를 이용해서 결합
        - select * from table1 inner join table2 on table1.col = tabl2.col

In [58]:
# 조인 결합 SQL
query_9 = """
    select * from emp left join dept on emp.deptno = dept.deptno
"""

sql(query_9)

접속된 서버가 존재함

,EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,dept.DEPTNO,DNAME,LOC
0,7369.0,SMITH,CLERK,7902.0,1980-12-17,800.0,0.0,20.0,20.0,RESEARCH,DALLAS
1,7499.0,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30.0,30.0,SALES,CHICAGO
2,7521.0,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30.0,30.0,SALES,CHICAGO
3,7566.0,JONES,MANAGER,7839.0,1981-04-02,2975.0,0.0,20.0,20.0,RESEARCH,DALLAS
4,7654.0,MARTIN,SALESMAN,7698.0,1981-09-28,1250.0,1400.0,30.0,30.0,SALES,CHICAGO
5,7698.0,BLAKE,MANAGER,7839.0,1981-05-01,2850.0,0.0,30.0,30.0,SALES,CHICAGO
6,7782.0,CLARK,MANAGER,7839.0,1981-06-09,2450.0,0.0,10.0,10.0,ACCOUNTING,NEW YORK
7,7788.0,SCOTT,ANALYST,7566.0,1987-06-28,3000.0,0.0,20.0,20.0,RESEARCH,DALLAS
8,7839.0,KING,PRESIDENT,0.0,1981-11-17,5000.0,0.0,10.0,10.0,ACCOUNTING,NEW YORK
9,7844.0,TURNER,SALESMAN,7698.0,1981-09-08,1500.0,0.0,30.0,30.0,SALES,CHICAGO
10,7876.0,ADAMS,CLERK,7788.0,1987-07-13,1100.0,0.0,20.0,20.0,RESEARCH,DALLAS
11,7900.0,JAMES,CLERK,7698.0,1981-12-03,950.0,0.0,30.0,30.0,SALES,CHICAGO
12,7902.0,FORD,ANALYST,7566.0,1981-12-03,3000.0,0.0,20.0,20.0,RESEARCH,DALLAS
13,7934.0,MILLER,CLERK,7782.0,1982-01-23,1300.0,0.0,10.0,10.0,ACCOUNTING,NEW YORK

In [60]:
pd.merge(emp_df,dept_df,on='DEPTNO',how='left')

,EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,DNAME,LOC
0,7369.0,SMITH,CLERK,7902.0,1980-12-17,800.0,0.0,20.0,RESEARCH,DALLAS
1,7499.0,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30.0,SALES,CHICAGO
2,7521.0,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30.0,SALES,CHICAGO
3,7566.0,JONES,MANAGER,7839.0,1981-04-02,2975.0,0.0,20.0,RESEARCH,DALLAS
4,7654.0,MARTIN,SALESMAN,7698.0,1981-09-28,1250.0,1400.0,30.0,SALES,CHICAGO
5,7698.0,BLAKE,MANAGER,7839.0,1981-05-01,2850.0,0.0,30.0,SALES,CHICAGO
6,7782.0,CLARK,MANAGER,7839.0,1981-06-09,2450.0,0.0,10.0,ACCOUNTING,NEW YORK
7,7788.0,SCOTT,ANALYST,7566.0,1987-06-28,3000.0,0.0,20.0,RESEARCH,DALLAS
8,7839.0,KING,PRESIDENT,0.0,1981-11-17,5000.0,0.0,10.0,ACCOUNTING,NEW YORK
9,7844.0,TURNER,SALESMAN,7698.0,1981-09-08,1500.0,0.0,30.0,SALES,CHICAGO
10,7876.0,ADAMS,CLERK,7788.0,1987-07-13,1100.0,0.0,20.0,RESEARCH,DALLAS
11,7900.0,JAMES,CLERK,7698.0,1981-12-03,950.0,0.0,30.0,SALES,CHICAGO
12,7902.0,FORD,ANALYST,7566.0,1981-12-03,3000.0,0.0,20.0,RESEARCH,DALLAS
13,7934.0,MILLER,CLERK,7782.0,1982-01-23,1300.0,0.0,10.0,ACCOUNTING,NEW YORK

In [62]:
dept_df2 = dept_df.copy()

In [66]:
dept_df2.rename(
    columns={
        'DEPTNO' : 'DEPTNUM'
    },inplace = True
)

In [67]:
# merge 함수에서 결합하려는 2개의 데이터프레임이 컬럼의 이름이 다른 경우
# emp 테이블에는 DEPTNO와 dept 테이블에서는 DEPTNUM의 데이터가 같은 경우
pd.merge(
    emp_df, dept_df2, left_on = 'DEPTNO', right_on = 'DEPTNUM', how = 'left'
)

,EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,DEPTNUM,DNAME,LOC
0,7369.0,SMITH,CLERK,7902.0,1980-12-17,800.0,0.0,20.0,20.0,RESEARCH,DALLAS
1,7499.0,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30.0,30.0,SALES,CHICAGO
2,7521.0,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30.0,30.0,SALES,CHICAGO
3,7566.0,JONES,MANAGER,7839.0,1981-04-02,2975.0,0.0,20.0,20.0,RESEARCH,DALLAS
4,7654.0,MARTIN,SALESMAN,7698.0,1981-09-28,1250.0,1400.0,30.0,30.0,SALES,CHICAGO
5,7698.0,BLAKE,MANAGER,7839.0,1981-05-01,2850.0,0.0,30.0,30.0,SALES,CHICAGO
6,7782.0,CLARK,MANAGER,7839.0,1981-06-09,2450.0,0.0,10.0,10.0,ACCOUNTING,NEW YORK
7,7788.0,SCOTT,ANALYST,7566.0,1987-06-28,3000.0,0.0,20.0,20.0,RESEARCH,DALLAS
8,7839.0,KING,PRESIDENT,0.0,1981-11-17,5000.0,0.0,10.0,10.0,ACCOUNTING,NEW YORK
9,7844.0,TURNER,SALESMAN,7698.0,1981-09-08,1500.0,0.0,30.0,30.0,SALES,CHICAGO
10,7876.0,ADAMS,CLERK,7788.0,1987-07-13,1100.0,0.0,20.0,20.0,RESEARCH,DALLAS
11,7900.0,JAMES,CLERK,7698.0,1981-12-03,950.0,0.0,30.0,30.0,SALES,CHICAGO
12,7902.0,FORD,ANALYST,7566.0,1981-12-03,3000.0,0.0,20.0,20.0,RESEARCH,DALLAS
13,7934.0,MILLER,CLERK,7782.0,1982-01-23,1300.0,0.0,10.0,10.0,ACCOUNTING,NEW YORK

In [68]:
# 유니언 결합 sql -> tran_1, tran_2 테이블을 유니언 결합
query_10 = """
    select * from tran_1
    union
    select * from tran_2
"""
sql(query_10)

접속된 서버가 존재함

     transaction_id   price         payment_date customer_id
0       T0000000113  210000  2019-02-01 01:36:57    PL563502
1       T0000000114   50000  2019-02-01 01:37:23    HD678019
2       T0000000115  120000  2019-02-01 02:34:19    HD298120
3       T0000000116  210000  2019-02-01 02:47:23    IK452215
4       T0000000117  170000  2019-02-01 04:33:46    PL542865
...             ...     ...                  ...         ...
6781    T0000006894  180000  2019-07-31 21:20:44    HI400734
6782    T0000006895   85000  2019-07-31 21:52:48    AS339451
6783    T0000006896  100000  2019-07-31 23:35:25    OA027325
6784    T0000006897   85000  2019-07-31 23:39:35    TS624738
6785    T0000006898   85000  2019-07-31 23:41:38    AS834214

[6786 rows x 4 columns]

In [70]:
tran_1 = pd.read_csv('../csv/tran_1.csv')
tran_2 = pd.read_csv('../csv/tran_2.csv')
tran_d1 = pd.read_csv('../csv/tran_d_1.csv')
tran_d2 = pd.read_csv('../csv/tran_d_2.csv')

In [74]:
pd.concat([tran_1,tran_2],axis=0,ignore_index=True).rename(
    columns = {
        'transaction_id' : '거래고유번호',
        'price' : '가격',
        'payment_date' : '거래일자',
        'customer_id' : '고객고유번호'
    }
)

           거래고유번호      가격                 거래일자    고객고유번호
0     T0000000113  210000  2019-02-01 01:36:57  PL563502
1     T0000000114   50000  2019-02-01 01:37:23  HD678019
2     T0000000115  120000  2019-02-01 02:34:19  HD298120
3     T0000000116  210000  2019-02-01 02:47:23  IK452215
4     T0000000117  170000  2019-02-01 04:33:46  PL542865
...           ...     ...                  ...       ...
6781  T0000006894  180000  2019-07-31 21:20:44  HI400734
6782  T0000006895   85000  2019-07-31 21:52:48  AS339451
6783  T0000006896  100000  2019-07-31 23:35:25  OA027325
6784  T0000006897   85000  2019-07-31 23:39:35  TS624738
6785  T0000006898   85000  2019-07-31 23:41:38  AS834214

[6786 rows x 4 columns]

In [79]:
# tran_1과 tran_d_1 테이블을 조인 결합
query_11 = """
    select
    t1.transaction_id, price, payment_date,quantity
    from tran_1 as t1
    left join
    tran_d_1 as td1
    on
    t1.transaction_id = td1.transaction_id
"""
sql(query_11)

접속된 서버가 존재함

     transaction_id   price         payment_date  quantity
0       T0000000113  210000  2019-02-01 01:36:57       1.0
1       T0000000114   50000  2019-02-01 01:37:23       1.0
2       T0000000115  120000  2019-02-01 02:34:19       1.0
3       T0000000116  210000  2019-02-01 02:47:23       1.0
4       T0000000117  170000  2019-02-01 04:33:46       2.0
...             ...     ...                  ...       ...
5238    T0000005108  210000  2019-06-15 02:42:41       NaN
5239    T0000005109  150000  2019-06-15 03:36:16       NaN
5240    T0000005110   50000  2019-06-15 03:44:06       NaN
5241    T0000005111  210000  2019-06-15 04:14:06       NaN
5242    T0000005112   50000  2019-06-15 04:42:38       NaN

[5243 rows x 4 columns]

In [81]:
# 정렬 방식 -> pandas : sort_values()
# ORDER BY 컬러명 ASC(기본값 - 생략가능) | DESC(내림차순)
query_12 = """
    select * from emp
    order by ename desc
"""

sql(query_12)

접속된 서버가 존재함

     EMPNO   ENAME        JOB     MGR    HIREDATE     SAL    COMM  DEPTNO
0   7521.0    WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0    30.0
1   7844.0  TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0    30.0
2   7369.0   SMITH      CLERK  7902.0  1980-12-17   800.0     0.0    20.0
3   7788.0   SCOTT    ANALYST  7566.0  1987-06-28  3000.0     0.0    20.0
4   7934.0  MILLER      CLERK  7782.0  1982-01-23  1300.0     0.0    10.0
5   7654.0  MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0    30.0
6   7839.0    KING  PRESIDENT     0.0  1981-11-17  5000.0     0.0    10.0
7   7566.0   JONES    MANAGER  7839.0  1981-04-02  2975.0     0.0    20.0
8   7900.0   JAMES      CLERK  7698.0  1981-12-03   950.0     0.0    30.0
9   7902.0    FORD    ANALYST  7566.0  1981-12-03  3000.0     0.0    20.0
10  7782.0   CLARK    MANAGER  7839.0  1981-06-09  2450.0     0.0    10.0
11  7698.0   BLAKE    MANAGER  7839.0  1981-05-01  2850.0     0.0    30.0
12  7499.0   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0    30.0
13  7876.0   ADAMS      CLERK  7788.0  1987-07-13  1100.0     0.0    20.0

In [83]:
emp_df.sort_values('ENAME',ascending=False)

     EMPNO   ENAME        JOB     MGR    HIREDATE     SAL    COMM  DEPTNO
2   7521.0    WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0    30.0
9   7844.0  TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0    30.0
0   7369.0   SMITH      CLERK  7902.0  1980-12-17   800.0     0.0    20.0
7   7788.0   SCOTT    ANALYST  7566.0  1987-06-28  3000.0     0.0    20.0
13  7934.0  MILLER      CLERK  7782.0  1982-01-23  1300.0     0.0    10.0
4   7654.0  MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0    30.0
8   7839.0    KING  PRESIDENT     0.0  1981-11-17  5000.0     0.0    10.0
3   7566.0   JONES    MANAGER  7839.0  1981-04-02  2975.0     0.0    20.0
11  7900.0   JAMES      CLERK  7698.0  1981-12-03   950.0     0.0    30.0
12  7902.0    FORD    ANALYST  7566.0  1981-12-03  3000.0     0.0    20.0
6   7782.0   CLARK    MANAGER  7839.0  1981-06-09  2450.0     0.0    10.0
5   7698.0   BLAKE    MANAGER  7839.0  1981-05-01  2850.0     0.0    30.0
1   7499.0   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0    30.0
10  7876.0   ADAMS      CLERK  7788.0  1987-07-13  1100.0     0.0    20.0

In [90]:
# 그룹화 -> pandas groupby() -> 그룹화 연산
# GROUP BY
query_13 = """
    select
    job, avg(sal) as avg_sal, sum(sal) as sum_sal, count(sal) as count
    from emp
    group by job
"""

sql(query_13)

접속된 서버가 존재함

         job      avg_sal  sum_sal  count
0      CLERK  1037.500000   4150.0      4
1   SALESMAN  1400.000000   5600.0      4
2    MANAGER  2758.333333   8275.0      3
3    ANALYST  3000.000000   6000.0      2
4  PRESIDENT  5000.000000   5000.0      1

In [95]:
emp_df[['JOB','SAL']].groupby('JOB').agg(['mean','sum','count'])

                   SAL
                  mean     sum count
JOB
ANALYST    3000.000000  6000.0     2
CLERK      1037.500000  4150.0     4
MANAGER    2758.333333  8275.0     3
PRESIDENT  5000.000000  5000.0     1
SALESMAN   1400.000000  5600.0     4

In [97]:
# 서브 쿼리
# 부서의 지역이 NEW YORK, CHICAGO인 사원의 정보를 확인
# 부서 테이블의 뉴욕, 시카고인 부서의 번호를 받아서 사원 정보 테이블에 필터
query_14 = """
    select * from emp
    where deptno in (10,30)
"""
sql(query_14)

접속된 서버가 존재함

    EMPNO   ENAME        JOB     MGR    HIREDATE     SAL    COMM  DEPTNO
0  7499.0   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0    30.0
1  7521.0    WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0    30.0
2  7654.0  MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0    30.0
3  7698.0   BLAKE    MANAGER  7839.0  1981-05-01  2850.0     0.0    30.0
4  7782.0   CLARK    MANAGER  7839.0  1981-06-09  2450.0     0.0    10.0
5  7839.0    KING  PRESIDENT     0.0  1981-11-17  5000.0     0.0    10.0
6  7844.0  TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0    30.0
7  7900.0   JAMES      CLERK  7698.0  1981-12-03   950.0     0.0    30.0
8  7934.0  MILLER      CLERK  7782.0  1982-01-23  1300.0     0.0    10.0

In [99]:
dept_df
query_15 = """
    select deptno from dept
    where loc in ('NEW YORK','CHICAGO')
"""
sql(query_15)

접속된 서버가 존재함

   deptno
0    10.0
1    30.0

In [ ]:
query_16 = """
    select * from emp
    where deptno in
    (
    select deptno from dept
    where loc in ('NEW YORK','CHICAGO')
    )
"""
sql(query_16)

접속된 서버가 존재함

    EMPNO   ENAME        JOB     MGR    HIREDATE     SAL    COMM  DEPTNO
0  7499.0   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0    30.0
1  7521.0    WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0    30.0
2  7654.0  MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0    30.0
3  7698.0   BLAKE    MANAGER  7839.0  1981-05-01  2850.0     0.0    30.0
4  7782.0   CLARK    MANAGER  7839.0  1981-06-09  2450.0     0.0    10.0
5  7839.0    KING  PRESIDENT     0.0  1981-11-17  5000.0     0.0    10.0
6  7844.0  TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0    30.0
7  7900.0   JAMES      CLERK  7698.0  1981-12-03   950.0     0.0    30.0
8  7934.0  MILLER      CLERK  7782.0  1982-01-23  1300.0     0.0    10.0

In [102]:
dept_df

   DEPTNO       DNAME       LOC
0    10.0  ACCOUNTING  NEW YORK
1    20.0    RESEARCH    DALLAS
2    30.0       SALES   CHICAGO
3    40.0  OPERATIONS    BOSTON

In [104]:
# 부서 정보에서 loc 컬럼이 뉴욕, 시카고인 부서의 번호를 추출
flag = dept_df.loc[
    dept_df['LOC'].isin(['NEW YORK','CHICAGO']),
    'DEPTNO'
]

In [107]:
emp_df.loc[emp_df['DEPTNO'].isin(flag), ]

     EMPNO   ENAME        JOB     MGR    HIREDATE     SAL    COMM  DEPTNO
1   7499.0   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0    30.0
2   7521.0    WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0    30.0
4   7654.0  MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0    30.0
5   7698.0   BLAKE    MANAGER  7839.0  1981-05-01  2850.0     0.0    30.0
6   7782.0   CLARK    MANAGER  7839.0  1981-06-09  2450.0     0.0    10.0
8   7839.0    KING  PRESIDENT     0.0  1981-11-17  5000.0     0.0    10.0
9   7844.0  TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0    30.0
11  7900.0   JAMES      CLERK  7698.0  1981-12-03   950.0     0.0    30.0
13  7934.0  MILLER      CLERK  7782.0  1982-01-23  1300.0     0.0    10.0

In [ ]:
# where(인덱스의 조건 - 필터), group by(그룹화), having(인덱스의 조건 - 필터), order by(정렬)
# 1. where(그룹화를 하기 전에 데이터를 필터)
# 2. group by(그룹화)
# 3. having(그룹화된 데이터에서 필터)
# 4. order by(최종 결과를 이용하여 정렬을 변경)
# 직종에서 ANALYST을 제외하고 직종별로 그룹화하여 SAL의 평균을 구한 뒤,
# 평균의 값이 2500이상인 데이터에서 평균 sal이 높을 순서대로 출력

query_17 = """
    select job, avg(sal) as mean from emp
    where job != 'ANALYST'
    group by job
    having mean >= 2500
    order by mean desc
"""
sql(query_17)

접속된 서버가 존재함

         job         mean
0  PRESIDENT  5000.000000
1    MANAGER  2758.333333

In [113]:
emp_df

     EMPNO   ENAME        JOB     MGR    HIREDATE     SAL    COMM  DEPTNO
0   7369.0   SMITH      CLERK  7902.0  1980-12-17   800.0     0.0    20.0
1   7499.0   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0    30.0
2   7521.0    WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0    30.0
3   7566.0   JONES    MANAGER  7839.0  1981-04-02  2975.0     0.0    20.0
4   7654.0  MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0    30.0
5   7698.0   BLAKE    MANAGER  7839.0  1981-05-01  2850.0     0.0    30.0
6   7782.0   CLARK    MANAGER  7839.0  1981-06-09  2450.0     0.0    10.0
7   7788.0   SCOTT    ANALYST  7566.0  1987-06-28  3000.0     0.0    20.0
8   7839.0    KING  PRESIDENT     0.0  1981-11-17  5000.0     0.0    10.0
9   7844.0  TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0    30.0
10  7876.0   ADAMS      CLERK  7788.0  1987-07-13  1100.0     0.0    20.0
11  7900.0   JAMES      CLERK  7698.0  1981-12-03   950.0     0.0    30.0
12  7902.0    FORD    ANALYST  7566.0  1981-12-03  3000.0     0.0    20.0
13  7934.0  MILLER      CLERK  7782.0  1982-01-23  1300.0     0.0    10.0

In [117]:
df = emp_df.loc[
    emp_df['JOB'] != 'ANALYST'
]
df

     EMPNO   ENAME        JOB     MGR    HIREDATE     SAL    COMM  DEPTNO
0   7369.0   SMITH      CLERK  7902.0  1980-12-17   800.0     0.0    20.0
1   7499.0   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0    30.0
2   7521.0    WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0    30.0
3   7566.0   JONES    MANAGER  7839.0  1981-04-02  2975.0     0.0    20.0
4   7654.0  MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0    30.0
5   7698.0   BLAKE    MANAGER  7839.0  1981-05-01  2850.0     0.0    30.0
6   7782.0   CLARK    MANAGER  7839.0  1981-06-09  2450.0     0.0    10.0
8   7839.0    KING  PRESIDENT     0.0  1981-11-17  5000.0     0.0    10.0
9   7844.0  TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0    30.0
10  7876.0   ADAMS      CLERK  7788.0  1987-07-13  1100.0     0.0    20.0
11  7900.0   JAMES      CLERK  7698.0  1981-12-03   950.0     0.0    30.0
13  7934.0  MILLER      CLERK  7782.0  1982-01-23  1300.0     0.0    10.0

In [118]:
group_df = df[['JOB','SAL']].groupby('JOB').mean()
group_df

                   SAL
JOB
CLERK      1037.500000
MANAGER    2758.333333
PRESIDENT  5000.000000
SALESMAN   1400.000000

In [120]:
group_df = group_df.loc[
    group_df['SAL'] >= 2500
]
group_df

                   SAL
JOB
MANAGER    2758.333333
PRESIDENT  5000.000000

In [122]:
group_df.sort_values('SAL',ascending=False).reset_index()

         JOB          SAL
0  PRESIDENT  5000.000000
1    MANAGER  2758.333333