In [1]:
import pandas as pd

In [ ]:
# csv 폴더 안에 있는 corona.csv 파일 로드
# 현재 작업중인 폴더(./)(생략이 가능) -> 상위 폴더로 이동(../) -> csv 하위 폴더로 이동(csv/) -> corona.csv
# 상대 경로는 내 파일의 위치에서부터 시작
corona = pd.read_csv('../csv/corona.csv')

In [3]:
# 데이터의 확인 : head(), tail()
corona.head()

,Unnamed: 0,createDt,deathCnt,decideCnt,seq,stateDt,stateTime,updateDt,accExamCnt,accDefRate
0,0,2022-06-08 09:09:05.982,24305,18188200,904,20220608,00:00,NaN,NaN,NaN
1,1,2022-06-07 09:09:00.897,24299,18174842,903,20220607,00:00,2022-06-08 09:10:36.846,NaN,NaN
2,2,2022-06-06 09:00:06.734,24279,18168670,902,20220606,00:00,2022-06-08 09:10:50.441,NaN,NaN
3,3,2022-06-05 08:53:19.426,24258,18163648,901,20220605,00:00,2022-06-08 09:11:04.758,NaN,NaN
4,4,2022-06-04 08:56:49.219,24238,18153814,900,20220604,00:00,2022-06-08 09:11:26.303,NaN,NaN

In [4]:
corona.tail()

,Unnamed: 0,createDt,deathCnt,decideCnt,seq,stateDt,stateTime,updateDt,accExamCnt,accDefRate
815,815,2020-03-14 00:00:00.000,72,8086,55,20200314,00:00,2021-10-07 10:30:51.51,261335.0,3.318000
816,816,2020-03-13 00:00:00.000,67,7979,54,20200313,00:00,2021-10-07 10:30:51.51,248647.0,3.458499
817,817,2020-03-12 00:00:00.000,66,7869,53,20200312,00:00,2021-10-07 10:30:51.51,234998.0,3.621744
818,818,2020-03-11 00:00:00.000,60,7755,52,20200311,00:00,2021-10-07 10:30:51.51,222395.0,3.804175
819,819,2020-03-10 00:00:00.000,54,7513,51,20200310,00:00,2021-10-07 10:30:51.51,210144.0,3.919308

In [7]:
# 데이터프레임에서 컬럼들의 목록 확인
# DataFrame라는 Class에는 3개 변수 -> values, index, columns
corona.columns

Index(['Unnamed: 0', 'createDt', 'deathCnt', 'decideCnt', 'seq', 'stateDt',
       'stateTime', 'updateDt', 'accExamCnt', 'accDefRate'],
      dtype='object')

In [ ]:
# Unnamed : 0 컬럼은 인덱스로 사용이 되는구나 -> 필요 X -> 해당 컬럼의 데이터는 제거
# seq 컬럼의 데이터는 게시글의 번호 -> 제거
# 특정 데이터를 제거(drop())
# dropna() -> 매개변수 축 설정(axis) -> 인덱스를 제거할것인가? 컬럼을 제거할것인가?
#           -> 매개변수 inplace -> 원본의 데이터를 변화시킬 것인가?
#           -> 결측치를 제거한다
# drop() -> axis, inplace 매개변수 존재
#       -> 첫번째 인자는 어떠한 것을 제거할것인가?
#       -> drop() 함수에서 기본 설정은 인덱스를 제거
corona.drop(
    ['Unnamed: 0','seq'], axis = 1, inplace = True
)
# 우리가 제거할 컬럼의 개수가 2개
# drop(inplace = True)의 함수를 실행하면 -> 첫번째 실행에서 정상 처리가 되더라도
# -> 같은 블록을 다시 실행하면 에러 발생( 해당 데이터가 제거되고 다시 제거하려니 없다)

In [12]:
corona.head(1)

,createDt,deathCnt,decideCnt,stateDt,stateTime,updateDt,accExamCnt,accDefRate
0,2022-06-08 09:09:05.982,24305,18188200,20220608,00:00,NaN,NaN,NaN

In [13]:
# 컬럼의 이름을 변경
# case1 : rename() 함수를 이용하여 컬럼의 이름을 변경
# 특정 컬럼의 이름을 변경할때 사용
corona.rename(
    columns = {
        'createDt' : '등록일시',
        'deathCnt' : '총사망자',
        'decideCnt' : '총확진자',
        'stateDt' : '기준일',
        'stateTime' : '기준시간',
        'updateDt' : '수정일시',
        'accExamCnt' : '누적의심자',
        'accDefRate' : '누적확진율'
    }
)

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율
0,2022-06-08 09:09:05.982,24305,18188200,20220608,00:00,NaN,NaN,NaN
1,2022-06-07 09:09:00.897,24299,18174842,20220607,00:00,2022-06-08 09:10:36.846,NaN,NaN
2,2022-06-06 09:00:06.734,24279,18168670,20220606,00:00,2022-06-08 09:10:50.441,NaN,NaN
3,2022-06-05 08:53:19.426,24258,18163648,20220605,00:00,2022-06-08 09:11:04.758,NaN,NaN
4,2022-06-04 08:56:49.219,24238,18153814,20220604,00:00,2022-06-08 09:11:26.303,NaN,NaN
...,...,...,...,...,...,...,...,...
815,2020-03-14 00:00:00.000,72,8086,20200314,00:00,2021-10-07 10:30:51.51,261335.0,3.318000
816,2020-03-13 00:00:00.000,67,7979,20200313,00:00,2021-10-07 10:30:51.51,248647.0,3.458499
817,2020-03-12 00:00:00.000,66,7869,20200312,00:00,2021-10-07 10:30:51.51,234998.0,3.621744
818,2020-03-11 00:00:00.000,60,7755,20200311,00:00,2021-10-07 10:30:51.51,222395.0,3.804175
819,2020-03-10 00:00:00.000,54,7513,20200310,00:00,2021-10-07 10:30:51.51,210144.0,3.919308

In [ ]:
# case2 : Class 내부의 columns 변수에 접근해서 다른 데이터를 대입
# ( 데이터를 변경하기 전에 확인은 불가능 )
# -> 이 방법은 모든 컬럼의 이름을 변경할때 주로 사용
# 주의사항 : 컬럼의 개수가 같은 자료형 데이터를 대입 (길이가 다르면 에러 발생)
corona.columns = ['등록일시', '총사망자', '총확진자', '기준일',
                '기준시간', '수정일시', '누적의심자', '누적확진율']

In [15]:
corona.head(1)corona.head(1)

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율
0,2022-06-08 09:09:05.982,24305,18188200,20220608,00:00,NaN,NaN,NaN

In [16]:
corona.head(10)

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율
0,2022-06-08 09:09:05.982,24305,18188200,20220608,00:00,NaN,NaN,NaN
1,2022-06-07 09:09:00.897,24299,18174842,20220607,00:00,2022-06-08 09:10:36.846,NaN,NaN
2,2022-06-06 09:00:06.734,24279,18168670,20220606,00:00,2022-06-08 09:10:50.441,NaN,NaN
3,2022-06-05 08:53:19.426,24258,18163648,20220605,00:00,2022-06-08 09:11:04.758,NaN,NaN
4,2022-06-04 08:56:49.219,24238,18153814,20220604,00:00,2022-06-08 09:11:26.303,NaN,NaN
5,2022-06-03 09:08:18.729,24229,18141775,20220603,00:00,2022-06-08 09:11:38.938,NaN,NaN
6,2022-06-02 08:58:19.746,24212,18129236,20220602,00:00,2022-06-08 09:11:51.985,NaN,NaN
7,2022-06-01 09:07:30.461,24197,18119345,20220601,00:00,2022-06-08 09:12:05.316,NaN,NaN
8,2022-05-31 08:55:39.977,24176,18103577,20220531,00:00,2022-06-04 08:59:23.637,NaN,NaN
9,2022-05-30 09:01:30.847,24167,18086392,20220530,00:00,2022-06-04 08:59:37.203,NaN,NaN

In [17]:
# 데이터를 확인하는 방법 : info(), isna().sum(), describe()
corona.info()

# 인덱스는 일반적으로 범위형태로 구성
# range(1,100)
# 시간 데이터(시계열 데이터)
# 일반적으로 인덱스는 고유값(primary key)
# 고유값을 사용하는 이유는? -> 전체의 데이터에서 특정 데이터를 찾기 편하기 위함
# 개인 정보의 데이터 -> 이름, 생년월일, 주소 ( 3개의 데이터는 고유값을 가질 수가 없다. )
# -> 고유 값 컬럼을 생성
# ( 숫자가 1씩 증가하는 형태(auto increment), 주민등록번호, ID )
# -> 하나의 행, 열에 접근하기 편하기 위해서

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 820 entries, 0 to 819
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   등록일시    820 non-null    object
 1   총사망자    820 non-null    int64
 2   총확진자    820 non-null    int64
 3   기준일     820 non-null    int64
 4   기준시간    820 non-null    object
 5   수정일시    817 non-null    object
 6   누적의심자   692 non-null    float64
 7   누적확진율   623 non-null    float64
dtypes: float64(2), int64(3), object(3)
memory usage: 51.4+ KB

In [18]:
# 결측치의 개수를 확인 -> 결측치가 맞느냐(isna()) -> 합산(sum())
# F -> 0, T -> 1 --> 합산을 하면 True의 개수(결측치 개수)
corona.isna().sum()

등록일시       0
총사망자       0
총확진자       0
기준일        0
기준시간       0
수정일시       3
누적의심자    128
누적확진율    197
dtype: int64

In [20]:
# 통계 정보 확인 -> 일반적으로 수치형 데이터의 통계 정보
corona.describe()

               총사망자          총확진자           기준일         누적의심자       누적확진율
count    820.000000  8.200000e+02  8.200000e+02  6.920000e+02  623.000000
mean    3927.832927  1.913097e+06  2.020897e+07  7.545057e+06    1.556435
std     6164.310693  4.857030e+06  7.118265e+03  6.172020e+06    0.543014
min       54.000000  7.513000e+03  2.020031e+07  2.101440e+05    0.902205
25%      415.750000  2.393525e+04  2.020100e+07  1.934309e+06    1.078089
50%     1812.500000  1.185640e+05  2.021042e+07  6.368310e+06    1.416159
75%     3120.500000  3.979915e+05  2.021112e+07  1.216890e+07    1.816009
max    24305.000000  1.818820e+07  2.022061e+07  2.151807e+07    3.919308

In [23]:
# 문자형 데이터의 통계 정보 ? ( 데이터의 개수, 고유값의 개수, 0번 인덱스의 데이터, 최빈값)
corona[[ '등록일시','기준시간']].describe()

                           등록일시   기준시간
count                       820    820
unique                      820      1
top     2022-06-08 09:09:05.982  00:00
freq                          1    820

In [26]:
# 데이터프레임에서 정렬을 변경
# list에서 정렬을 변경하는 함수 -> sort()
# (기본적으로는 오름차순, reverse 매개변수를 True로 변경하면 내림차순)
# 데이터프레임은 정렬을 변경할 수 있는 방법 2개 -> index, values(기준이 될 수 있는 값을 여러개)
# 데이터프레임은 sort()함수가 2개 존재 -> sort_index(), sort_values()
# 코로나 데이터에서 등록일시를 기준으로 정렬을 오름차순 정렬로 변경
# sort_values() : 특정 컬럼의 값들을 기준으로 정렬을 오름차순(기본값) / 내림차순
# 오름차순 / 내림차순 : ascending 매개변수를 False로 변경하면 내림차순
corona.sort_values('등록일시', ascending=True, inplace = True)

In [27]:
corona.head(3)

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율
819,2020-03-10 00:00:00.000,54,7513,20200310,00:00,2021-10-07 10:30:51.51,210144.0,3.919308
818,2020-03-11 00:00:00.000,60,7755,20200311,00:00,2021-10-07 10:30:51.51,222395.0,3.804175
817,2020-03-12 00:00:00.000,66,7869,20200312,00:00,2021-10-07 10:30:51.51,234998.0,3.621744

In [30]:
# 인덱스가 역순으로 되어있는게 좀 걸린다
# 인덱스를 재지정(초기화)
# 초기화(reset) + 인덱스(index)
# 인덱스는 초기화 -> 기존의 인덱스는 index라는 컬럼을 생성하여 데이터를 유지
# 기존의 인덱스를 제거하려면 ? -> reset_index().drop('index',axis = 1) //
# -> reset_index() 함수 안에 drop 매개변수 존재
# (기본값은 False, True로 변경하면 기존의 인덱스는 제거)
corona.reset_index(drop=True,inplace = True)

In [31]:
# 1차 작업이 종료 -> 백업본 하나 생성
origin_data = corona.copy()

In [34]:
# 결측치가 존재하는 컬림이 3개 (수정일시, 누적의심자, 누적확진율)
# 수정일시가 결측치인 데이터를 확인( 수정일시가 결측치인 이유는? -> 수정이 되지 않았다 ? )
# 수정일시가 결측치인(인덱스의 조건식) 데이터를 출력( 전체 데이터에서 특정 데이터들만 확인)
# 데이터프레임에서 수정일시 데이터만 추출 -> 결측치와 같은가?
flag_null = corona['수정일시'].isna()

In [36]:
corona.loc[flag_null,]

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율
640,2021-12-11 06:19:00.000,4210,510578,20211211,00:00,NaN,18024403.0,NaN
700,2022-02-09 10:37:00.08,6943,1131239,20220209,00:00,NaN,NaN,NaN
819,2022-06-08 09:09:05.982,24305,18188200,20220608,00:00,NaN,NaN,NaN

In [37]:
# 640d인덱스를 기준으로 상위 2부터 하위 2개까지의 데이터를 출력
# loc[] ->범위 지정이면 종료값 포함
corona.loc[638:642, ]

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율
638,2021-12-09 09:05:11.285,4077,496853,20211209,00:00,2021-12-17 09:07:54.162,17870821.0,NaN
639,2021-12-10 09:04:53.786,4130,503601,20211210,00:00,2021-12-17 09:08:03.447,17950721.0,NaN
640,2021-12-11 06:19:00.000,4210,510578,20211211,00:00,NaN,18024403.0,NaN
641,2021-12-12 08:35:19.089,4252,517259,20211212,00:00,2021-12-20 09:03:46.785,18084589.0,NaN
642,2021-12-13 09:00:10.891,4292,523075,20211213,00:00,2021-12-22 09:19:51.783,18140572.0,NaN

In [40]:
# 누적의심자, 누적확진율
# 결측치가 왜 생겼을까? --> 코로나의 감염자가 재감염이 되는 경우가 발생(많은 수가 발생)
# -> 2개의 컬럼의 데이터의 신뢰도가 떨어져서 데이터를 더 이상 입력하지 않았다. 추측
flag_null2 = corona['누적확진율'].isna()

In [42]:
corona.loc[flag_null2,]

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율
623,2021-11-24 09:08:22.071,3362,425059,20211124,00:00,2021-12-02 09:06:01.826,16939923.0,NaN
624,2021-11-25 09:00:47.897,3401,428996,20211125,00:00,2021-12-02 09:06:12.94,16998733.0,NaN
625,2021-11-26 09:03:03.973,3440,432892,20211126,00:00,2021-12-02 09:06:24.138,17056003.0,NaN
626,2021-11-27 09:32:36.026,3492,436959,20211127,00:00,2021-12-02 09:06:37.327,17115754.0,NaN
627,2021-11-28 08:58:53.394,3548,440884,20211128,00:00,2021-12-02 09:06:50.152,17158535.0,NaN
...,...,...,...,...,...,...,...,...
815,2022-06-04 08:56:49.219,24238,18153814,20220604,00:00,2022-06-08 09:11:26.303,NaN,NaN
816,2022-06-05 08:53:19.426,24258,18163648,20220605,00:00,2022-06-08 09:11:04.758,NaN,NaN
817,2022-06-06 09:00:06.734,24279,18168670,20220606,00:00,2022-06-08 09:10:50.441,NaN,NaN
818,2022-06-07 09:09:00.897,24299,18174842,20220607,00:00,2022-06-08 09:10:36.846,NaN,NaN
819,2022-06-08 09:09:05.982,24305,18188200,20220608,00:00,NaN,NaN,NaN

In [43]:
flag_null3 = corona['누적의심자'].isna()

corona.loc[flag_null3,]

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율
692,2022-02-01 09:06:24.411,6772,864026,20220201,00:00,2022-02-09 13:04:21.424,NaN,NaN
693,2022-02-02 09:04:49.92,6787,884294,20220202,00:00,2022-02-09 13:04:29.013,NaN,NaN
694,2022-02-03 08:46:14.856,6812,907200,20220203,00:00,2022-02-09 13:04:42.741,NaN,NaN
695,2022-02-04 08:58:40.476,6836,934638,20220204,00:00,2022-02-09 13:04:52.382,NaN,NaN
696,2022-02-05 10:25:08.782,6858,970983,20220205,00:00,2022-02-09 13:05:01.221,NaN,NaN
...,...,...,...,...,...,...,...,...
815,2022-06-04 08:56:49.219,24238,18153814,20220604,00:00,2022-06-08 09:11:26.303,NaN,NaN
816,2022-06-05 08:53:19.426,24258,18163648,20220605,00:00,2022-06-08 09:11:04.758,NaN,NaN
817,2022-06-06 09:00:06.734,24279,18168670,20220606,00:00,2022-06-08 09:10:50.441,NaN,NaN
818,2022-06-07 09:09:00.897,24299,18174842,20220607,00:00,2022-06-08 09:10:36.846,NaN,NaN
819,2022-06-08 09:09:05.982,24305,18188200,20220608,00:00,NaN,NaN,NaN

In [47]:
# 2개의 컬럼의 데이터는 특정 날짜 이후로는 데이터를 수집하지 않았다.
# 데이터의 필요성 없어졌다 -> 컬럼의 데이터를 제거해도 되겠다
corona.drop(
    ['누적의심자','누적확진율'],axis = 1,inplace = True
)

In [ ]:
# 데이터셋에서 우리가 필요한 데이터가 존재하지 않는다면 -> 데이터를 생성
# 일일확진자 -> 어제의 총확진자와 오늘의 총확진자의 수의 차이
# 파생변수를 생성 -> 컬럼이 하나 추가
# 일일확진자 = 오늘의 총확진자 - 어제의 총확진자
corona.loc[1,'총확진자'] - corona.loc[0,'총확진자']
corona.loc[2,'총확진자'] - corona.loc[1,'총확진자']
corona.loc[3,'총확진자'] - corona.loc[2,'총확진자']

corona.loc[819,'총확진자'] - corona.loc[818,'총확진자']
# .... 819번 실행 -> 첫날짜는 일일확진자를 계산 불가능(첫날의 데이터는 0으로 지정)

110

In [52]:
new_list = []

# 819번 반복을 하는 반복문
for i in range(819):
    # i는 0부터 818까지 대입
    result = corona.loc[i+1,'총확진자'] - corona.loc[i,'총확진자']
    # 계산 결과를 new_list에 추가
    new_list.append(result)

new_list

[242,
 114,
 110,
 107,
 76,
 74,
 84,
 93,
 152,
 87,
 147,
 98,
 64,
 76,
 100,
 104,
 91,
 146,
 105,
 78,
 125,
 101,
 89,
 86,
 94,
 81,
 47,
 47,
 53,
 39,
 27,
 30,
 32,
 25,
 27,
 27,
 22,
 22,
 18,
 8,
 13,
 9,
 11,
 8,
 6,
 10,
 10,
 10,
 14,
 9,
 4,
 9,
 6,
 13,
 8,
 3,
 2,
 4,
 12,
 18,
 34,
 35,
 27,
 26,
 56,
 19,
 13,
 15,
 13,
 32,
 12,
 20,
 23,
 25,
 16,
 19,
 40,
 79,
 58,
 39,
 27,
 35,
 38,
 49,
 39,
 39,
 51,
 57,
 37,
 38,
 50,
 45,
 56,
 48,
 34,
 37,
 34,
 43,
 59,
 49,
 67,
 48,
 17,
 46,
 51,
 28,
 39,
 51,
 62,
 42,
 42,
 51,
 54,
 61,
 63,
 61,
 48,
 44,
 62,
 50,
 45,
 35,
 44,
 62,
 33,
 39,
 61,
 60,
 39,
 34,
 26,
 45,
 63,
 59,
 41,
 113,
 58,
 25,
 28,
 48,
 18,
 36,
 31,
 30,
 23,
 34,
 33,
 43,
 20,
 43,
 36,
 28,
 34,
 54,
 56,
 103,
 166,
 279,
 197,
 246,
 297,
 288,
 324,
 332,
 396,
 266,
 280,
 320,
 441,
 371,
 323,
 299,
 248,
 235,
 267,
 195,
 198,
 168,
 167,
 119,
 136,
 156,
 155,
 176,
 136,
 121,
 109,
 106,
 113,
 153,
 126,
 110,
 82,
 70,
 61,
 110,
 125,
 114,
 61,
 95,
 50,
 38,
 113,
 77,
 63,
 75,
 64,
 73,
 75,
 114,
 69,
 54,
 72,
 58,
 98,
 91,
 84,
 110,
 47,
 73,
 91,
 76,
 58,
 89,
 121,
 155,
 77,
 61,
 119,
 88,
 103,
 125,
 113,
 127,
 124,
 97,
 75,
 117,
 125,
 145,
 89,
 143,
 126,
 100,
 145,
 143,
 191,
 205,
 208,
 222,
 230,
 285,
 325,
 348,
 386,
 330,
 271,
 349,
 382,
 581,
 555,
 503,
 450,
 438,
 451,
 511,
 540,
 628,
 577,
 631,
 615,
 587,
 670,
 680,
 689,
 950,
 1030,
 718,
 880,
 1078,
 1014,
 1064,
 1045,
 1096,
 924,
 866,
 1090,
 985,
 1240,
 1131,
 970,
 806,
 1044,
 1050,
 967,
 1027,
 820,
 657,
 1020,
 714,
 838,
 869,
 674,
 641,
 657,
 451,
 537,
 561,
 524,
 512,
 580,
 520,
 389,
 386,
 404,
 400,
 346,
 431,
 392,
 437,
 349,
 559,
 497,
 469,
 456,
 354,
 305,
 336,
 467,
 451,
 370,
 390,
 371,
 288,
 303,
 444,
 504,
 403,
 362,
 326,
 343,
 457,
 621,
 621,
 561,
 448,
 416,
 332,
 356,
 440,
 395,
 387,
 415,
 355,
 355,
 344,
 444,
 424,
 398,
 418,
 416,
 346,
 446,
 470,
 465,
 488,
 490,
 459,
 379,
 363,
 469,
 445,
 463,
 447,
 456,
 415,
 346,
 428,
 430,
 489,
 505,
 482,
 382,
 447,
 506,
 551,
 557,
 543,
 543,
 473,
 477,
 668,
 700,
 671,
 677,
 614,
 587,
 542,
 731,
 698,
 673,
 658,
 671,
 532,
 549,
 731,
 735,
 797,
 785,
 644,
 499,
 512,
 769,
 679,
 661,
 627,
 606,
 488,
 541,
 676,
 574,
 525,
 701,
 564,
 463,
 510,
 634,
 715,
 747,
 681,
 610,
 619,
 528,
 654,
 646,
 561,
 666,
 585,
 530,
 516,
 705,
 629,
 587,
 533,
 910,
 -430,
 889,
 677,
 681,
 695,
 744,
 556,
 485,
 454,
 602,
 610,
 556,
 565,
 452,
 399,
 373,
 545,
 540,
 507,
 482,
 429,
 357,
 394,
 645,
 610,
 634,
 668,
 614,
 501,
 595,
 794,
 761,
 825,
 794,
 743,
 711,
 746,
 1211,
 1275,
 1316,
 1378,
 1324,
 1100,
 1150,
 1613,
 1599,
 1535,
 1449,
 1453,
 1251,
 1278,
 1781,
 1841,
 1629,
 1627,
 1487,
 1318,
 1363,
 1895,
 1673,
 1710,
 1538,
 1442,
 1218,
 1200,
 1725,
 1775,
 1704,
 1823,
 1727,
 1491,
 1537,
 2221,
 1987,
 1989,
 1928,
 1816,
 1554,
 1372,
 1803,
 2152,
 2140,
 1787,
 1626,
 1417,
 1507,
 2154,
 1882,
 1837,
 1791,
 1619,
 1485,
 1370,
 2024,
 1960,
 1708,
 1803,
 1490,
 1375,
 1597,
 2047,
 2049,
 1893,
 1864,
 1755,
 1433,
 1508,
 2065,
 1942,
 2008,
 2087,
 1909,
 1604,
 1729,
 1720,
 1715,
 2429,
 3270,
 2768,
 2381,
 2288,
 2881,
 2561,
 2484,
 2247,
 2085,
 1670,
 1574,
 2027,
 2425,
 2171,
 1953,
 1594,
 1297,
 1346,
 1583,
 1939,
 1683,
 1617,
 1420,
 1050,
 1073,
 1571,
 1441,
 1438,
 1508,
 1421,
 1190,
 1272,
 1945,
 2111,
 2121,
 2104,
 2061,
 1685,
 1588,
 2667,
 2482,
 2343,
 2246,
 2225,
 1754,
 1717,
 2425,
 2518,
 2368,
 2324,
 2418,
 2004,
 2122,
 3189,
 3292,
 3033,
 3205,
 3120,
 2827,
 2697,
 4113,
 3937,
 3896,
 4067,
 3925,
 3307,
 3031,
 5122,
 5263,
 4944,
 5352,
 5125,
 4324,
 4953,
 7173,
 7375,
 6748,
 6977,
 6681,
 5816,
 5567,
 7849,
 7619,
 7434,
 7310,
 6233,
 5316,
 5192,
 7452,
 6914,
 6233,
 5840,
 5413,
 4203,
 3864,
 5407,
 5034,
 4873,
 4415,
 3831,
 3125,
 3021,
 4441,
 4122,
 3713,
 3507,
 3371,
 3005,
 3092,
 4383,
 4164,
 4538,
 4419,
 4189,
 3854,
 4062,
 5803,
 6600,
 6766,
 7004,
 7626,
 7511,
 8570,
 13009,
 14514,
 16093,
 17513,
 17522,
 17077,
 18338,
 20268,
 22906,
 27438,
 36345,
 38689,
 35283,
 36717,
 49567,
 54122,
 53903,
 54935,
 56428,
 54617,
 57164,
 90435,
 93132,
 109823,
 102210,
 104814,
 95339,
 99569,
 171442,
 170015,
 165887,
 166182,
 163561,
 139624,
 138990,
 219228,
 198800,
 266850,
 254327,
 243625,
 210709,
 202702,
 342429,
 327538,
 282973,
 383617,
 350182,
 309779,
 362283,
 400593,
 621204,
 406839,
 381413,
 334653,
 209139,
 353828,
 490771,
 395526,
 339451,
 335541,
 318075,
 187182,
 347500,
 424466,
 320683,
 280231,
 264120,
 234265,
 127163,
 266085,
 286247,
 224784,
 205299,
 185525,
 164456,
 90917,
 210715,
 195382,
 148409,
 125800,
 107882,
 92978,
 47730,
 118462,
 111289,
 90843,
 81033,
 75423,
 64704,
 34361,
 80267,
 76764,
 57446,
 50556,
 43244,
 37760,
 20076,
 51106,
 49046,
 42279,
 26678,
 39563,
 40048,
 20588,
 49896,
 43881,
 35882,
 32435,
 29572,
 25425,
 13290,
 35085,
 31333,
 28109,
 25113,
 23450,
 19289,
 9971,
 26331,
 23936,
 18805,
 16572,
 14374,
 12647,
 6135,
 17185,
 15768,
 9891,
 12539,
 12039,
 9834,
 5022,
 6172,
 13358]

In [53]:
new_list2 = []

for i in range(1,820,1):
    result = corona.loc[i,'총확진자'] - corona.loc[i-1,'총확진자']
    new_list2.append(result)
len(new_list2)

819

In [ ]:
# 819번 반복하면서 일일확진자의 데이터는 819개 -> 첫 번째 데이터는 일일확진자를 구할 수 없기 때문
# 첫 날의 데이터는 0으로 생성
# 만들어진 리스트에 0을 첫번째 데이터로 대입 -> list.insert(0, 0)
# 리스트 + 리스트 -> 연결 [0] + new_list
# 반복 실행하기 전 new_list를 빈 리스트가 아니라 [0] 대입한 뒤 append()
# case1
[0] + new_list

[0,
 242,
 114,
 110,
 107,
 76,
 74,
 84,
 93,
 152,
 87,
 147,
 98,
 64,
 76,
 100,
 104,
 91,
 146,
 105,
 78,
 125,
 101,
 89,
 86,
 94,
 81,
 47,
 47,
 53,
 39,
 27,
 30,
 32,
 25,
 27,
 27,
 22,
 22,
 18,
 8,
 13,
 9,
 11,
 8,
 6,
 10,
 10,
 10,
 14,
 9,
 4,
 9,
 6,
 13,
 8,
 3,
 2,
 4,
 12,
 18,
 34,
 35,
 27,
 26,
 56,
 19,
 13,
 15,
 13,
 32,
 12,
 20,
 23,
 25,
 16,
 19,
 40,
 79,
 58,
 39,
 27,
 35,
 38,
 49,
 39,
 39,
 51,
 57,
 37,
 38,
 50,
 45,
 56,
 48,
 34,
 37,
 34,
 43,
 59,
 49,
 67,
 48,
 17,
 46,
 51,
 28,
 39,
 51,
 62,
 42,
 42,
 51,
 54,
 61,
 63,
 61,
 48,
 44,
 62,
 50,
 45,
 35,
 44,
 62,
 33,
 39,
 61,
 60,
 39,
 34,
 26,
 45,
 63,
 59,
 41,
 113,
 58,
 25,
 28,
 48,
 18,
 36,
 31,
 30,
 23,
 34,
 33,
 43,
 20,
 43,
 36,
 28,
 34,
 54,
 56,
 103,
 166,
 279,
 197,
 246,
 297,
 288,
 324,
 332,
 396,
 266,
 280,
 320,
 441,
 371,
 323,
 299,
 248,
 235,
 267,
 195,
 198,
 168,
 167,
 119,
 136,
 156,
 155,
 176,
 136,
 121,
 109,
 106,
 113,
 153,
 126,
 110,
 82,
 70,
 61,
 110,
 125,
 114,
 61,
 95,
 50,
 38,
 113,
 77,
 63,
 75,
 64,
 73,
 75,
 114,
 69,
 54,
 72,
 58,
 98,
 91,
 84,
 110,
 47,
 73,
 91,
 76,
 58,
 89,
 121,
 155,
 77,
 61,
 119,
 88,
 103,
 125,
 113,
 127,
 124,
 97,
 75,
 117,
 125,
 145,
 89,
 143,
 126,
 100,
 145,
 143,
 191,
 205,
 208,
 222,
 230,
 285,
 325,
 348,
 386,
 330,
 271,
 349,
 382,
 581,
 555,
 503,
 450,
 438,
 451,
 511,
 540,
 628,
 577,
 631,
 615,
 587,
 670,
 680,
 689,
 950,
 1030,
 718,
 880,
 1078,
 1014,
 1064,
 1045,
 1096,
 924,
 866,
 1090,
 985,
 1240,
 1131,
 970,
 806,
 1044,
 1050,
 967,
 1027,
 820,
 657,
 1020,
 714,
 838,
 869,
 674,
 641,
 657,
 451,
 537,
 561,
 524,
 512,
 580,
 520,
 389,
 386,
 404,
 400,
 346,
 431,
 392,
 437,
 349,
 559,
 497,
 469,
 456,
 354,
 305,
 336,
 467,
 451,
 370,
 390,
 371,
 288,
 303,
 444,
 504,
 403,
 362,
 326,
 343,
 457,
 621,
 621,
 561,
 448,
 416,
 332,
 356,
 440,
 395,
 387,
 415,
 355,
 355,
 344,
 444,
 424,
 398,
 418,
 416,
 346,
 446,
 470,
 465,
 488,
 490,
 459,
 379,
 363,
 469,
 445,
 463,
 447,
 456,
 415,
 346,
 428,
 430,
 489,
 505,
 482,
 382,
 447,
 506,
 551,
 557,
 543,
 543,
 473,
 477,
 668,
 700,
 671,
 677,
 614,
 587,
 542,
 731,
 698,
 673,
 658,
 671,
 532,
 549,
 731,
 735,
 797,
 785,
 644,
 499,
 512,
 769,
 679,
 661,
 627,
 606,
 488,
 541,
 676,
 574,
 525,
 701,
 564,
 463,
 510,
 634,
 715,
 747,
 681,
 610,
 619,
 528,
 654,
 646,
 561,
 666,
 585,
 530,
 516,
 705,
 629,
 587,
 533,
 910,
 -430,
 889,
 677,
 681,
 695,
 744,
 556,
 485,
 454,
 602,
 610,
 556,
 565,
 452,
 399,
 373,
 545,
 540,
 507,
 482,
 429,
 357,
 394,
 645,
 610,
 634,
 668,
 614,
 501,
 595,
 794,
 761,
 825,
 794,
 743,
 711,
 746,
 1211,
 1275,
 1316,
 1378,
 1324,
 1100,
 1150,
 1613,
 1599,
 1535,
 1449,
 1453,
 1251,
 1278,
 1781,
 1841,
 1629,
 1627,
 1487,
 1318,
 1363,
 1895,
 1673,
 1710,
 1538,
 1442,
 1218,
 1200,
 1725,
 1775,
 1704,
 1823,
 1727,
 1491,
 1537,
 2221,
 1987,
 1989,
 1928,
 1816,
 1554,
 1372,
 1803,
 2152,
 2140,
 1787,
 1626,
 1417,
 1507,
 2154,
 1882,
 1837,
 1791,
 1619,
 1485,
 1370,
 2024,
 1960,
 1708,
 1803,
 1490,
 1375,
 1597,
 2047,
 2049,
 1893,
 1864,
 1755,
 1433,
 1508,
 2065,
 1942,
 2008,
 2087,
 1909,
 1604,
 1729,
 1720,
 1715,
 2429,
 3270,
 2768,
 2381,
 2288,
 2881,
 2561,
 2484,
 2247,
 2085,
 1670,
 1574,
 2027,
 2425,
 2171,
 1953,
 1594,
 1297,
 1346,
 1583,
 1939,
 1683,
 1617,
 1420,
 1050,
 1073,
 1571,
 1441,
 1438,
 1508,
 1421,
 1190,
 1272,
 1945,
 2111,
 2121,
 2104,
 2061,
 1685,
 1588,
 2667,
 2482,
 2343,
 2246,
 2225,
 1754,
 1717,
 2425,
 2518,
 2368,
 2324,
 2418,
 2004,
 2122,
 3189,
 3292,
 3033,
 3205,
 3120,
 2827,
 2697,
 4113,
 3937,
 3896,
 4067,
 3925,
 3307,
 3031,
 5122,
 5263,
 4944,
 5352,
 5125,
 4324,
 4953,
 7173,
 7375,
 6748,
 6977,
 6681,
 5816,
 5567,
 7849,
 7619,
 7434,
 7310,
 6233,
 5316,
 5192,
 7452,
 6914,
 6233,
 5840,
 5413,
 4203,
 3864,
 5407,
 5034,
 4873,
 4415,
 3831,
 3125,
 3021,
 4441,
 4122,
 3713,
 3507,
 3371,
 3005,
 3092,
 4383,
 4164,
 4538,
 4419,
 4189,
 3854,
 4062,
 5803,
 6600,
 6766,
 7004,
 7626,
 7511,
 8570,
 13009,
 14514,
 16093,
 17513,
 17522,
 17077,
 18338,
 20268,
 22906,
 27438,
 36345,
 38689,
 35283,
 36717,
 49567,
 54122,
 53903,
 54935,
 56428,
 54617,
 57164,
 90435,
 93132,
 109823,
 102210,
 104814,
 95339,
 99569,
 171442,
 170015,
 165887,
 166182,
 163561,
 139624,
 138990,
 219228,
 198800,
 266850,
 254327,
 243625,
 210709,
 202702,
 342429,
 327538,
 282973,
 383617,
 350182,
 309779,
 362283,
 400593,
 621204,
 406839,
 381413,
 334653,
 209139,
 353828,
 490771,
 395526,
 339451,
 335541,
 318075,
 187182,
 347500,
 424466,
 320683,
 280231,
 264120,
 234265,
 127163,
 266085,
 286247,
 224784,
 205299,
 185525,
 164456,
 90917,
 210715,
 195382,
 148409,
 125800,
 107882,
 92978,
 47730,
 118462,
 111289,
 90843,
 81033,
 75423,
 64704,
 34361,
 80267,
 76764,
 57446,
 50556,
 43244,
 37760,
 20076,
 51106,
 49046,
 42279,
 26678,
 39563,
 40048,
 20588,
 49896,
 43881,
 35882,
 32435,
 29572,
 25425,
 13290,
 35085,
 31333,
 28109,
 25113,
 23450,
 19289,
 9971,
 26331,
 23936,
 18805,
 16572,
 14374,
 12647,
 6135,
 17185,
 15768,
 9891,
 12539,
 12039,
 9834,
 5022,
 6172,
 13358]

In [55]:
# case2 : insert()
new_list.insert(0,0)

In [56]:
new_list

[0,
 242,
 114,
 110,
 107,
 76,
 74,
 84,
 93,
 152,
 87,
 147,
 98,
 64,
 76,
 100,
 104,
 91,
 146,
 105,
 78,
 125,
 101,
 89,
 86,
 94,
 81,
 47,
 47,
 53,
 39,
 27,
 30,
 32,
 25,
 27,
 27,
 22,
 22,
 18,
 8,
 13,
 9,
 11,
 8,
 6,
 10,
 10,
 10,
 14,
 9,
 4,
 9,
 6,
 13,
 8,
 3,
 2,
 4,
 12,
 18,
 34,
 35,
 27,
 26,
 56,
 19,
 13,
 15,
 13,
 32,
 12,
 20,
 23,
 25,
 16,
 19,
 40,
 79,
 58,
 39,
 27,
 35,
 38,
 49,
 39,
 39,
 51,
 57,
 37,
 38,
 50,
 45,
 56,
 48,
 34,
 37,
 34,
 43,
 59,
 49,
 67,
 48,
 17,
 46,
 51,
 28,
 39,
 51,
 62,
 42,
 42,
 51,
 54,
 61,
 63,
 61,
 48,
 44,
 62,
 50,
 45,
 35,
 44,
 62,
 33,
 39,
 61,
 60,
 39,
 34,
 26,
 45,
 63,
 59,
 41,
 113,
 58,
 25,
 28,
 48,
 18,
 36,
 31,
 30,
 23,
 34,
 33,
 43,
 20,
 43,
 36,
 28,
 34,
 54,
 56,
 103,
 166,
 279,
 197,
 246,
 297,
 288,
 324,
 332,
 396,
 266,
 280,
 320,
 441,
 371,
 323,
 299,
 248,
 235,
 267,
 195,
 198,
 168,
 167,
 119,
 136,
 156,
 155,
 176,
 136,
 121,
 109,
 106,
 113,
 153,
 126,
 110,
 82,
 70,
 61,
 110,
 125,
 114,
 61,
 95,
 50,
 38,
 113,
 77,
 63,
 75,
 64,
 73,
 75,
 114,
 69,
 54,
 72,
 58,
 98,
 91,
 84,
 110,
 47,
 73,
 91,
 76,
 58,
 89,
 121,
 155,
 77,
 61,
 119,
 88,
 103,
 125,
 113,
 127,
 124,
 97,
 75,
 117,
 125,
 145,
 89,
 143,
 126,
 100,
 145,
 143,
 191,
 205,
 208,
 222,
 230,
 285,
 325,
 348,
 386,
 330,
 271,
 349,
 382,
 581,
 555,
 503,
 450,
 438,
 451,
 511,
 540,
 628,
 577,
 631,
 615,
 587,
 670,
 680,
 689,
 950,
 1030,
 718,
 880,
 1078,
 1014,
 1064,
 1045,
 1096,
 924,
 866,
 1090,
 985,
 1240,
 1131,
 970,
 806,
 1044,
 1050,
 967,
 1027,
 820,
 657,
 1020,
 714,
 838,
 869,
 674,
 641,
 657,
 451,
 537,
 561,
 524,
 512,
 580,
 520,
 389,
 386,
 404,
 400,
 346,
 431,
 392,
 437,
 349,
 559,
 497,
 469,
 456,
 354,
 305,
 336,
 467,
 451,
 370,
 390,
 371,
 288,
 303,
 444,
 504,
 403,
 362,
 326,
 343,
 457,
 621,
 621,
 561,
 448,
 416,
 332,
 356,
 440,
 395,
 387,
 415,
 355,
 355,
 344,
 444,
 424,
 398,
 418,
 416,
 346,
 446,
 470,
 465,
 488,
 490,
 459,
 379,
 363,
 469,
 445,
 463,
 447,
 456,
 415,
 346,
 428,
 430,
 489,
 505,
 482,
 382,
 447,
 506,
 551,
 557,
 543,
 543,
 473,
 477,
 668,
 700,
 671,
 677,
 614,
 587,
 542,
 731,
 698,
 673,
 658,
 671,
 532,
 549,
 731,
 735,
 797,
 785,
 644,
 499,
 512,
 769,
 679,
 661,
 627,
 606,
 488,
 541,
 676,
 574,
 525,
 701,
 564,
 463,
 510,
 634,
 715,
 747,
 681,
 610,
 619,
 528,
 654,
 646,
 561,
 666,
 585,
 530,
 516,
 705,
 629,
 587,
 533,
 910,
 -430,
 889,
 677,
 681,
 695,
 744,
 556,
 485,
 454,
 602,
 610,
 556,
 565,
 452,
 399,
 373,
 545,
 540,
 507,
 482,
 429,
 357,
 394,
 645,
 610,
 634,
 668,
 614,
 501,
 595,
 794,
 761,
 825,
 794,
 743,
 711,
 746,
 1211,
 1275,
 1316,
 1378,
 1324,
 1100,
 1150,
 1613,
 1599,
 1535,
 1449,
 1453,
 1251,
 1278,
 1781,
 1841,
 1629,
 1627,
 1487,
 1318,
 1363,
 1895,
 1673,
 1710,
 1538,
 1442,
 1218,
 1200,
 1725,
 1775,
 1704,
 1823,
 1727,
 1491,
 1537,
 2221,
 1987,
 1989,
 1928,
 1816,
 1554,
 1372,
 1803,
 2152,
 2140,
 1787,
 1626,
 1417,
 1507,
 2154,
 1882,
 1837,
 1791,
 1619,
 1485,
 1370,
 2024,
 1960,
 1708,
 1803,
 1490,
 1375,
 1597,
 2047,
 2049,
 1893,
 1864,
 1755,
 1433,
 1508,
 2065,
 1942,
 2008,
 2087,
 1909,
 1604,
 1729,
 1720,
 1715,
 2429,
 3270,
 2768,
 2381,
 2288,
 2881,
 2561,
 2484,
 2247,
 2085,
 1670,
 1574,
 2027,
 2425,
 2171,
 1953,
 1594,
 1297,
 1346,
 1583,
 1939,
 1683,
 1617,
 1420,
 1050,
 1073,
 1571,
 1441,
 1438,
 1508,
 1421,
 1190,
 1272,
 1945,
 2111,
 2121,
 2104,
 2061,
 1685,
 1588,
 2667,
 2482,
 2343,
 2246,
 2225,
 1754,
 1717,
 2425,
 2518,
 2368,
 2324,
 2418,
 2004,
 2122,
 3189,
 3292,
 3033,
 3205,
 3120,
 2827,
 2697,
 4113,
 3937,
 3896,
 4067,
 3925,
 3307,
 3031,
 5122,
 5263,
 4944,
 5352,
 5125,
 4324,
 4953,
 7173,
 7375,
 6748,
 6977,
 6681,
 5816,
 5567,
 7849,
 7619,
 7434,
 7310,
 6233,
 5316,
 5192,
 7452,
 6914,
 6233,
 5840,
 5413,
 4203,
 3864,
 5407,
 5034,
 4873,
 4415,
 3831,
 3125,
 3021,
 4441,
 4122,
 3713,
 3507,
 3371,
 3005,
 3092,
 4383,
 4164,
 4538,
 4419,
 4189,
 3854,
 4062,
 5803,
 6600,
 6766,
 7004,
 7626,
 7511,
 8570,
 13009,
 14514,
 16093,
 17513,
 17522,
 17077,
 18338,
 20268,
 22906,
 27438,
 36345,
 38689,
 35283,
 36717,
 49567,
 54122,
 53903,
 54935,
 56428,
 54617,
 57164,
 90435,
 93132,
 109823,
 102210,
 104814,
 95339,
 99569,
 171442,
 170015,
 165887,
 166182,
 163561,
 139624,
 138990,
 219228,
 198800,
 266850,
 254327,
 243625,
 210709,
 202702,
 342429,
 327538,
 282973,
 383617,
 350182,
 309779,
 362283,
 400593,
 621204,
 406839,
 381413,
 334653,
 209139,
 353828,
 490771,
 395526,
 339451,
 335541,
 318075,
 187182,
 347500,
 424466,
 320683,
 280231,
 264120,
 234265,
 127163,
 266085,
 286247,
 224784,
 205299,
 185525,
 164456,
 90917,
 210715,
 195382,
 148409,
 125800,
 107882,
 92978,
 47730,
 118462,
 111289,
 90843,
 81033,
 75423,
 64704,
 34361,
 80267,
 76764,
 57446,
 50556,
 43244,
 37760,
 20076,
 51106,
 49046,
 42279,
 26678,
 39563,
 40048,
 20588,
 49896,
 43881,
 35882,
 32435,
 29572,
 25425,
 13290,
 35085,
 31333,
 28109,
 25113,
 23450,
 19289,
 9971,
 26331,
 23936,
 18805,
 16572,
 14374,
 12647,
 6135,
 17185,
 15768,
 9891,
 12539,
 12039,
 9834,
 5022,
 6172,
 13358]

In [60]:
new_list2.insert(0,0)

In [61]:
# corona 데이터프레임에 new_list로 만들어준 일일확진자를 대입
# 데이터프레임은 dict와 비슷한 특성을 가지고 있다.
# 데이터프레임[new_col] = 1차원 데이터(Series, list, tuple) // 단일 데이터
# 1차원 데이터를 대입하는 경우는 데이터프레임의 인덱스와 길이가 같아야 한다.
# 단일 데이터를 대입하는 경우 -> 모든 값이 단일 데이터로 고정
corona['일일확진자'] = new_list2

In [62]:
corona.head()

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,test,일일확진자
0,2020-03-10 00:00:00.000,54,7513,20200310,00:00,2021-10-07 10:30:51.51,1,0
1,2020-03-11 00:00:00.000,60,7755,20200311,00:00,2021-10-07 10:30:51.51,1,242
2,2020-03-12 00:00:00.000,66,7869,20200312,00:00,2021-10-07 10:30:51.51,1,114
3,2020-03-13 00:00:00.000,67,7979,20200313,00:00,2021-10-07 10:30:51.51,1,110
4,2020-03-14 00:00:00.000,72,8086,20200314,00:00,2021-10-07 10:30:51.51,1,107

In [72]:
# 인덱스 이동(shift) 함수
# shift()는 기본값은 인덱스는 1씩 이동 (아래로 한칸씩 이동)
# 1차원 데이터중 list - list ?? --> 에러발생
# numpy의 ndarray형태(행렬) -> 행렬 - 행렬 -> 같은 위치의 원소끼리의 차를 구해서 행렬로 결과
# pandas가 설치될때 numpy가 같이 설치 --> pandas에서 numpy를 사용
# DataFrame과 Series의 values 값들은 행렬로 표시
# series - series --> 행렬의 차로 계산
# 54 - NaN = NaN // 결측치를 0으로 채운다
# 54 - 0 = 54
corona['일일사망자'] = (corona['총사망자'] - corona['총사망자'].shift()).fillna(0)
# int - int -> int
# 총사망자 shift()를 이용하여 계산을 하면 결측치가 우선 발생(해당 데이터의 타입이 float 변환)

In [73]:
corona.head()

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,test,일일확진자,일일사망자
0,2020-03-10 00:00:00.000,54,7513,20200310,00:00,2021-10-07 10:30:51.51,1,0,0.0
1,2020-03-11 00:00:00.000,60,7755,20200311,00:00,2021-10-07 10:30:51.51,1,242,6.0
2,2020-03-12 00:00:00.000,66,7869,20200312,00:00,2021-10-07 10:30:51.51,1,114,6.0
3,2020-03-13 00:00:00.000,67,7979,20200313,00:00,2021-10-07 10:30:51.51,1,110,1.0
4,2020-03-14 00:00:00.000,72,8086,20200314,00:00,2021-10-07 10:30:51.51,1,107,5.0

In [75]:
# 같은 컬럼내에서 데이터들간의 차이를 구하는 함수
# diff(n) : n만큼 이동한 데이터와의 차이를 구하는 함수
# diff(1)의 결과는 Series - Series.shift(1) 결과와 같다
corona['일일사망자2'] = corona['총사망자'].diff(1)

In [76]:
corona.tail()

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,test,일일확진자,일일사망자,일일사망자2
815,2022-06-04 08:56:49.219,24238,18153814,20220604,00:00,2022-06-08 09:11:26.303,1,12039,9.0,9.0
816,2022-06-05 08:53:19.426,24258,18163648,20220605,00:00,2022-06-08 09:11:04.758,1,9834,20.0,20.0
817,2022-06-06 09:00:06.734,24279,18168670,20220606,00:00,2022-06-08 09:10:50.441,1,5022,21.0,21.0
818,2022-06-07 09:09:00.897,24299,18174842,20220607,00:00,2022-06-08 09:10:36.846,1,6172,20.0,20.0
819,2022-06-08 09:09:05.982,24305,18188200,20220608,00:00,NaN,1,13358,6.0,6.0

In [79]:
(corona['일일사망자'] == corona['일일사망자2'].fillna(0)).all()
# all() -> 모든 값이 True인 경우 True -> 하나라도 False가 존재하면 False
# sum() -> 합산
# any() -> 하나라도 True이면 True -> 모든 데이터가 False라면 False

True

In [81]:
corona['일일사망자2'] = corona['일일사망자2'].fillna(0,inplace = True)

In [83]:
# 파생변수 일일확진자, 일일사망자 생성 -> 확인
# 일일확진자와 일일사망자 데이터들의 범위는 ? 0 ~ xxx -> 음수가 아니어야된다.
# 음수인 데이터가 존재하는가? (조건식)
# 일일확진자가 음수라면
corona['일일확진자'] < 0

0      False
1      False
2      False
3      False
4      False
       ...
815    False
816    False
817    False
818    False
819    False
Name: 일일확진자, Length: 820, dtype: bool

In [84]:
# 특정 컬럼의 범위를 찾는다? 최솟값과 최댓값 --> describe()
corona['일일확진자'].describe()

count       820.000000
mean      22171.569512
std       71013.854189
min        -430.000000
25%         125.000000
50%         642.500000
75%        2782.750000
max      621204.000000
Name: 일일확진자, dtype: float64

In [85]:
corona['일일사망자'].describe()

count    820.000000
mean      29.574390
std       68.530863
min       -2.000000
25%        2.000000
50%        5.000000
75%       20.000000
max      469.000000
Name: 일일사망자, dtype: float64

In [87]:
# 음수인 데이터의 개수를 확인
(corona['일일확진자'] < 0).sum()

1

In [88]:
(corona['일일사망자']<0).sum()

1

In [92]:
# 음수가 왜 발생했는가? 이유는 찾아보자
# 해당 데이터를 확인 -> 일일사망자, 일일확진자 데이터들이 음수인 모든 데이터를 확인
flag = (corona[['일일사망자','일일확진자']]<0).any(axis=1) # 데이터프레임에서 비교연산자 -> 결과도 데이터프레임
# flag로 되어있는 데이터셋이 2차원 이상의 데이터셋
corona.loc[flag,]

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,test,일일확진자,일일사망자,일일사망자2
446,2021-05-30 00:00:00.000,1957,139907,20210530,00:00,2021-10-07 10:30:51.51,1,-430,-2.0,None

In [93]:
# 2021년 5월 30일 데이터(index 446)에서 음수가 발생
# 2일전부터 2일후까지의 데이터를 확인
# 인덱스가 444번부터 448번까지 확인
corona.loc[444:448,]

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,test,일일확진자,일일사망자,일일사망자2
444,2021-05-29 00:00:00.000,1951,139427,20210529,00:00,2021-10-07 10:30:51.51,1,533,5.0,None
445,2021-05-30 00:00:00.0,1959,140337,20210531,00:00,2021-10-14 13:48:56.821,1,910,8.0,None
446,2021-05-30 00:00:00.000,1957,139907,20210530,00:00,2021-10-07 10:30:51.51,1,-430,-2.0,None
447,2021-06-01 00:00:00.000,1963,140796,20210601,00:00,2021-10-07 10:30:51.51,1,889,6.0,None
448,2021-06-02 00:00:00.000,1965,141473,20210602,00:00,2021-10-07 10:30:51.51,1,677,2.0,None

In [95]:
# index 445 위치의 등록일시가 잘못입력되었다.
# 2021-05-30 00:00:00.0이 아니라 2021-05-31 00:00:00.000 변경
# 데이터프레임에서 데이터를 변경하는 방법 -> 함수를 이용해서 변경,
#                                   특정 영역을 선택한 뒤 대입 연산자를 이용해서 변경
# 인덱스는 445, 컬럼은 등록일시의 데이터를 추출하여 다른 데이터로 변환
corona.loc[445,'등록일시'] = '2021-05-31 00:00:00.000'

In [97]:
corona.loc[444:448,]

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,test,일일확진자,일일사망자,일일사망자2
444,2021-05-29 00:00:00.000,1951,139427,20210529,00:00,2021-10-07 10:30:51.51,1,533,5.0,None
445,2021-05-31 00:00:00.000,1959,140337,20210531,00:00,2021-10-14 13:48:56.821,1,910,8.0,None
446,2021-05-30 00:00:00.000,1957,139907,20210530,00:00,2021-10-07 10:30:51.51,1,-430,-2.0,None
447,2021-06-01 00:00:00.000,1963,140796,20210601,00:00,2021-10-07 10:30:51.51,1,889,6.0,None
448,2021-06-02 00:00:00.000,1965,141473,20210602,00:00,2021-10-07 10:30:51.51,1,677,2.0,None

- 데이터 수정
    1. 등록일시를 기준으로 오름차순 정렬
    2. 인덱스는 초기화하고 기존의 인덱스는 제거
    3. '일일사망자','일일사망자2',''일일확진자' 컬럼을 제거
    4. '일일사망자' 컬럼을 생성하여 shift() 함수를 이용하여 계산
    5. '일일확진자' 컬럼을 생성하여 diff() 함수를 이용하여 계산
    6. 새롭게 생성한 파생변수들의 데이터에서 음수가 존재하는가 확인

In [113]:
# 오름차순 정렬 변경
corona.sort_values('등록일시',ascending=True,inplace = True)

In [114]:
corona.loc[444:448,]

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,test,일일확진자,일일사망자,일일사망자2
444,2021-05-29 00:00:00.000,1951,139427,20210529,00:00,2021-10-07 10:30:51.51,1,533,5.0,None
446,2021-05-30 00:00:00.000,1957,139907,20210530,00:00,2021-10-07 10:30:51.51,1,-430,-2.0,None
445,2021-05-31 00:00:00.000,1959,140337,20210531,00:00,2021-10-14 13:48:56.821,1,910,8.0,None
447,2021-06-01 00:00:00.000,1963,140796,20210601,00:00,2021-10-07 10:30:51.51,1,889,6.0,None
448,2021-06-02 00:00:00.000,1965,141473,20210602,00:00,2021-10-07 10:30:51.51,1,677,2.0,None

In [116]:
# 인덱스를 초기화하고 기존의 인덱스는 제거
corona.reset_index(drop=True,inplace=True)

In [122]:
# 컬럼을 제거하는 방법 -> drop( ,axis=1)
corona.drop(
    ['일일사망자','일일확진자','일일사망자2'],axis=1,inplace=True)

In [119]:
# 데이터프레임에서 '등록일시' 부터 '수정일시'까지 보겠다
corona.loc[:, '등록일시' : '수정일시']

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시
0,2020-03-10 00:00:00.000,54,7513,20200310,00:00,2021-10-07 10:30:51.51
1,2020-03-11 00:00:00.000,60,7755,20200311,00:00,2021-10-07 10:30:51.51
2,2020-03-12 00:00:00.000,66,7869,20200312,00:00,2021-10-07 10:30:51.51
3,2020-03-13 00:00:00.000,67,7979,20200313,00:00,2021-10-07 10:30:51.51
4,2020-03-14 00:00:00.000,72,8086,20200314,00:00,2021-10-07 10:30:51.51
...,...,...,...,...,...,...
815,2022-06-04 08:56:49.219,24238,18153814,20220604,00:00,2022-06-08 09:11:26.303
816,2022-06-05 08:53:19.426,24258,18163648,20220605,00:00,2022-06-08 09:11:04.758
817,2022-06-06 09:00:06.734,24279,18168670,20220606,00:00,2022-06-08 09:10:50.441
818,2022-06-07 09:09:00.897,24299,18174842,20220607,00:00,2022-06-08 09:10:36.846
819,2022-06-08 09:09:05.982,24305,18188200,20220608,00:00,NaN

In [121]:
# 컬럼의 위치를 변경해서 확인
corona[['등록일시','수정일시','총확진자','총사망자']]

                        등록일시                     수정일시      총확진자   총사망자
0    2020-03-10 00:00:00.000   2021-10-07 10:30:51.51      7513     54
1    2020-03-11 00:00:00.000   2021-10-07 10:30:51.51      7755     60
2    2020-03-12 00:00:00.000   2021-10-07 10:30:51.51      7869     66
3    2020-03-13 00:00:00.000   2021-10-07 10:30:51.51      7979     67
4    2020-03-14 00:00:00.000   2021-10-07 10:30:51.51      8086     72
..                       ...                      ...       ...    ...
815  2022-06-04 08:56:49.219  2022-06-08 09:11:26.303  18153814  24238
816  2022-06-05 08:53:19.426  2022-06-08 09:11:04.758  18163648  24258
817  2022-06-06 09:00:06.734  2022-06-08 09:10:50.441  18168670  24279
818  2022-06-07 09:09:00.897  2022-06-08 09:10:36.846  18174842  24299
819  2022-06-08 09:09:05.982                      NaN  18188200  24305

[820 rows x 4 columns]

In [123]:
# '일일사망자' 컬럼은 shift() 함수를 이용하여 파생변수 생성
corona['일일사망자'] = (corona['총사망자'] - corona['총사망자'].shift(1)).fillna(0)

In [124]:
# '일일확진자' 컬럼은 diff() 함수를 이용하여 파생변수 생성
corona['일일확진자'] = corona['총확진자'].diff(1).fillna(0)

In [126]:
flag = (corona[['일일확진자','일일사망자']]<0).any(axis=1)

In [127]:
corona[['일일확진자','일일사망자']].describe()

               일일확진자       일일사망자
count     820.000000  820.000000
mean    22171.569512   29.574390
std     71013.844067   68.530435
min         0.000000    0.000000
25%       125.000000    2.000000
50%       634.000000    5.000000
75%      2782.750000   20.000000
max    621204.000000  469.000000