### 데이터베이스와 python의 연결
1. 데이터베이스와 연결을 하기 위한 라이브러리 설치
2. 라이브러리 로드
3. 데이터베이스 서버와의 연결
    - 서버의 정보
        - 서버의 주소
        - 서버의 포트(3306)
        - 아이디 (root)
        - 비밀번호( 비밀번호가 없으면 생략가능 )
        - 사용할 데이터베이스명(multicam)
4. Cursor(가상공간)를 생성
5. SQL query문을 작성하여 질의를 DB서버에 보낸다.
    - select(조회)
        - return 데이터가 존재
        - fetchall() 함수를 이용해서 결과 값을 돌려받는다.
    - insert, update, delete
        - return 데이터가 존재 x
        - 실제 데이터가 변화(Cursor 변환) -> DB서버와 Cursor 동기화
6. 서버와의 연결을 종료

In [ ]:
# 라이브러리 설치
# !pip install pymysql cryptography

Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: cryptography in c:\users\lovek\appdata\local\programs\python\python311\lib\site-packages (42.0.7)
Requirement already satisfied: cffi>=1.12 in c:\users\lovek\appdata\local\programs\python\python311\lib\site-packages (from cryptography) (1.15.1)
Requirement already satisfied: pycparser in c:\users\lovek\appdata\local\programs\python\python311\lib\site-packages (from cffi>=1.12->cryptography) (2.21)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2

WARNING: Ignoring invalid distribution ~yproj (C:\Users\lovek\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~yproj (C:\Users\lovek\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~yproj (C:\Users\lovek\AppData\Local\Programs\Python\Python311\Lib\site-packages)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
# 라이브러리 로드
import pymysql

In [3]:
# DB server와의 연결
# 컴퓨터의 주소? 외부 컴퓨터 DB에 접속하려면 IP 필요
# 내 컴퓨터 DB server 주소 -> 127.0.0.1 | localhost

_db = pymysql.connect(
    host = '127.0.0.1', # 서버의 주소
    port = 3306,        # 서버의 포트(숫자로 입력)
    user = 'root',      # DB Server 접속 아이디
    password= '1234',   # 비밀번호
    db = 'multicam'     # 데이터베이스명
)

In [4]:
# 가상공간인 Cursor 생성


# 기본값으로 커서 생성 -> select문으로 데이터를 로드할때 결과 데이터의 타입 지정
cursor = _db.cursor()
# DictCursor 옵션을 사용해서 커서 생성
cursor2 = _db.cursor(pymysql.cursors.DictCursor)

In [ ]:
# query 문을 작성 -> 문자열 데이터로 작성
select_query = """
    select * from `emp`
"""
# select_query를 cursor에게 보낸다 (질의)
cursor.execute(select_query)
cursor2.execute(select_query)
# execute() 함수의 리턴은 select인 경우 인덱스의 수 출력

14

In [7]:
# cursor 안에 select의 결과가 저장되어 있어서 해당 데이터를 가져온다(fetchall())
# fetchall() 함수를 호출 시 cursor의 데이터를 가져오고 cursor에 데이터는 제거
select1 = cursor.fetchall()
select2 = cursor2.fetchall()

In [8]:
select1

((7369.0, 'SMITH', 'CLERK', 7902.0, '1980-12-17', 800.0, 0.0, 20.0),
 (7499.0, 'ALLEN', 'SALESMAN', 7698.0, '1981-02-20', 1600.0, 300.0, 30.0),
 (7521.0, 'WARD', 'SALESMAN', 7698.0, '1981-02-22', 1250.0, 500.0, 30.0),
 (7566.0, 'JONES', 'MANAGER', 7839.0, '1981-04-02', 2975.0, 0.0, 20.0),
 (7654.0, 'MARTIN', 'SALESMAN', 7698.0, '1981-09-28', 1250.0, 1400.0, 30.0),
 (7698.0, 'BLAKE', 'MANAGER', 7839.0, '1981-05-01', 2850.0, 0.0, 30.0),
 (7782.0, 'CLARK', 'MANAGER', 7839.0, '1981-06-09', 2450.0, 0.0, 10.0),
 (7788.0, 'SCOTT', 'ANALYST', 7566.0, '1987-06-28', 3000.0, 0.0, 20.0),
 (7839.0, 'KING', 'PRESIDENT', 0.0, '1981-11-17', 5000.0, 0.0, 10.0),
 (7844.0, 'TURNER', 'SALESMAN', 7698.0, '1981-09-08', 1500.0, 0.0, 30.0),
 (7876.0, 'ADAMS', 'CLERK', 7788.0, '1987-07-13', 1100.0, 0.0, 20.0),
 (7900.0, 'JAMES', 'CLERK', 7698.0, '1981-12-03', 950.0, 0.0, 30.0),
 (7902.0, 'FORD', 'ANALYST', 7566.0, '1981-12-03', 3000.0, 0.0, 20.0),
 (7934.0, 'MILLER', 'CLERK', 7782.0, '1982-01-23', 1300.0, 0.0, 10.0))

In [9]:
select2

[{'EMPNO': 7369.0,
  'ENAME': 'SMITH',
  'JOB': 'CLERK',
  'MGR': 7902.0,
  'HIREDATE': '1980-12-17',
  'SAL': 800.0,
  'COMM': 0.0,
  'DEPTNO': 20.0},
 {'EMPNO': 7499.0,
  'ENAME': 'ALLEN',
  'JOB': 'SALESMAN',
  'MGR': 7698.0,
  'HIREDATE': '1981-02-20',
  'SAL': 1600.0,
  'COMM': 300.0,
  'DEPTNO': 30.0},
 {'EMPNO': 7521.0,
  'ENAME': 'WARD',
  'JOB': 'SALESMAN',
  'MGR': 7698.0,
  'HIREDATE': '1981-02-22',
  'SAL': 1250.0,
  'COMM': 500.0,
  'DEPTNO': 30.0},
 {'EMPNO': 7566.0,
  'ENAME': 'JONES',
  'JOB': 'MANAGER',
  'MGR': 7839.0,
  'HIREDATE': '1981-04-02',
  'SAL': 2975.0,
  'COMM': 0.0,
  'DEPTNO': 20.0},
 {'EMPNO': 7654.0,
  'ENAME': 'MARTIN',
  'JOB': 'SALESMAN',
  'MGR': 7698.0,
  'HIREDATE': '1981-09-28',
  'SAL': 1250.0,
  'COMM': 1400.0,
  'DEPTNO': 30.0},
 {'EMPNO': 7698.0,
  'ENAME': 'BLAKE',
  'JOB': 'MANAGER',
  'MGR': 7839.0,
  'HIREDATE': '1981-05-01',
  'SAL': 2850.0,
  'COMM': 0.0,
  'DEPTNO': 30.0},
 {'EMPNO': 7782.0,
  'ENAME': 'CLARK',
  'JOB': 'MANAGER',
  'MGR': 7839.0,
  'HIREDATE': '1981-06-09',
  'SAL': 2450.0,
  'COMM': 0.0,
  'DEPTNO': 10.0},
 {'EMPNO': 7788.0,
  'ENAME': 'SCOTT',
  'JOB': 'ANALYST',
  'MGR': 7566.0,
  'HIREDATE': '1987-06-28',
  'SAL': 3000.0,
  'COMM': 0.0,
  'DEPTNO': 20.0},
 {'EMPNO': 7839.0,
  'ENAME': 'KING',
  'JOB': 'PRESIDENT',
  'MGR': 0.0,
  'HIREDATE': '1981-11-17',
  'SAL': 5000.0,
  'COMM': 0.0,
  'DEPTNO': 10.0},
 {'EMPNO': 7844.0,
  'ENAME': 'TURNER',
  'JOB': 'SALESMAN',
  'MGR': 7698.0,
  'HIREDATE': '1981-09-08',
  'SAL': 1500.0,
  'COMM': 0.0,
  'DEPTNO': 30.0},
 {'EMPNO': 7876.0,
  'ENAME': 'ADAMS',
  'JOB': 'CLERK',
  'MGR': 7788.0,
  'HIREDATE': '1987-07-13',
  'SAL': 1100.0,
  'COMM': 0.0,
  'DEPTNO': 20.0},
 {'EMPNO': 7900.0,
  'ENAME': 'JAMES',
  'JOB': 'CLERK',
  'MGR': 7698.0,
  'HIREDATE': '1981-12-03',
  'SAL': 950.0,
  'COMM': 0.0,
  'DEPTNO': 30.0},
 {'EMPNO': 7902.0,
  'ENAME': 'FORD',
  'JOB': 'ANALYST',
  'MGR': 7566.0,
  'HIREDATE': '1981-12-03',
  'SAL': 3000.0,
  'COMM': 0.0,
  'DEPTNO': 20.0},
 {'EMPNO': 7934.0,
  'ENAME': 'MILLER',
  'JOB': 'CLERK',
  'MGR': 7782.0,
  'HIREDATE': '1982-01-23',
  'SAL': 1300.0,
  'COMM': 0.0,
  'DEPTNO': 10.0}]

In [10]:
import pandas as pd

In [11]:
df1 = pd.DataFrame(select1)
df2 = pd.DataFrame(select2)

In [12]:
df1.head(1)

        0      1      2       3           4      5    6     7
0  7369.0  SMITH  CLERK  7902.0  1980-12-17  800.0  0.0  20.0

In [13]:
df2.head(1)

    EMPNO  ENAME    JOB     MGR    HIREDATE    SAL  COMM  DEPTNO
0  7369.0  SMITH  CLERK  7902.0  1980-12-17  800.0   0.0    20.0