In [1]:
from selenium import webdriver
from bs4 import BeautifulSoup as bs
import pandas as pd
import requests

In [2]:
# 무신사의 반팔 상의 주소를 저장 
url = 'https://www.musinsa.com/category/001001/goods?gf=A'

# 상품에 대한 정보(브랜명, 상품 이름, 상품의 할인율, 가격)

res = requests.get(url)
res

In [3]:
soup = bs(res.text, 'html.parser')
soup

<!DOCTYPE html>
<html lang="ko-KR"><head><meta charset="utf-8" data-next-head=""/><title data-next-head="">반소매 티셔츠 | 무신사 추천 상품</title><meta content="width=device-width, initial-scale=1" data-next-head="" name="viewport"/><meta content="무신사 추천 상품" data-next-head="" data-rh="true" name="description"/><meta content="website" data-next-head="" property="og:type"/><meta content="반소매 티셔츠 | 무신사 추천 상품" data-next-head="" data-rh="true" property="og:title"/><meta content="무신사 추천 상품" data-next-head="" data-rh="true" property="og:description"/><meta content="https://image.msscdn.net/static/assets/bi/og/og_musinsa.png" data-next-head="" name="og:image" property="og:image"/><link data-next-head="" href="https://www.musinsa.com/category/001001" rel="canonical"/><link data-next-head="" href="https://www.musinsa.com/category/001001" hreflang="ko-KR" rel="alternate"/><link data-next-head="" href="https://static.msscdn.net/static/v2/pc/category/vendor.js" rel="modulepreload"/><link data-next-head="" href="https://static.msscdn.net/static/v2/pc/category/category.js" rel="modulepreload"/><link href="https://static.msscdn.net/static/common/layout-pc/style.css" rel="stylesheet" type="text/css"/><link href="https://static.msscdn.net/platform/css/common-mobile.css" rel="stylesheet" type="text/css"/><link href="https://static.msscdn.net/static/mds/2.0.0/mds.css" rel="stylesheet" type="text/css"/><link href="https://image.msscdn.net/static/assets/bi/favicon/favicon.svg" rel="icon" type="image/svg+xml"/><link href="https://image.msscdn.net/static/assets/bi/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/><link href="https://image.msscdn.net/static/assets/bi/favicon/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png"/><link href="https://image.msscdn.net/static/assets/bi/favicon/favicon-192x192.png" rel="icon" sizes="192x192" type="image/png"/><link href="/favicon.ico" rel="icon" sizes="any"/><link href="https://image.msscdn.net/static/assets/bi/favicon/favicon-180x180.png" rel="apple-touch-icon" sizes="180x180"/><meta content="noindex,nofollow" name="Baiduspider"/><style>
              #__next {
                height: 100%;
              }
            </style><script data-nscript="beforeInteractive" id="category-data">
        window.__MSS_FE__ = {
          meta: {"data":{"categoryCode":"001001","categoryTitle":"반소매 티셔츠","metaKeyword":"반팔티, 티셔츠","linkUrl":"https://www.musinsa.com/category/001001","isStore":false,"storeCode":"","storeIconImage":""},"meta":{"result":"SUCCESS"}},
          shared: {"loggedIn":false},
          config: {"gender":{"syncQueryToCookie":true},"isMobile":false,"mfs":true,"couponPrice":true,"priceGuide":true,"isSubwayFilterEnabled":true,"dataDog":{"sessionSampleRate":1},"usedDynamicFacet":true,"usedDefaultFilter":true,"usedRisingSort":true,"newGoodsLikeSort":true,"isPlpSortOrderImproved":true,"isAdCarousels":true,"isAdCarouselsAlwaysShow":true,"isGoodsAPIVersion2":true,"isPriceHistogramEnabled":true,"returnAdOnFilter":true,"isAppbarSpecialtyHomeEnabled":true,"isFilterRetentionPolicy":true,"isDiscountRateMultiSelectEnabled":true,"isQuickFilterMotionEnabled":true,"isCategorySnapShortsEnabled":true,"isQuickFilterLottieEnabled":true},
          experimentVariant: {},
          isMfsEnabled: true,
          isHeavyGroup: false,
        }
      </script><script data-nscript="beforeInteractive" id="mss-i18n-bundle">window.__MSS_I18N__={"countries":[{"code":"KR","name":{"nativeText":"대한민국","texts":{"en-US":"South Korea","ja-JP":"韓国","ko-KR":"대한민국","zh-CN":"韩国","zh-TW":"韓國"}},"continent":{"code":"AS","name":{"nativeText":"Asia","texts":{"en-US":"Asia","ja-JP":"アジア","ko-KR":"아시아","zh-CN":"亚洲","zh-TW":"亞洲"}}},"defaultCurrency":"KRW","defaultLocale":"ko-KR","defaultLengthUnit":"CENTIMETER","defaultWeightUnit":"KILOGRAM"},{"code":"JP","name":{"nativeText":"日本","texts":{"en-US":"Japan","ja-JP":"日本","ko-KR":"일본","zh-CN":"日本","zh-TW":"日本"}},"continent":{"code":"AS","name":{"nativeText":"Asia","texts":{"en-US":"Asia","ja-JP":"アジア","ko-KR":"아시아","zh-CN":"亚洲","zh-TW":"亞洲"}}},"defaultCurrency":"JPY","defaultLocale":"ja-JP","defaultLengthUnit":"CENTIMETER","defaultWeightUnit":"KILOGRAM"},{"code":"US","name":{"nativeText":"United States","texts":{"en-US":"United States","ja-JP":"アメリカ","ko-KR":"미국","zh-CN":"美国","zh-TW":"美國"}},"continent":{"code":"NA","name":{"nativeText":"Americas","texts":{"en-US":"Americas","ja-JP":"アメリカ","ko-KR":"미주","zh-CN":"美洲","zh-TW":"美洲"}}},"defaultCurrency":"USD","defaultLocale":"en-US","defaultLengthUnit":"INCH","defaultWeightUnit":"POUND"},{"code":"AU","name":{"nativeText":"Australia","texts":{"en-US":"Australia","ja-JP":"オーストラリア","ko-KR":"호주","zh-CN":"澳大利亚","zh-TW":"澳大利亞"}},"continent":{"code":"OC","name":{"nativeText":"Oceania","texts":{"en-US":"Oceania","ja-JP":"オセアニア","ko-KR":"오세아니아","zh-CN":"大洋洲","zh-TW":"大洋洲"}}},"defaultCurrency":"AUD","defaultLocale":"en-US","defaultLengthUnit":"INCH","defaultWeightUnit":"POUND"},{"code":"CA","name":{"nativeText":"Canada","texts":{"en-US":"Canada","ja-JP":"カナダ","ko-KR":"캐나다","zh-CN":"加拿大","zh-TW":"加拿大"}},"continent":{"code":"NA","name":{"nativeText":"Americas","texts":{"en-US":"Americas","ja-JP":"アメリカ","ko-KR":"미주","zh-CN":"美洲","zh-TW":"美洲"}}},"defaultCurrency":"CAD","defaultLocale":"en-US","defaultLengthUnit":"INCH","defaultWeightUnit":"POUND"},{"code":"HK","name":{"nativeText":"香港","texts":{"en-US":"Hong Kong","ja-JP":"香港","ko-KR":"홍콩","zh-CN":"香港","zh-TW":"香港"}},"continent":{"code":"AS","name":{"nativeText":"Asia","texts":{"en-US":"Asia","ja-JP":"アジア","ko-KR":"아시아","zh-CN":"亚洲","zh-TW":"亞洲"}}},"defaultCurrency":"HKD","defaultLocale":"zh-TW","defaultLengthUnit":"CENTIMETER","defaultWeightUnit":"KILOGRAM"},{"code":"ID","name":{"nativeText":"Indonesia","texts":{"en-US":"Indonesia","ja-JP":"インドネシア","ko-KR":"인도네시아","zh-CN":"印度尼西亚","zh-TW":"印度尼西亞"}},"continent":{"code":"AS","name":{"nativeText":"Asia","texts":{"en-US":"Asia","ja-JP":"アジア","ko-KR":"아시아","zh-CN":"亚洲","zh-TW":"亞洲"}}},"defaultCurrency":"IDR","defaultLocale":"en-US","defaultLengthUnit":"CENTIMETER","defaultWeightUnit":"KILOGRAM"},{"code":"MY","name":{"nativeText":"Malaysia","texts":{"en-US":"Malaysia","ja-JP":"マレーシア","ko-KR":"말레이시아","zh-CN":"马来西亚","zh-TW":"馬來西亞"}},"continent":{"code":"AS","name":{"nativeText":"Asia","texts":{"en-US":"Asia","ja-JP":"アジア","ko-KR":"아시아","zh-CN":"亚洲","zh-TW":"亞洲"}}},"defaultCurrency":"MYR","defaultLocale":"en-US","defaultLengthUnit":"CENTIMETER","defaultWeightUnit":"KILOGRAM"},{"code":"NZ","name":{"nativeText":"New Zealand","texts":{"en-US":"New Zealand","ja-JP":"ニュージーランド","ko-KR":"뉴질랜드","zh-CN":"新西兰","zh-TW":"紐西蘭"}},"continent":{"code":"OC","name":{"nativeText":"Oceania","texts":{"en-US":"Oceania","ja-JP":"オセアニア","ko-KR":"오세아니아","zh-CN":"大洋洲","zh-TW":"大洋洲"}}},"defaultCurrency":"NZD","defaultLocale":"en-US","defaultLengthUnit":"INCH","defaultWeightUnit":"POUND"},{"code":"PH","name":{"nativeText":"Philippines","texts":{"en-US":"Philippines","ja-JP":"フィリピン","ko-KR":"필리핀","zh-CN":"菲律宾","zh-TW":"菲律賓"}},"continent":{"code":"AS","name":{"nativeText":"Asia","texts":{"en-US":"Asia","ja-JP":"アジア","ko-KR":"아시아","zh-CN":"亚洲","zh-TW":"亞洲"}}},"defaultCurrency":"PHP","defaultLocale":"en-US","defaultLengthUnit":"CENTIMETER","defaultWeightUnit":"KILOGRAM"},{"code":"SG","name":{"nativeText":"Singapore","texts":{"en-US":"Singapore","ja-JP":"シンガポール","ko-KR":"싱가포르","zh-CN":"新加坡","zh-TW":"新加坡"}},"continent":{"code":"AS","name":{"nativeText":"Asia","texts":{"en-US":"Asia","ja-JP":"アジア","ko-KR":"아시아","zh-CN":"亚洲","zh-TW":"亞洲"}}},"defaultCurrency":"SGD","defaultLocale":"en-US","defaultLengthUnit":"CENTIMETER","defaultWeightUnit":"KILOGRAM"},{"code":"TW","name":{"nativeText":"臺灣","texts":{"en-US":"Taiwan","ja-JP":"台湾","ko-KR":"대만","zh-CN":"台湾","zh-TW":"臺灣"}},"continent":{"code":"AS","name":{"nativeText":"Asia","texts":{"en-US":"Asia","ja-JP":"アジア","ko-KR":"아시아","zh-CN":"亚洲","zh-TW":"亞洲"}}},"defaultCurrency":"TWD","defaultLocale":"zh-TW","defaultLengthUnit":"CENTIMETER","defaultWeightUnit":"KILOGRAM"},{"code":"TH","name":{"nativeText":"Thailand","texts":{"en-US":"Thailand","ja-JP":"タイ","ko-KR":"태국","zh-CN":"泰国","zh-TW":"泰國"}},"continent":{"code":"AS","name":{"nativeText":"Asia","texts":{"en-US":"Asia","ja-JP":"アジア","ko-KR":"아시아","zh-CN":"亚洲","zh-TW":"亞洲"}}},"defaultCurrency":"THB","defaultLocale":"en-US","defaultLengthUnit":"CENTIMETER","defaultWeightUnit":"KILOGRAM"},{"code":"VN","name":{"nativeText":"Việt Nam","texts":{"en-US":"Vietnam","ja-JP":"ベトナム","ko-KR":"베트남","zh-CN":"越南","zh-TW":"越南"}},"continent":{"code":"AS","name":{"nativeText":"Asia","texts":{"en-US":"Asia","ja-JP":"アジア","ko-KR":"아시아","zh-CN":"亚洲","zh-TW":"亞洲"}}},"defaultCurrency":"VND","defaultLocale":"en-US","defaultLengthUnit":"CENTIMETER","defaultWeightUnit":"KILOGRAM"}],"currencies":[{"code":"KRW","symbol":"₩"},{"code":"JPY","symbol":"¥"},{"code":"USD","symbol":"US$"},{"code":"AUD","symbol":"A$"},{"code":"CAD","symbol":"CA$"},{"code":"HKD","symbol":"HK$"},{"code":"IDR","symbol":"Rp"},{"code":"MYR","symbol":"RM"},{"code":"NZD","symbol":"NZ$"},{"code":"PHP","symbol":"₱"},{"code":"SGD","symbol":"S$"},{"code":"TWD","symbol":"NT$"},{"code":"THB","symbol":"฿"},{"code":"VND","symbol":"₫"}],"locales":[{"code":"en-US","language":"en","country":"US","name":{"nativeText":"English","texts":{"en-US":"English","ja-JP":"英語","ko-KR":"영어","zh-CN":"英语","zh-TW":"英語"}}},{"code":"ko-KR","language":"ko","country":"KR","name":{"nativeText":"한국어","texts":{"en-US":"Korean","ja-JP":"韓国語","ko-KR":"한국어","zh-CN":"韩语","zh-TW":"韓語"}}},{"code":"ja-JP","language":"ja","country":"JP","name":{"nativeText":"日本語","texts":{"en-US":"Japanese","ja-JP":"日本語","ko-KR":"일본어","zh-CN":"日语","zh-TW":"日語"}}},{"code":"zh-CN","language":"zh","country":"CN","name":{"nativeText":"简体中文","texts":{"en-US":"Simplified Chinese","ja-JP":"簡体中国語","ko-KR":"중국어(간체)","zh-CN":"简体中文","zh-TW":"簡體中文"}}},{"code":"zh-TW","language":"zh","country":"TW","name":{"nativeText":"繁體中文","texts":{"en-US":"Traditional Chinese","ja-JP":"繁体中国語","ko-KR":"중국어(번체)","zh-CN":"繁体中文","zh-TW":"繁體中文"}}}],"continents":[{"code":"AS","name":{"nativeText":"Asia","texts":{"en-US":"Asia","ja-JP":"アジア","ko-KR":"아시아","zh-CN":"亚洲","zh-TW":"亞洲"}}},{"code":"NA","name":{"nativeText":"Americas","texts":{"en-US":"Americas","ja-JP":"アメリカ","ko-KR":"미주","zh-CN":"美洲","zh-TW":"美洲"}}},{"code":"OC","name":{"nativeText":"Oceania","texts":{"en-US":"Oceania","ja-JP":"オセアニア","ko-KR":"오세아니아","zh-CN":"大洋洲","zh-TW":"大洋洲"}}}]};</script><script data-nscript="beforeInteractive" id="mss-gtm">(function (w, d, s, l, i) {
                  w[l] = w[l] || [];
                  w[l].push({ 'gtm.start': new Date().getTime(), 'event': 'gtm.js' });
                  var f = d.getElementsByTagName(s)[0],
                    j = d.createElement(s),
                    dl = l != 'dataLayer' ? '&l=' + l : '';
                  j.async = true;
                  j.src = 'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
                  f.parentNode.insertBefore(j, f);

1. selenium을 이용하여 무신사 페이지에 요청
2. 해당 페이지의 html 문서를 불러온다
3. bs4를 이용하여 데이터 파싱
4. GoodsList__List로 시작하는 class 값을 가진 div 태그를 찾는다.
5. GoodsList__Row로 시작하는 class 값을 가진 모든 div 태그를 찾는다
6. sc-it로 시작하는 class 값을 가진 모든 div 태그를 찾는다.
7. 브랜드명, 이름, 할인율, 가격 데이터, 해당 상품의 링크 주소를 추출
8. 추출한 데이터를 데이터프레임으로 생성

In [4]:
import re
import time

In [5]:
driver = webdriver.Chrome()

In [6]:
# 무신사 페이지에 요청
driver.get(url)

In [7]:
time.sleep(5)   # ← 이 줄 추가

In [8]:
soup = bs(driver.page_source, 'html.parser')

In [9]:
soup

<html lang="ko-KR"><head><link href="https://static.msscdn.net/static/mds/2.0.0/mds-with-prefix.css" rel="stylesheet" type="text/css"/><meta charset="utf-8" data-next-head=""/><title data-next-head="">반소매 티셔츠 | 무신사 추천 상품</title><meta content="width=device-width, initial-scale=1" data-next-head="" name="viewport"/><meta content="website" data-next-head="" property="og:type"/><meta content="https://image.msscdn.net/static/assets/bi/og/og_musinsa.png" data-next-head="" name="og:image" property="og:image"/><link data-next-head="" href="https://www.musinsa.com/category/001001" rel="canonical"/><link data-next-head="" href="https://www.musinsa.com/category/001001" hreflang="ko-KR" rel="alternate"/><link data-next-head="" href="https://static.msscdn.net/static/v2/pc/category/vendor.js" rel="modulepreload"/><link data-next-head="" href="https://static.msscdn.net/static/v2/pc/category/category.js" rel="modulepreload"/><link href="https://static.msscdn.net/static/common/layout-pc/style.css" rel="stylesheet" type="text/css"/><link href="https://static.msscdn.net/platform/css/common-mobile.css" rel="stylesheet" type="text/css"/><link href="https://static.msscdn.net/static/mds/2.0.0/mds.css" rel="stylesheet" type="text/css"/><link href="https://image.msscdn.net/static/assets/bi/favicon/favicon.svg" rel="icon" type="image/svg+xml"/><link href="https://image.msscdn.net/static/assets/bi/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/><link href="https://image.msscdn.net/static/assets/bi/favicon/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png"/><link href="https://image.msscdn.net/static/assets/bi/favicon/favicon-192x192.png" rel="icon" sizes="192x192" type="image/png"/><link href="/favicon.ico" rel="icon" sizes="any"/><link href="https://image.msscdn.net/static/assets/bi/favicon/favicon-180x180.png" rel="apple-touch-icon" sizes="180x180"/><meta content="noindex,nofollow" name="Baiduspider"/><style>
              #__next {
                height: 100%;
              }
            </style><script src="https://ct.pinterest.com/static/ct/token_create.js"></script><script async="" src="https://s.pinimg.com/ct/lib/main.0cb4b510.js"></script><script async="" src="https://connect.facebook.net/signals/config/240753852943871?v=2.9.345&amp;r=stable&amp;domain=www.musinsa.com&amp;hme=319b24ce7b9254a3f841b0e945e5985d85ddfae2329b4423159b7af5bd4224f0&amp;ex_m=105%2C208%2C156%2C22%2C73%2C74%2C147%2C69%2C68%2C11%2C165%2C91%2C16%2C139%2C128%2C39%2C76%2C79%2C135%2C161%2C167%2C8%2C4%2C5%2C7%2C6%2C3%2C92%2C102%2C168%2C173%2C222%2C30%2C75%2C234%2C233%2C232%2C23%2C33%2C55%2C104%2C61%2C10%2C64%2C98%2C99%2C100%2C106%2C131%2C31%2C29%2C133%2C134%2C130%2C129%2C157%2C77%2C160%2C158%2C159%2C50%2C60%2C124%2C15%2C164%2C45%2C279%2C280%2C278%2C26%2C27%2C28%2C48%2C148%2C78%2C113%2C18%2C20%2C44%2C40%2C42%2C41%2C84%2C93%2C97%2C111%2C146%2C149%2C46%2C112%2C24%2C21%2C120%2C70%2C36%2C151%2C150%2C152%2C143%2C141%2C25%2C35%2C59%2C110%2C163%2C71%2C17%2C154%2C115%2C82%2C67%2C19%2C86%2C87%2C117%2C85%2C137%2C136%2C140%2C162%2C34%2C293%2C309%2C215%2C204%2C62%2C205%2C203%2C312%2C303%2C52%2C216%2C108%2C132%2C81%2C122%2C54%2C47%2C49%2C114%2C121%2C127%2C126%2C58%2C65%2C63%2C153%2C116%2C37%2C32%2C53%2C56%2C101%2C166%2C1%2C125%2C14%2C123%2C12%2C2%2C57%2C94%2C66%2C119%2C90%2C89%2C169%2C170%2C95%2C96%2C9%2C103%2C51%2C144%2C88%2C80%2C72%2C118%2C107%2C43%2C145%2C0%2C83%2C138%2C142%2C155%2C38%2C109%2C13%2C171"></script><script async="" src="https://connect.facebook.net/en_US/fbevents.js"></script><script async="" src="https://s.pinimg.com/ct/core.js" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtag/destination?id=AW-727913138&amp;cx=c&amp;gtm=4e66o0h2" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtag/destination?id=AW-964079298&amp;cx=c&amp;gtm=4e66o0h2" type="text/javascript"></script><script async="" src="https://static.ads-twitter.com/uwt.js"></script><script async="" src="https://t1.kakaocdn.net/kakao_js_sdk/v1/kakao.min.js" type="text/javascript"></script><script async="" src="https://musinsa-collect.s3.ap-northeast-2.amazonaws.com/v2.0/heathrow-v2-async.js" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-MMJ53Z2&amp;gtm=4e66o0h2" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-8PEGV51YTJ&amp;cx=c&amp;gtm=4e66o0h2" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-KTZPBQV"></script><script data-nscript="beforeInteractive" id="category-data">
        window.__MSS_FE__ = {
          meta: {"data":{"categoryCode":"001001","categoryTitle":"반소매 티셔츠","metaKeyword":"반팔티, 티셔츠","linkUrl":"https://www.musinsa.com/category/001001","isStore":false,"storeCode":"","storeIconImage":""},"meta":{"result":"SUCCESS"}},
          shared: {"loggedIn":false},
          config: {"gender":{"syncQueryToCookie":true},"isMobile":false,"mfs":true,"couponPrice":true,"priceGuide":true,"isSubwayFilterEnabled":true,"dataDog":{"sessionSampleRate":1},"usedDynamicFacet":true,"usedDefaultFilter":true,"usedRisingSort":true,"newGoodsLikeSort":true,"isPlpSortOrderImproved":true,"isAdCarousels":true,"isAdCarouselsAlwaysShow":true,"isGoodsAPIVersion2":true,"isPriceHistogramEnabled":true,"returnAdOnFilter":true,"isAppbarSpecialtyHomeEnabled":true,"isFilterRetentionPolicy":true,"isDiscountRateMultiSelectEnabled":true,"isQuickFilterMotionEnabled":true,"isCategorySnapShortsEnabled":true,"isQuickFilterLottieEnabled":true},
          experimentVariant: {},
          isMfsEnabled: true,
          isHeavyGroup: false,
        }
      </script><script data-nscript="beforeInteractive" id="mss-i18n-bundle">window.__MSS_I18N__={"countries":[{"code":"KR","name":{"nativeText":"대한민국","texts":{"en-US":"South Korea","ja-JP":"韓国","ko-KR":"대한민국","zh-CN":"韩国","zh-TW":"韓國"}},"continent":{"code":"AS","name":{"nativeText":"Asia","texts":{"en-US":"Asia","ja-JP":"アジア","ko-KR":"아시아","zh-CN":"亚洲","zh-TW":"亞洲"}}},"defaultCurrency":"KRW","defaultLocale":"ko-KR","defaultLengthUnit":"CENTIMETER","defaultWeightUnit":"KILOGRAM"},{"code":"JP","name":{"nativeText":"日本","texts":{"en-US":"Japan","ja-JP":"日本","ko-KR":"일본","zh-CN":"日本","zh-TW":"日本"}},"continent":{"code":"AS","name":{"nativeText":"Asia","texts":{"en-US":"Asia","ja-JP":"アジア","ko-KR":"아시아","zh-CN":"亚洲","zh-TW":"亞洲"}}},"defaultCurrency":"JPY","defaultLocale":"ja-JP","defaultLengthUnit":"CENTIMETER","defaultWeightUnit":"KILOGRAM"},{"code":"US","name":{"nativeText":"United States","texts":{"en-US":"United States","ja-JP":"アメリカ","ko-KR":"미국","zh-CN":"美国","zh-TW":"美國"}},"continent":{"code":"NA","name":{"nativeText":"Americas","texts":{"en-US":"Americas","ja-JP":"アメリカ","ko-KR":"미주","zh-CN":"美洲","zh-TW":"美洲"}}},"defaultCurrency":"USD","defaultLocale":"en-US","defaultLengthUnit":"INCH","defaultWeightUnit":"POUND"},{"code":"AU","name":{"nativeText":"Australia","texts":{"en-US":"Australia","ja-JP":"オーストラリア","ko-KR":"호주","zh-CN":"澳大利亚","zh-TW":"澳大利亞"}},"continent":{"code":"OC","name":{"nativeText":"Oceania","texts":{"en-US":"Oceania","ja-JP":"オセアニア","ko-KR":"오세아니아","zh-CN":"大洋洲","zh-TW":"大洋洲"}}},"defaultCurrency":"AUD","defaultLocale":"en-US","defaultLengthUnit":"INCH","defaultWeightUnit":"POUND"},{"code":"CA","name":{"nativeText":"Canada","texts":{"en-US":"Canada","ja-JP":"カナダ","ko-KR":"캐나다","zh-CN":"加拿大","zh-TW":"加拿大"}},"continent":{"code":"NA","name":{"nativeText":"Americas","texts":{"en-US":"Americas","ja-JP":"アメリカ","ko-KR":"미주","zh-CN":"美洲","zh-TW":"美洲"}}},"defaultCurrency":"CAD","defaultLocale":"en-US","defaultLengthUnit":"INCH","defaultWeightUnit":"POUND"},{"code":"HK","name":{"nativeText":"香港","texts":{"en-US":"Hong Kong","ja-JP":"香港","ko-KR":"홍콩","zh-CN":"香港","zh-TW":"香港"}},"continent":{"code":"AS","name":{"nativeText":"Asia","texts":{"en-US":"Asia","ja-JP":"アジア","ko-KR":"아시아","zh-CN":"亚洲","zh-TW":"亞洲"}}},"defaultCurrency":"HKD","defaultLocale":"zh-TW","defaultLengthUnit":"CENTIMETER","defaultWeightUnit":"KILOGRAM"},{"code":"ID","name":{"nativeText":"Indonesia","texts":{"en-US":"Indonesia","ja-JP":"インドネシア","ko-KR":"인도네시아","zh-CN":"印度尼西亚","zh-TW":"印度尼西亞"}},"continent":{"code":"AS","name":{"nativeText":"Asia","texts":{"en-US":"Asia","ja-JP":"アジア","ko-KR":"아시아","zh-CN":"亚洲","zh-TW":"亞洲"}}},"defaultCurrency":"IDR","defaultLocale":"en-US","defaultLengthUnit":"CENTIMETER","defaultWeightUnit":"KILOGRAM"},{"code":"MY","name":{"nativeText":"Malaysia","texts":{"en-US":"Malaysia","ja-JP":"マレーシア","ko-KR":"말레이시아","zh-CN":"马来西亚","zh-TW":"馬來西亞"}},"continent":{"code":"AS","name":{"nativeText":"Asia","texts":{"en-US":"Asia","ja-JP":"アジア","ko-KR":"아시아","zh-CN":"亚洲","zh-TW":"亞洲"}}},"defaultCurrency":"MYR","defaultLocale":"en-US","defaultLengthUnit":"CENTIMETER","defaultWeightUnit":"KILOGRAM"},{"code":"NZ","name":{"nativeText":"New Zealand","texts":{"en-US":"New Zealand","ja-JP":"ニュージーランド","ko-KR":"뉴질랜드","zh-CN":"新西兰","zh-TW":"紐西蘭"}},"continent":{"code":"OC","name":{"nativeText":"Oceania","texts":{"en-US":"Oceania","ja-JP":"オセアニア","ko-KR":"오세아니아","zh-CN":"大洋洲","zh-TW":"大洋洲"}}},"defaultCurrency":"NZD","defaultLocale":"en-US","defaultLengthUnit":"INCH","defaultWeightUnit":"POUND"},{"code":"PH","name":{"nativeText":"Philippines","texts":{"en-US":"Philippines","ja-JP":"フィリピン","ko-KR":"필리핀","zh-CN":"菲律宾","zh-TW":"菲律賓"}},"continent":{"code":"AS","name":{"nativeText":"Asia","texts":{"en-US":"Asia","ja-JP":"アジア","ko-KR":"아시아","zh-CN":"亚洲","zh-TW":"亞洲"}}},"defaultCurrency":"PHP","defaultLocale":"en-US","defaultLengthUnit":"CENTIMETER","defaultWeightUnit":"KILOGRAM"},{"code":"SG","name":{"nativeText":"Singapore","texts":{"en-US":"Singapore","ja-JP":"シンガポール","ko-KR":"싱가포르","zh-CN":"新加坡","zh-TW":"新加坡"}},"continent":{"code":"AS","name":{"nativeText":"Asia","texts":{"en-US":"Asia","ja-JP":"アジア","ko-KR":"아시아","zh-CN":"亚洲","zh-TW":"亞洲"}}},"defaultCurrency":"SGD","defaultLocale":"en-US","defaultLengthUnit":"CENTIMETER","defaultWeightUnit":"KILOGRAM"},{"code":"TW","name":{"nativeText":"臺灣","texts":{"en-US":"Taiwan","ja-JP":"台湾","ko-KR":"대만","zh-CN":"台湾","zh-TW":"臺灣"}},"continent":{"code":"AS","name":{"nativeText":"Asia","texts":{"en-US":"Asia","ja-JP":"アジア","ko-KR":"아시아","zh-CN":"亚洲","zh-TW":"亞洲"}}},"defaultCurrency":"TWD","defaultLocale":"zh-TW","defaultLengthUnit":"CENTIMETER","defaultWeightUnit":"KILOGRAM"},{"code":"TH","name":{"nativeText":"Thailand","texts":{"en-US":"Thailand","ja-JP":"タイ","ko-KR":"태국","zh-CN":"泰国","zh-TW":"泰國"}},"continent":{"code":"AS","name":{"nativeText":"Asia","texts":{"en-US":"Asia","ja-JP":"アジア","ko-KR":"아시아","zh-CN":"亚洲","zh-TW":"亞洲"}}},"defaultCurrency":"THB","defaultLocale":"en-US","defaultLengthUnit":"CENTIMETER","defaultWeightUnit":"KILOGRAM"},{"code":"VN","name":{"nativeText":"Việt Nam","texts":{"en-US":"Vietnam","ja-JP":"ベトナム","ko-KR":"베트남","zh-CN":"越南","zh-TW":"越南"}},"continent":{"code":"AS","name":{"nativeText":"Asia","texts":{"en-US":"Asia","ja-JP":"アジア","ko-KR":"아시아","zh-CN":"亚洲","zh-TW":"亞洲"}}},"defaultCurrency":"VND","defaultLocale":"en-US","defaultLengthUnit":"CENTIMETER","defaultWeightUnit":"KILOGRAM"}],"currencies":[{"code":"KRW","symbol":"₩"},{"code":"JPY","symbol":"¥"},{"code":"USD","symbol":"US$"},{"code":"AUD","symbol":"A$"},{"code":"CAD","symbol":"CA$"},{"code":"HKD","symbol":"HK$"},{"code":"IDR","symbol":"Rp"},{"code":"MYR","symbol":"RM"},{"code":"NZD","symbol":"NZ$"},{"code":"PHP","symbol":"₱"},{"code":"SGD","symbol":"S$"},{"code":"TWD","symbol":"NT$"},{"code":"THB","symbol":"฿"},{"code":"VND","symbol":"₫"}],"locales":[{"code":"en-US","language":"en","country":"US","name":{"nativeText":"English","texts":{"en-US":"English","ja-JP":"英語","ko-KR":"영어","zh-CN":"英语","zh-TW":"英語"}}},{"code":"ko-KR","language":"ko","country":"KR","name":{"nativeText":"한국어","texts":{"en-US":"Korean","ja-JP":"韓国語","ko-KR":"한국어","zh-CN":"韩语","zh-TW":"韓語"}}},{"code":"ja-JP","language":"ja","country":"JP","name":{"nativeText":"日本語","texts":{"en-US":"Japanese","ja-JP":"日本語","ko-KR":"일본어","zh-CN":"日语","zh-TW":"日語"}}},{"code":"zh-CN","language":"zh","country":"CN","name":{"nativeText":"简体中文","texts":{"en-US":"Simplified Chinese","ja-JP":"簡体中国語","ko-KR":"중국어(간체)","zh-CN":"简体中文","zh-TW":"簡體中文"}}},{"code":"zh-TW","language":"zh","country":"TW","name":{"nativeText":"繁體中文","texts":{"en-US":"Traditional Chinese","ja-JP":"繁体中国語","ko-KR":"중국어(번체)","zh-CN":"繁体中文","zh-TW":"繁體中文"}}}],"continents":[{"code":"AS","name":{"nativeText":"Asia","texts":{"en-US":"Asia","ja-JP":"アジア","ko-KR":"아시아","zh-CN":"亚洲","zh-TW":"亞洲"}}},{"code":"NA","name":{"nativeText":"Americas","texts":{"en-US":"Americas","ja-JP":"アメリカ","ko-KR":"미주","zh-CN":"美洲","zh-TW":"美洲"}}},{"code":"OC","name":{"nativeText":"Oceania","texts":{"en-US":"Oceania","ja-JP":"オセアニア","ko-KR":"오세아니아","zh-CN":"大洋洲","zh-TW":"大洋洲"}}}]};</script><script data-nscript="beforeInteractive" id="mss-gtm">(function (w, d, s, l, i) {
                  w[l] = w[l] || [];
                  w[l].push({ 'gtm.start': new Date().getTime(), 'event': 'gtm.js' });
                  var f = d.getElementsByTagName(s)[0],
                    j = d.createElement(s),
                    dl = l != 'dataLayer' ? '&l=' + l : '';
                  j.async = true;
                  j.src = 'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
                  f.parentNode.insertBefore(j, f);

In [10]:
# class이 값이 특정 문자로 시작하는? 
# re.compile(r"^GoddsList__List")
div_tag = soup.find('div', class_=re.compile(r"^GoodsList__List"))

In [11]:
goods_row = div_tag.find_all('div', class_= re.compile(r"^GoodsList__Row"))

In [12]:
# goods_row에서 각각의 원소에서 sc-it로 시작하는 class 값을 가진 div 태그들을 모두 찾는다. 
goods_dict = []
for good_info in goods_row:
    info_data = good_info.find_all('div', class_=re.compile(r'^sc-it'))
    for data in info_data:
        # 상품의 정보를 저장할수 있는 딕셔너리형 데이터 초기값을 저장 
        info_dict = {}
        # info_dict에서 사용할 키 값들의 목록 생성 
        dict_keys = ['브랜드', '상품명', '할인율', '판매가격']
        # print( len(data.find_all('span')) )
        span_tags = data.find_all('span')
        for span, k in zip(span_tags, dict_keys):
            text = span.get_text()
            # info_dict에 데이터를 추가 
            info_dict[k] = text.strip()
            # print(info_dict)
        # 해당 상품의 하이퍼링크 주소 값을 info_dict에 추가 
        # data에서 a태그들을 찾아서 2번째 a 태그의 href 값을 추출
        link_url = data.find_all('a')[1]['href']
        info_dict['link'] = link_url
        # break
        # 3번째 반복문이 끝나고 만들어진 상품 정보 데이터를 goods_dict에 추가 
        goods_dict.append(info_dict)
    # break

In [13]:
goods_dict

[{'브랜드': '소버먼트',
  '상품명': '【건조기 가능】 3-Way 롤업 레이어드 소프트 티셔츠 [9 Color]',
  '할인율': '30%',
  '판매가격': '29,000원',
  'link': 'https://www.musinsa.com/products/6659876'},
 {'브랜드': '누아트 스튜디오',
  '상품명': '[송승일 PICK] 우먼 솔리드 반팔 티셔츠_4colors',
  '할인율': '41%',
  '판매가격': '18,500원',
  'link': 'https://www.musinsa.com/products/6433549'},
 {'브랜드': '이스케이프프롬',
  '상품명': '하트 포인트 ESCF 프린트 보트넥 슬림핏 반팔티 [4color]',
  '할인율': '29%',
  '판매가격': '36,900원',
  'link': 'https://www.musinsa.com/products/6612061'},
 {'브랜드': '엘엠알',
  '상품명': '[지현서 PICK] 도트 셔링 반팔 티셔츠 DARK GREY',
  '할인율': '20%',
  '판매가격': '39,100원',
  'link': 'https://www.musinsa.com/products/6453175'},
 {'브랜드': '그로우하이드',
  '상품명': '포헬 원오프 오버핏 레터링 반팔 티셔츠_브라운',
  '할인율': '69,000원',
  'link': 'https://www.musinsa.com/products/6581346'},
 {'브랜드': '페이드',
  '상품명': 'PD ase 슬림핏 반팔티 블랙',
  '할인율': '34%',
  '판매가격': '24,900원',
  'link': 'https://www.musinsa.com/products/6548127'},
 {'브랜드': '프리즘웍스',
  '상품명': 'ZANES BAIT & TACKLE RINGER TEE _ IVORY',
  '할인율': '10%',
  '판매가격': '40,500원',
  'link': 'https://www.musinsa.com/products/6490668'},
 {'브랜드': '일꼬르소',
  '상품명': 'CRS Sorona Cotton ARCHIVE 숏 슬리브 티셔츠 블랙',
  '할인율': '5%',
  '판매가격': '56,050원',
  'link': 'https://www.musinsa.com/products/6581788'},
 {'브랜드': '해비즘',
  '상품명': 'NAME CARD S/S TEE(PLUM)',
  '할인율': '10%',
  '판매가격': '37,800원',
  'link': 'https://www.musinsa.com/products/6579994'},
 {'브랜드': '엘엠알',
  '상품명': '[지현서 PICK] 투웨이 레이스 셔링 레이어드 반팔 티셔츠 IVORY / SKY BLUE',
  '할인율': '43%',
  '판매가격': '39,100원',
  'link': 'https://www.musinsa.com/products/6453251'},
 {'브랜드': '해칭룸',
  '상품명': 'Lines Tee Green',
  '할인율': '68,000원',
  'link': 'https://www.musinsa.com/products/6529480'},
 {'브랜드': '무센트',
  '상품명': '사하라 호피 십자가 백 로고 유넥 굴림 반팔 티 (2컬러)',
  '할인율': '40%',
  '판매가격': '29,900원',
  'link': 'https://www.musinsa.com/products/6552945'},
 {'브랜드': '할리데이비슨 컬렉션스®',
  '상품명': '할리 1903 레터링 링거티 _화이트 HH16111058',
  '할인율': '20%',
  '판매가격': '47,920원',
  'link': 'https://www.musinsa.com/products/6583505'},
 {'브랜드': '썸웨어버터',
  '상품명': 'Stitch Square Logo Top - Ivory',
  '할인율': '43,000원',
  'link': 'https://www.musinsa.com/products/6593664'},
 {'브랜드': '에스이에스티',
  '상품명': 'Crop Eyelet Cut-out T-shirts Dark Brown',
  '할인율': '31%',
  '판매가격': '34,000원',
  'link': 'https://www.musinsa.com/products/6565837'},
 {'브랜드': '토피',
  '상품명': '[2PACK] 슬림 크롭 헨리넥 하프 티셔츠',
  '할인율': '25%',
  '판매가격': '46,500원',
  'link': 'https://www.musinsa.com/products/6543526'},
 {'브랜드': '이스케이프프롬',
  '상품명': '[SET] 로즈 크로스 프린트 보트넥 슬림핏 반팔티 틸블루 & 슬리브리스',
  '할인율': '85,000원',
  'link': 'https://www.musinsa.com/products/6649569'},
 {'브랜드': '로파이',
  '상품명': '니코 스트라이프 크롭 티셔츠 (2PACK)',
  '할인율': '15%',
  '판매가격': '62,900원',
  'link': 'https://www.musinsa.com/products/6498017'},
 {'브랜드': '일리고',
  '상품명': '스트라이프 셔링 카라 티 버건디',
  '할인율': '9%',
  '판매가격': '82,000원',
  'link': 'https://www.musinsa.com/products/6455158'},
 {'브랜드': '디오스피스',
  '상품명': '(DUC) Dancer Baby Tee Mint',
  '할인율': '30%',
  '판매가격': '33,600원',
  'link': 'https://www.musinsa.com/products/6586076'},
 {'브랜드': '무한도전',
  '상품명': '무한상사 반팔',
  '할인율': '39,000원',
  'link': 'https://www.musinsa.com/products/6551491'},
 {'브랜드': '허그유어스킨',
  '상품명': '레이어드 헨리넥 탑 (네이비)',
  '할인율': '65,000원',
  'link': 'https://www.musinsa.com/products/6455164'},
 {'브랜드': '소버먼트',
  '상품명': '레귤러 크롭 체인 스티치 티셔츠[5 Color]',
  '할인율': '30%',
  '판매가격': '29,000원',
  'link': 'https://www.musinsa.com/products/6585898'},
 {'브랜드': '르아브',
  '상품명': '[젠플록스X르아브] [2PACK] 플록스 에어로쿨 크롭 티셔츠',
  '할인율': '45%',
  '판매가격': '44,000원',
  'link': 'https://www.musinsa.com/products/6448424'},
 {'브랜드': '카네이테이',
  '상품명': '[현킴 X KNT] PIG PARM CROP SHORT SLEEVE (PIGMENT CHARCOAL)',
  '할인율': '21%',
  '판매가격': '46,900원',
  'link': 'https://www.musinsa.com/products/6592529'},
 {'브랜드': '벤힛',
  '상품명': 'Heart Dream 슬림핏 반팔티',
  '할인율': '36%',
  '판매가격': '30,900원',
  'link': 'https://www.musinsa.com/products/6616076'},
 {'브랜드': '토아베',
  '상품명': 'Statement Floral T-Shirt (2 Color)',
  '할인율': '63,000원',
  'link': 'https://www.musinsa.com/products/6621658'},
 {'브랜드': '노이어 포 우먼',
  '상품명': '슬림 리브드 티셔츠 (페일옐로우)',
  '할인율': '22%',
  '판매가격': '35,190원',
  'link': 'https://www.musinsa.com/products/6535565'},
 {'브랜드': '무신사 스탠다드 우먼',
  '상품명': '우먼즈 트윈 걸즈 티셔츠 [다크 그레이]',
  '할인율': '40%',
  '판매가격': '23,940원',
  'link': 'https://www.musinsa.com/products/4943687'},
 {'브랜드': '이티씨이',
  '상품명': 'REBIRTH BAND T-SHIRT (BLACK)',
  '할인율': '75,000원',
  'link': 'https://www.musinsa.com/products/6416986'},
 {'브랜드': '썸웨어버터',
  '상품명': 'Stitch Square Logo Top - Cobalt Blue',
  '할인율': '43,000원',
  'link': 'https://www.musinsa.com/products/6593662'},
 {'브랜드': '카키포인트',
  '상품명': 'Muted Curve Top (black)',
  '할인율': '45,000원',
  'link': 'https://www.musinsa.com/products/6458464'},
 {'브랜드': '미드나잇 무브',
  '상품명': 'ss ex t (grey)',
  '할인율': '20%',
  '판매가격': '33,600원',
  'link': 'https://www.musinsa.com/products/6539160'},
 {'브랜드': '이스케이프프롬',
  '상품명': '[ESCF X 핫투데이] Heritage Horse 와플 헨리넥 반팔 티셔츠 그레이',
  '할인율': '21%',
  '판매가격': '49,900원',
  'link': 'https://www.musinsa.com/products/6530794'},
 {'브랜드': '아미',
  '상품명': '파리 로고패치 반소매 티셔츠 - 화이트 크림 / UTS075726136',
  '할인율': '59%',
  '판매가격': '153,990원',
  'link': 'https://www.musinsa.com/products/4866268'},
 {'브랜드': '스파오',
  '상품명': '[호빵맨] 세균맨 반팔 티셔츠(Black)_SPRLG37U31',
  '할인율': '29,900원',
  'link': 'https://www.musinsa.com/products/6478708'},
 {'브랜드': '탑텐',
  '상품명': '공용) 쿨에어 코튼 리젠 콜라보 반팔 티 (토비)_MSF2TS3007',
  '할인율': '40%',
  '판매가격': '17,900원',
  'link': 'https://www.musinsa.com/products/4860171'},
 {'브랜드': '피지컬 디파트먼트',
  '상품명': '우먼즈 스타 스프레이 반팔티셔츠_옐로우',
  '할인율': '59%',
  '판매가격': '19,900원',
  'link': 'https://www.musinsa.com/products/4990766'},
 {'브랜드': '플레어업',
  '상품명': '3-Layered Henley T-shirt (FL-151_Black)',
  '할인율': '79,000원',
  'link': 'https://www.musinsa.com/products/6535163'},
 {'브랜드': '디오스피스',
  '상품명': '(DUC) BB Layered One-Shoulder T-Shirt White',
  '할인율': '30%',
  '판매가격': '40,600원',
  'link': 'https://www.musinsa.com/products/6592259'},
 {'브랜드': '탑텐',
  '상품명': '공용) 컴팩트 코튼 콜라보 반팔티 (블랙 크로우스)_MSF2TS3004',
  '할인율': '40%',
  '판매가격': '17,900원',
  'link': 'https://www.musinsa.com/products/4739524'},
 {'브랜드': '토아베',
  '상품명': 'Chill Bio Strap Off-Shoulder T-Shirt (Tiffany blue)',
  '할인율': '68,000원',
  'link': 'https://www.musinsa.com/products/6619494'},
 {'브랜드': '언노운 플라넷',
  '상품명': '레이어드 디컨스트럭티드 슬림 티셔츠 챠콜',
  '할인율': '20%',
  '판매가격': '35,000원',
  'link': 'https://www.musinsa.com/products/6349754'},
 {'브랜드': '루나키후',
  '상품명': 'WXT099 쿠모 도마도 체크 아플리케 티셔츠 (WHITE)',
  '할인율': '10%',
  '판매가격': '44,100원',
  'link': 'https://www.musinsa.com/products/6507519'},
 {'브랜드': '플리즈노팔로우',
  '상품명': 'Mandy Lace Layered Short Sleeve Top (Baby Blue)',
  '할인율': '15%',
  '판매가격': '67,150원',
  'link': 'https://www.musinsa.com/products/6646014'},
 {'브랜드': '에스이에스티',
  '상품명': 'Crop Eyelet Cut-out T-shirts Charcoal',
  '할인율': '31%',
  '판매가격': '34,000원',
  'link': 'https://www.musinsa.com/products/6565796'},
 {'브랜드': '플레이스 스튜디오',
  '상품명': '빈티지 99 리벳 절개 피티드 세미크롭 소프트 보트넥 반팔 티셔츠_3COLOR',
  '할인율': '30%',
  '판매가격': '29,400원',
  'link': 'https://www.musinsa.com/products/6607333'},
 {'브랜드': '험머',
  '상품명': '[2PACK] 썸머 소로나 기능성 속건 쿨 반팔 티셔츠',
  '할인율': '64%',
  '판매가격': '25,800원',
  'link': 'https://www.musinsa.com/products/6543955'},
 {'브랜드': '제로',
  '상품명': '코어 배색 반팔 티셔츠 [블랙]',
  '할인율': '29,000원',
  'link': 'https://www.musinsa.com/products/6573863'},
 {'브랜드': '예스아이씨',
  '상품명': 'The Kidding Heads Frame Tee Red',
  '할인율': '65,000원',
  'link': 'https://www.musinsa.com/products/6615533'},
 {'브랜드': '언더오프',
  '상품명': '롤업 슬리브 크롭 반팔 티셔츠 지오그라피 버건디',
  '할인율': '21%',
  '판매가격': '29,900원',
  'link': 'https://www.musinsa.com/products/6622083'},
 {'브랜드': '마리끌레르',
  '상품명': '플라워 펀칭 레이어드 반팔 티셔츠(MAGBTS50MIV)',
  '할인율': '10%',
  '판매가격': '53,000원',
  'link': 'https://www.musinsa.com/products/6614889'},
 {'브랜드': '오오엠엘',
  '상품명': '피플 슬림 숏 슬리브 멜란지 그레이',
  '할인율': '20%',
  '판매가격': '29,520원',
  'link': 'https://www.musinsa.com/products/6508556'},
 {'브랜드': '오드스튜디오',
  '상품명': '[디지몬 어드벤처] Vamdemon, Gottsumon, and Pumpmon Overfit T-shirt - 3COLOR',
  '할인율': '10%',
  '판매가격': '37,800원',
  'link': 'https://www.musinsa.com/products/6546927'}]

In [14]:
# driver에서 화면 스크롤 이벤트
driver.execute_script(
    'window.scrollBy(0, 1600);'
)

In [15]:
df = pd.DataFrame(goods_dict)
df

,브랜드,상품명,할인율,판매가격,link
0,소버먼트,【건조기 가능】 3-Way 롤업 레이어드 소프트 티셔츠 [9 Color],30%,"29,000원",https://www.musinsa.com/products/6659876
1,누아트 스튜디오,[송승일 PICK] 우먼 솔리드 반팔 티셔츠_4colors,41%,"18,500원",https://www.musinsa.com/products/6433549
2,이스케이프프롬,하트 포인트 ESCF 프린트 보트넥 슬림핏 반팔티 [4color],29%,"36,900원",https://www.musinsa.com/products/6612061
3,엘엠알,[지현서 PICK] 도트 셔링 반팔 티셔츠 DARK GREY,20%,"39,100원",https://www.musinsa.com/products/6453175
4,그로우하이드,포헬 원오프 오버핏 레터링 반팔 티셔츠_브라운,"69,000원",NaN,https://www.musinsa.com/products/6581346
5,페이드,PD ase 슬림핏 반팔티 블랙,34%,"24,900원",https://www.musinsa.com/products/6548127
6,프리즘웍스,ZANES BAIT & TACKLE RINGER TEE _ IVORY,10%,"40,500원",https://www.musinsa.com/products/6490668
7,일꼬르소,CRS Sorona Cotton ARCHIVE 숏 슬리브 티셔츠 블랙,5%,"56,050원",https://www.musinsa.com/products/6581788
8,해비즘,NAME CARD S/S TEE(PLUM),10%,"37,800원",https://www.musinsa.com/products/6579994
9,엘엠알,[지현서 PICK] 투웨이 레이스 셔링 레이어드 반팔 티셔츠 IVORY / SKY ...,43%,"39,100원",https://www.musinsa.com/products/6453251
10,해칭룸,Lines Tee Green,"68,000원",NaN,https://www.musinsa.com/products/6529480
11,무센트,사하라 호피 십자가 백 로고 유넥 굴림 반팔 티 (2컬러),40%,"29,900원",https://www.musinsa.com/products/6552945
12,할리데이비슨 컬렉션스®,할리 1903 레터링 링거티 _화이트 HH16111058,20%,"47,920원",https://www.musinsa.com/products/6583505
13,썸웨어버터,Stitch Square Logo Top - Ivory,"43,000원",NaN,https://www.musinsa.com/products/6593664
14,에스이에스티,Crop Eyelet Cut-out T-shirts Dark Brown,31%,"34,000원",https://www.musinsa.com/products/6565837
15,토피,[2PACK] 슬림 크롭 헨리넥 하프 티셔츠,25%,"46,500원",https://www.musinsa.com/products/6543526
16,이스케이프프롬,[SET] 로즈 크로스 프린트 보트넥 슬림핏 반팔티 틸블루 & 슬리브리스,"85,000원",NaN,https://www.musinsa.com/products/6649569
17,로파이,니코 스트라이프 크롭 티셔츠 (2PACK),15%,"62,900원",https://www.musinsa.com/products/6498017
18,일리고,스트라이프 셔링 카라 티 버건디,9%,"82,000원",https://www.musinsa.com/products/6455158
19,디오스피스,(DUC) Dancer Baby Tee Mint,30%,"33,600원",https://www.musinsa.com/products/6586076
20,무한도전,무한상사 반팔,"39,000원",NaN,https://www.musinsa.com/products/6551491
21,허그유어스킨,레이어드 헨리넥 탑 (네이비),"65,000원",NaN,https://www.musinsa.com/products/6455164
22,소버먼트,레귤러 크롭 체인 스티치 티셔츠[5 Color],30%,"29,000원",https://www.musinsa.com/products/6585898
23,르아브,[젠플록스X르아브] [2PACK] 플록스 에어로쿨 크롭 티셔츠,45%,"44,000원",https://www.musinsa.com/products/6448424
24,카네이테이,[현킴 X KNT] PIG PARM CROP SHORT SLEEVE (PIGMENT...,21%,"46,900원",https://www.musinsa.com/products/6592529
25,벤힛,Heart Dream 슬림핏 반팔티,36%,"30,900원",https://www.musinsa.com/products/6616076
26,토아베,Statement Floral T-Shirt (2 Color),"63,000원",NaN,https://www.musinsa.com/products/6621658
27,노이어 포 우먼,슬림 리브드 티셔츠 (페일옐로우),22%,"35,190원",https://www.musinsa.com/products/6535565
28,무신사 스탠다드 우먼,우먼즈 트윈 걸즈 티셔츠 [다크 그레이],40%,"23,940원",https://www.musinsa.com/products/4943687
29,이티씨이,REBIRTH BAND T-SHIRT (BLACK),"75,000원",NaN,https://www.musinsa.com/products/6416986
30,썸웨어버터,Stitch Square Logo Top - Cobalt Blue,"43,000원",NaN,https://www.musinsa.com/products/6593662
31,카키포인트,Muted Curve Top (black),"45,000원",NaN,https://www.musinsa.com/products/6458464
32,미드나잇 무브,ss ex t (grey),20%,"33,600원",https://www.musinsa.com/products/6539160
33,이스케이프프롬,[ESCF X 핫투데이] Heritage Horse 와플 헨리넥 반팔 티셔츠 그레이,21%,"49,900원",https://www.musinsa.com/products/6530794
34,아미,파리 로고패치 반소매 티셔츠 - 화이트 크림 / UTS075726136,59%,"153,990원",https://www.musinsa.com/products/4866268
35,스파오,[호빵맨] 세균맨 반팔 티셔츠(Black)_SPRLG37U31,"29,900원",NaN,https://www.musinsa.com/products/6478708
36,탑텐,공용) 쿨에어 코튼 리젠 콜라보 반팔 티 (토비)_MSF2TS3007,40%,"17,900원",https://www.musinsa.com/products/4860171
37,피지컬 디파트먼트,우먼즈 스타 스프레이 반팔티셔츠_옐로우,59%,"19,900원",https://www.musinsa.com/products/4990766
38,플레어업,3-Layered Henley T-shirt (FL-151_Black),"79,000원",NaN,https://www.musinsa.com/products/6535163
39,디오스피스,(DUC) BB Layered One-Shoulder T-Shirt White,30%,"40,600원",https://www.musinsa.com/products/6592259
40,탑텐,공용) 컴팩트 코튼 콜라보 반팔티 (블랙 크로우스)_MSF2TS3004,40%,"17,900원",https://www.musinsa.com/products/4739524
41,토아베,Chill Bio Strap Off-Shoulder T-Shirt (Tiffany ...,"68,000원",NaN,https://www.musinsa.com/products/6619494
42,언노운 플라넷,레이어드 디컨스트럭티드 슬림 티셔츠 챠콜,20%,"35,000원",https://www.musinsa.com/products/6349754
43,루나키후,WXT099 쿠모 도마도 체크 아플리케 티셔츠 (WHITE),10%,"44,100원",https://www.musinsa.com/products/6507519
44,플리즈노팔로우,Mandy Lace Layered Short Sleeve Top (Baby Blue),15%,"67,150원",https://www.musinsa.com/products/6646014
45,에스이에스티,Crop Eyelet Cut-out T-shirts Charcoal,31%,"34,000원",https://www.musinsa.com/products/6565796
46,플레이스 스튜디오,빈티지 99 리벳 절개 피티드 세미크롭 소프트 보트넥 반팔 티셔츠_3COLOR,30%,"29,400원",https://www.musinsa.com/products/6607333
47,험머,[2PACK] 썸머 소로나 기능성 속건 쿨 반팔 티셔츠,64%,"25,800원",https://www.musinsa.com/products/6543955
48,제로,코어 배색 반팔 티셔츠 [블랙],"29,000원",NaN,https://www.musinsa.com/products/6573863
49,예스아이씨,The Kidding Heads Frame Tee Red,"65,000원",NaN,https://www.musinsa.com/products/6615533
50,언더오프,롤업 슬리브 크롭 반팔 티셔츠 지오그라피 버건디,21%,"29,900원",https://www.musinsa.com/products/6622083
51,마리끌레르,플라워 펀칭 레이어드 반팔 티셔츠(MAGBTS50MIV),10%,"53,000원",https://www.musinsa.com/products/6614889
52,오오엠엘,피플 슬림 숏 슬리브 멜란지 그레이,20%,"29,520원",https://www.musinsa.com/products/6508556
53,오드스튜디오,"[디지몬 어드벤처] Vamdemon, Gottsumon, and Pumpmon Ov...",10%,"37,800원",https://www.musinsa.com/products/6546927

In [16]:
print(df.columns)

Index(['브랜드', '상품명', '할인율', '판매가격', 'link'], dtype='str')

In [17]:
print(len(goods_row))  # 0이면 파싱 실패
print(df)

9
             브랜드                                                상품명      할인율  \
0           소버먼트           【건조기 가능】 3-Way 롤업 레이어드 소프트 티셔츠 [9 Color]      30%
1       누아트 스튜디오                   [송승일 PICK] 우먼 솔리드 반팔 티셔츠_4colors      41%
2        이스케이프프롬               하트 포인트 ESCF 프린트 보트넥 슬림핏 반팔티 [4color]      29%
3            엘엠알                  [지현서 PICK] 도트 셔링 반팔 티셔츠 DARK GREY      20%
4         그로우하이드                          포헬 원오프 오버핏 레터링 반팔 티셔츠_브라운  69,000원
5            페이드                                  PD ase 슬림핏 반팔티 블랙      34%
6          프리즘웍스             ZANES BAIT & TACKLE RINGER TEE _ IVORY      10%
7           일꼬르소             CRS Sorona Cotton ARCHIVE 숏 슬리브 티셔츠 블랙       5%
8            해비즘                            NAME CARD S/S TEE(PLUM)      10%
9            엘엠알  [지현서 PICK] 투웨이 레이스 셔링 레이어드 반팔 티셔츠 IVORY / SKY ...      43%
10           해칭룸                                    Lines Tee Green  68,000원
11           무센트                   사하라 호피 십자가 백 로고 유넥 굴림 반팔 티 (2컬러)      40%
12  할리데이비슨 컬렉션스®                    할리 1903 레터링 링거티 _화이트 HH16111058      20%
13         썸웨어버터                     Stitch Square Logo Top - Ivory  43,000원
14        에스이에스티            Crop Eyelet Cut-out T-shirts Dark Brown      31%
15            토피                           [2PACK] 슬림 크롭 헨리넥 하프 티셔츠      25%
16       이스케이프프롬           [SET] 로즈 크로스 프린트 보트넥 슬림핏 반팔티 틸블루 & 슬리브리스  85,000원
17           로파이                            니코 스트라이프 크롭 티셔츠 (2PACK)      15%
18           일리고                                  스트라이프 셔링 카라 티 버건디       9%
19         디오스피스                         (DUC) Dancer Baby Tee Mint      30%
20          무한도전                                            무한상사 반팔  39,000원
21        허그유어스킨                                   레이어드 헨리넥 탑 (네이비)  65,000원
22          소버먼트                         레귤러 크롭 체인 스티치 티셔츠[5 Color]      30%
23           르아브                 [젠플록스X르아브] [2PACK] 플록스 에어로쿨 크롭 티셔츠      45%
24         카네이테이  [현킴 X KNT] PIG PARM CROP SHORT SLEEVE (PIGMENT...      21%
25            벤힛                                Heart Dream 슬림핏 반팔티      36%
26           토아베                 Statement Floral T-Shirt (2 Color)  63,000원
27      노이어 포 우먼                                 슬림 리브드 티셔츠 (페일옐로우)      22%
28   무신사 스탠다드 우먼                             우먼즈 트윈 걸즈 티셔츠 [다크 그레이]      40%
29          이티씨이                       REBIRTH BAND T-SHIRT (BLACK)  75,000원
30         썸웨어버터               Stitch Square Logo Top - Cobalt Blue  43,000원
31         카키포인트                            Muted Curve Top (black)  45,000원
32       미드나잇 무브                                     ss ex t (grey)      20%
33       이스케이프프롬     [ESCF X 핫투데이] Heritage Horse 와플 헨리넥 반팔 티셔츠 그레이      21%
34            아미            파리 로고패치 반소매 티셔츠 - 화이트 크림 / UTS075726136      59%
35           스파오                 [호빵맨] 세균맨 반팔 티셔츠(Black)_SPRLG37U31  29,900원
36            탑텐             공용) 쿨에어 코튼 리젠 콜라보 반팔 티 (토비)_MSF2TS3007      40%
37     피지컬 디파트먼트                              우먼즈 스타 스프레이 반팔티셔츠_옐로우      59%
38          플레어업            3-Layered Henley T-shirt (FL-151_Black)  79,000원
39         디오스피스        (DUC) BB Layered One-Shoulder T-Shirt White      30%
40            탑텐            공용) 컴팩트 코튼 콜라보 반팔티 (블랙 크로우스)_MSF2TS3004      40%
41           토아베  Chill Bio Strap Off-Shoulder T-Shirt (Tiffany ...  68,000원
42       언노운 플라넷                             레이어드 디컨스트럭티드 슬림 티셔츠 챠콜      20%
43          루나키후                  WXT099 쿠모 도마도 체크 아플리케 티셔츠 (WHITE)      10%
44       플리즈노팔로우    Mandy Lace Layered Short Sleeve Top (Baby Blue)      15%
45        에스이에스티              Crop Eyelet Cut-out T-shirts Charcoal      31%
46     플레이스 스튜디오        빈티지 99 리벳 절개 피티드 세미크롭 소프트 보트넥 반팔 티셔츠_3COLOR      30%
47            험머                     [2PACK] 썸머 소로나 기능성 속건 쿨 반팔 티셔츠      64%
48            제로                                  코어 배색 반팔 티셔츠 [블랙]  29,000원
49         예스아이씨                    The Kidding Heads Frame Tee Red  65,000원
50          언더오프                         롤업 슬리브 크롭 반팔 티셔츠 지오그라피 버건디      21%
51         마리끌레르                    플라워 펀칭 레이어드 반팔 티셔츠(MAGBTS50MIV)      10%
52          오오엠엘                                피플 슬림 숏 슬리브 멜란지 그레이      20%
53        오드스튜디오  [디지몬 어드벤처] Vamdemon, Gottsumon, and Pumpmon Ov...      10%

        판매가격                                      link
0    29,000원  https://www.musinsa.com/products/6659876
1    18,500원  https://www.musinsa.com/products/6433549
2    36,900원  https://www.musinsa.com/products/6612061
3    39,100원  https://www.musinsa.com/products/6453175
4        NaN  https://www.musinsa.com/products/6581346
5    24,900원  https://www.musinsa.com/products/6548127
6    40,500원  https://www.musinsa.com/products/6490668
7    56,050원  https://www.musinsa.com/products/6581788
8    37,800원  https://www.musinsa.com/products/6579994
9    39,100원  https://www.musinsa.com/products/6453251
10       NaN  https://www.musinsa.com/products/6529480
11   29,900원  https://www.musinsa.com/products/6552945
12   47,920원  https://www.musinsa.com/products/6583505
13       NaN  https://www.musinsa.com/products/6593664
14   34,000원  https://www.musinsa.com/products/6565837
15   46,500원  https://www.musinsa.com/products/6543526
16       NaN  https://www.musinsa.com/products/6649569
17   62,900원  https://www.musinsa.com/products/6498017
18   82,000원  https://www.musinsa.com/products/6455158
19   33,600원  https://www.musinsa.com/products/6586076
20       NaN  https://www.musinsa.com/products/6551491
21       NaN  https://www.musinsa.com/products/6455164
22   29,000원  https://www.musinsa.com/products/6585898
23   44,000원  https://www.musinsa.com/products/6448424
24   46,900원  https://www.musinsa.com/products/6592529
25   30,900원  https://www.musinsa.com/products/6616076
26       NaN  https://www.musinsa.com/products/6621658
27   35,190원  https://www.musinsa.com/products/6535565
28   23,940원  https://www.musinsa.com/products/4943687
29       NaN  https://www.musinsa.com/products/6416986
30       NaN  https://www.musinsa.com/products/6593662
31       NaN  https://www.musinsa.com/products/6458464
32   33,600원  https://www.musinsa.com/products/6539160
33   49,900원  https://www.musinsa.com/products/6530794
34  153,990원  https://www.musinsa.com/products/4866268
35       NaN  https://www.musinsa.com/products/6478708
36   17,900원  https://www.musinsa.com/products/4860171
37   19,900원  https://www.musinsa.com/products/4990766
38       NaN  https://www.musinsa.com/products/6535163
39   40,600원  https://www.musinsa.com/products/6592259
40   17,900원  https://www.musinsa.com/products/4739524
41       NaN  https://www.musinsa.com/products/6619494
42   35,000원  https://www.musinsa.com/products/6349754
43   44,100원  https://www.musinsa.com/products/6507519
44   67,150원  https://www.musinsa.com/products/6646014
45   34,000원  https://www.musinsa.com/products/6565796
46   29,400원  https://www.musinsa.com/products/6607333
47   25,800원  https://www.musinsa.com/products/6543955
48       NaN  https://www.musinsa.com/products/6573863
49       NaN  https://www.musinsa.com/products/6615533
50   29,900원  https://www.musinsa.com/products/6622083
51   53,000원  https://www.musinsa.com/products/6614889
52   29,520원  https://www.musinsa.com/products/6508556
53   37,800원  https://www.musinsa.com/products/6546927

In [18]:
link_list = df['link'].tolist()
name_list = df['상품명'].tolist()
link_list[0]

'https://www.musinsa.com/products/6659876'

In [26]:
driver = webdriver.Chrome()

In [27]:
driver.get(link_list[0])

In [28]:
time.sleep(3)   # ← 추가 (페이지 로딩 대기)

In [29]:
# 스크롤을 마지막까지 내린다.
driver.execute_script(
    'window.scrollBy(0, document.body.scrollHeight);'
)

In [30]:
soup2 = bs(driver.page_source,'html.parser')

In [31]:
# GoodReviewListSection로 시작하는 class 값을 가진 div 태그를 선택
reviews_tag = soup2.find('div', class_=re.compile(f'GoodsReviewListSection'))
reviews_tag

<div class="GoodsReviewListSection__Container-sc-hmqz8q-0"><div class="GoodsReviewFilterTabSection__ScrollAnchor-sc-yqbv7s-0"></div><div class="GoodsReviewTabGroup__Container-sc-1mdjrqg-0 ffSVcu"><div class="flex w-full scrollbar-hide overflow-x-scroll GoodsReviewTabGroup__TabGroup-sc-1mdjrqg-1 zLJqW" data-mds="TabFixed"><div class="GoodsReviewTabGroup__TabItemWrapper-sc-1mdjrqg-3 CiRGj gtm-click-button" data-applied-tab="(not set)" data-brand-id="(not set)" data-button-id="전체" data-button-name="전체" data-index="(not set)" data-section-index="42" data-section-name="review_tab" data-selected="true" data-testid="goods-review-tab-전체"><span class="px-4 py-2 cursor-pointer bg-white text-black text-[14px] leading-[20px] tracking-[0] font-[600] lang-ja-JP:text-[13px] lang-zh-CN:text-[13px] lang-zh-TW:text-[13px] GoodsReviewTabGroup__TabItem-sc-1mdjrqg-2 hNLXRf" data-mds="TabFixedItem"><span class="relative" data-mds="TabFixedItem"><span class="text-[13px] leading-[18px] tracking-[0] font-[600] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] text-black font-global" data-mds="Typography">전체</span><span class="text-[11px] leading-[14px] tracking-[0] font-[400] lang-ja-JP:text-[10px] lang-zh-CN:text-[10px] lang-zh-TW:text-[10px] text-black font-global" data-mds="Typography">8</span></span></span><div class="GoodsReviewTabGroup__HiddenDivider-sc-1mdjrqg-5 dKvLvc"></div></div><div class="GoodsReviewTabGroup__TabItemWrapper-sc-1mdjrqg-3 CiRGj gtm-click-button" data-applied-tab="(not set)" data-brand-id="(not set)" data-button-id="스타일" data-button-name="스타일" data-index="(not set)" data-section-index="42" data-section-name="review_tab" data-selected="false" data-testid="goods-review-tab-스타일"><span class="px-4 py-2 cursor-pointer bg-gray-200 text-gray-500 text-[14px] leading-[20px] tracking-[0] font-[400] lang-ja-JP:text-[13px] lang-zh-CN:text-[13px] lang-zh-TW:text-[13px] GoodsReviewTabGroup__TabItem-sc-1mdjrqg-2 hNLXRf" data-mds="TabFixedItem"><span class="relative" data-mds="TabFixedItem"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] text-gray-500 font-global" data-mds="Typography">스타일</span><span class="text-[11px] leading-[14px] tracking-[0] font-[400] lang-ja-JP:text-[10px] lang-zh-CN:text-[10px] lang-zh-TW:text-[10px] text-gray-500 font-global" data-mds="Typography">2</span></span></span><div class="GoodsReviewTabGroup__Divider-sc-1mdjrqg-4 hErfCV"></div></div><div class="GoodsReviewTabGroup__TabItemWrapper-sc-1mdjrqg-3 CiRGj gtm-click-button" data-applied-tab="(not set)" data-brand-id="(not set)" data-button-id="일반" data-button-name="일반" data-index="(not set)" data-section-index="42" data-section-name="review_tab" data-selected="false" data-testid="goods-review-tab-일반"><span class="px-4 py-2 cursor-pointer bg-gray-200 text-gray-500 text-[14px] leading-[20px] tracking-[0] font-[400] lang-ja-JP:text-[13px] lang-zh-CN:text-[13px] lang-zh-TW:text-[13px] GoodsReviewTabGroup__TabItem-sc-1mdjrqg-2 hNLXRf" data-mds="TabFixedItem"><span class="relative" data-mds="TabFixedItem"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] text-gray-500 font-global" data-mds="Typography">일반</span><span class="text-[11px] leading-[14px] tracking-[0] font-[400] lang-ja-JP:text-[10px] lang-zh-CN:text-[10px] lang-zh-TW:text-[10px] text-gray-500 font-global" data-mds="Typography">6</span></span></span></div></div></div><div class="GoodsReviewFilterTabSection__FilterContainer-sc-yqbv7s-1 AhQKU"><div class="GoodsReviewFilterGroupSection__Container-sc-w46hs7-0 dmqFWX"><div class="inline-flex relative border border-solid rounded cursor-pointer justify-center items-center whitespace-nowrap p-[7px] bg-transparent text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] text-gray-600 border-gray-300" data-mds="FilterOutlinedItem"><button class="inline-flex items-center justify-center group-data-[disabled]:cursor-not-allowed focus:outline-none size-4" data-mds="IconButton"><svg class="" data-mds="IcFilter" fill="none" height="100%" viewbox="0 0 20 20" width="100%" xmlns="http://www.w3.org/2000/svg"><path class="stroke-black" d="M3 10H7M9.5 10H17M3 5H10.5M13 5H17M13 3V7M7 8V12M3 15H7M9.5 15H17M10 13V17" data-mds="IcFilter" vector-effect="non-scaling-stroke"></path></svg></button></div><div class="GoodsReviewFilterGroupSection__FilterButtonGroup-sc-w46hs7-1 cKZPao"><div class="inline-flex relative py-1.5 border border-solid rounded cursor-pointer justify-center items-center whitespace-nowrap px-1.5 bg-transparent text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] text-gray-600 border-gray-300 FilterTextButton__FilterOutlinedItem-sc-1yevciv-0 hyUBWN gtm-click-button" data-applied-tab="(not set)" data-brand-id="(not set)" data-button-id="(not set)" data-button-name="(not set)" data-filter-type="filter_click" data-filter-value="남" data-index="(not set)" data-mds="FilterOutlinedItem" data-section-index="28" data-section-name="filter_1" data-section-title="(not set)">남</div><div class="inline-flex relative py-1.5 border border-solid rounded cursor-pointer justify-center items-center whitespace-nowrap px-1.5 bg-transparent text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] text-gray-600 border-gray-300 FilterTextButton__FilterOutlinedItem-sc-1yevciv-0 hyUBWN gtm-click-button" data-applied-tab="(not set)" data-brand-id="(not set)" data-button-id="(not set)" data-button-name="(not set)" data-filter-type="filter_click" data-filter-value="여" data-index="(not set)" data-mds="FilterOutlinedItem" data-section-index="28" data-section-name="filter_1" data-section-title="(not set)">여</div><div class="inline-flex relative py-1.5 border border-solid rounded cursor-pointer justify-center items-center whitespace-nowrap pr-1 pl-1.5 bg-transparent text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] text-gray-600 border-gray-300 gtm-click-button" data-applied-tab="(not set)" data-brand-id="(not set)" data-button-id="(not set)" data-button-name="(not set)" data-filter-type="filter_click" data-filter-value="옵션" data-index="(not set)" data-mds="FilterOutlinedItem" data-section-index="28" data-section-name="filter_1" data-section-title="(not set)" data-testid="filter-button-option">옵션<span class="inline-flex items-center justify-center group-data-[disabled]:cursor-not-allowed focus:outline-none size-3 ml-0.5" data-mds="FilterOutlinedItemIconButton"><svg class="stroke-black" data-mds="IcArrowDown" fill="none" height="100%" viewbox="0 0 20 20" width="100%" xmlns="http://www.w3.org/2000/svg"><path class="stroke-current" d="M4 8L9.78787 13.7879C9.90503 13.905 10.095 13.905 10.2121 13.7879L16 8" data-mds="IcArrowDown" vector-effect="non-scaling-stroke"></path></svg></span></div><div data-mds="TooltipTrigger"><div class="inline-flex relative py-1.5 border border-solid rounded cursor-pointer justify-center items-center whitespace-nowrap pr-1 pl-1.5 bg-transparent text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] text-gray-600 border-gray-300 gtm-click-button" data-applied-tab="(not set)" data-brand-id="(not set)" data-button-id="(not set)" data-button-name="(not set)" data-filter-type="filter_click" data-filter-value="키/몸무게" data-index="(not set)" data-mds="FilterOutlinedItem" data-section-index="28" data-section-name="filter_1" data-section-title="(not set)" data-testid="filter-button-weightAndHeight">키/몸무게<span class="inline-flex items-center justify-center group-data-[disabled]:cursor-not-allowed focus:outline-none size-3 ml-0.5" data-mds="FilterOutlinedItemIconButton"><svg class="stroke-black" data-mds="IcArrowDown" fill="none" height="100%" viewbox="0 0 20 20" width="100%" xmlns="http://www.w3.org/2000/svg"><path class="stroke-current" d="M4 8L9.78787 13.7879C9.90503 13.905 10.095 13.905 10.2121 13.7879L16 8" data-mds="IcArrowDown" vector-effect="non-scaling-stroke"></path></svg></span></div></div></div></div></div><div class="GoodsReviewSortingSelectSection__Container-sc-6m9lz3-0 dCxuJD"><div class="GoodsReviewSortingSelectSection__SwitchGroup-sc-6m9lz3-1 dWizsg"><div class="PhotoReviewFilterSwitch__Container-sc-1iju8o3-0 cmIWZx gtm-click-button" data-applied-tab="(not set)" data-brand-id="(not set)" data-button-id="photo_filter" data-button-name="사진후기만" data-filter-type="filter_toggle" data-filter-value="사진후기만" data-index="(not set)" data-section-index="30" data-section-name="filter_2"><button aria-checked="false" class="peer inline-flex shrink-0 cursor-pointer items-center rounded-full border-0 border-transparent transition-colors focus:ring-0 focus-visible:outline-none disabled:cursor-not-allowed disabled:data-[state=unchecked]:bg-gray-200 disabled:data-[state=checked]:bg-gray-400 data-[state=checked]:bg-black data-[state=unchecked]:bg-gray-400 w-6 h-4" data-mds="Switch" data-state="unchecked" id="photo-review-filter-switch" role="switch" type="button" value="on"><span class="pointer-events-none block rounded-full bg-white ring-0 transition-transform data-[disabled]:data-[state=unchecked]:bg-gray-100 data-[disabled]:data-[state=checked]:bg-gray-200 size-3 data-[state=checked]:translate-x-2.5 data-[state=unchecked]:translate-x-0.5" data-mds="Switch" data-state="unchecked"></span></button><label class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] text-nowrap disabled:text-gray-400 peer-disabled:text-gray-400 peer-disabled:cursor-not-allowed group-data-[disabled]:text-gray-400 peer-data-[state=checked]:text-black peer-data-[state=unchecked]:text-gray-600 peer-data-[state=unchecked]:peer-disabled:text-gray-400 peer-data-[state=checked]:peer-disabled:text-gray-600 peer-[[role=switch]]:text-gray-600 peer-[[role=switch]]:peer-data-[state=checked]:text-black peer-[[role=switch]]:peer-data-[state=unchecked]:peer-disabled:text-gray-400 peer-[[role=switch]]:peer-data-[state=checked]:peer-disabled:text-gray-600" data-mds="TextLabel" for="photo-review-filter-switch">사진후기만</label></div><div class="MyProfileFilterSwitch__Container-sc-1vlbhkh-0 dZYqoJ gtm-click-button" data-applied-tab="(not set)" data-brand-id="(not set)" data-button-id="(not set)" data-button-name="(not set)" data-filter-type="filter_toggle" data-filter-value="내 사이즈" data-index="(not set)" data-section-index="30" data-section-name="filter_2"><button aria-checked="false" class="peer inline-flex shrink-0 cursor-pointer items-center rounded-full border-0 border-transparent transition-colors focus:ring-0 focus-visible:outline-none disabled:cursor-not-allowed disabled:data-[state=unchecked]:bg-gray-200 disabled:data-[state=checked]:bg-gray-400 data-[state=checked]:bg-black data-[state=unchecked]:bg-gray-400 w-6 h-4" data-mds="Switch" data-state="unchecked" id="my-profile-filter-switch" role="switch" type="button" value="on"><span class="pointer-events-none block rounded-full bg-white ring-0 transition-transform data-[disabled]:data-[state=unchecked]:bg-gray-100 data-[disabled]:data-[state=checked]:bg-gray-200 size-3 data-[state=checked]:translate-x-2.5 data-[state=unchecked]:translate-x-0.5" data-mds="Switch" data-state="unchecked"></span></button><label class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] text-nowrap disabled:text-gray-400 peer-disabled:text-gray-400 peer-disabled:cursor-not-allowed group-data-[disabled]:text-gray-400 peer-data-[state=checked]:text-black peer-data-[state=unchecked]:text-gray-600 peer-data-[state=unchecked]:peer-disabled:text-gray-400 peer-data-[state=checked]:peer-disabled:text-gray-600 peer-[[role=switch]]:text-gray-600 peer-[[role=switch]]:peer-data-[state=checked]:text-black peer-[[role=switch]]:peer-data-[state=unchecked]:peer-disabled:text-gray-400 peer-[[role=switch]]:peer-data-[state=checked]:peer-disabled:text-gray-600" data-mds="TextLabel" for="my-profile-filter-switch">내 사이즈</label></div></div><div class="ReviewSortSelectMenu__Wrapper-sc-qnt3uy-0 irVipI"><div class="relative block focus:outline-none" data-mds="Menu" tabindex="0"><div class="ReviewSortSelectMenu__TriggerContainer-sc-qnt3uy-1 joRHDT gtm-click-button" data-applied-tab="(not set)" data-brand-id="(not set)" data-button-id="(not set)" data-button-name="(not set)" data-filter-type="array_click" data-index="(not set)" data-section-index="30" data-section-name="filter_2"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] text-gray-600 font-global" data-mds="Typography">유용한순</span><div class="ReviewSortSelectMenu__IconWrapper-sc-qnt3uy-3 gkCWIn"><svg class="stroke-black" data-mds="IcArrowDown" fill="none" height="100%" viewbox="0 0 20 20" width="100%" xmlns="http://www.w3.org/2000/svg"><path class="stroke-gray-600" d="M4 8L9.78787 13.7879C9.90503 13.905 10.095 13.905 10.2121 13.7879L16 8" data-mds="IcArrowDown" vector-effect="non-scaling-stroke"></path></svg></div></div></div></div></div><div class="w-full h-[1px] bg-gray-500 bg-opacity-10 GoodsReviewFilterTabSection__Divider-sc-yqbv7s-2 ftNpax" data-mds="Divider"></div><div class="FilteredCount__Container-sc-zfxuj0-0 euntKg"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] text-gray-600 font-global" data-mds="Typography">8개</span></div><div class="GoodsReviewStaticList__Container-sc-shsfhc-0 dMfyOo"><div class="review-list-item__Container-sc-5kl1h0-0 fRTfcZ gtm-impression-content" data-brand-id="(not set)" data-content-id="85707792" data-content-name="후기리스트노출" data-index="(not set)" data-section-index="31" data-section-name="review"><div class="UserProfileSection__Container-sc-1r0zvbw-0 eDpSej"><a class="UserProfileSection__ProfileContainer-sc-1r0zvbw-1 bmkziF gtm-click-button" data-applied-tab="(not set)" data-brand-id="(not set)" data-button-id="review_profile" data-button-name="후기유저" data-index="(not set)" data-section-index="31" data-section-name="review" href="https://www.musinsa.com/review/user/741427262e4ab83d3a648928f4d9abdd" rel="noreferrer noopener" target="_blank"><div class="inline-flex items-center justify-center relative z-5 rounded-full before:border before:rounded-full before:border-solid before:absolute before:inset-0 before:size-full before:z-6 size-7 before:border-black before:opacity-[8%] Avatar__Container-sc-16lzyqb-0 eIlxre" data-mds="ImageCircleItem"><div class="relative z-5 inline-flex items-center justify-center w-full h-full before:absolute before:inset-0 before:size-full before:z-5 before:overflow-hidden before:bg-transparent overflow-hidden rounded-full" data-mds="Image"><img aria-hidden="true" class="max-w-full w-full absolute m-auto inset-0 h-auto z-0 visible object-contain" data-mds="Image" src="https://image.msscdn.net/thumbnails/mfile_s01/_simbols/_basic/basic.png?w=96"/></div></div><div class="UserProfileSection__Info-sc-1r0zvbw-2 CzBZn"><div class="UserProfileSection__FirstInfo-sc-1r0zvbw-3 gHYKrw"><span class="text-[13px] leading-[18px] tracking-[0] font-[500] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] UserProfileSection__Nickname-sc-1r0zvbw-4 dLijoq text-black font-global" data-mds="Typography" title="돈줘할인해줘">돈줘할인해줘</span><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] UserProfileSection__PurchaseDate-sc-1r0zvbw-5 hdhicz text-gray-500 font-global" data-mds="Typography">1일 전</span></div><div class="StarsScore__Container-sc-6zijmn-0 hmssOX"><div class="StarsScore__StarGroup-sc-6zijmn-1 kJFsxf"><svg class="" data-mds="IcStar" fill="none" height="100%" viewbox="0 0 20 20" width="12" xmlns="http://www.w3.org/2000/svg"><path class="fill-yellow" d="M10.2707 1.06689C10.162 0.839265 9.83799 0.839265 9.72928 1.06689L7.16594 6.43467C7.12297 6.52464 7.03812 6.58739 6.9395 6.60211L1.0893 7.4751C0.84556 7.51147 0.747211 7.80993 0.921583 7.98408L5.14053 12.1976C5.20921 12.2662 5.24046 12.3638 5.2244 12.4595L4.22835 18.3961C4.18708 18.6422 4.44661 18.8281 4.6663 18.71L9.85791 15.9182C9.94663 15.8705 10.0534 15.8705 10.1421 15.9182L15.3337 18.71C15.5534 18.8281 15.8129 18.6422 15.7716 18.3961L14.7756 12.4597C14.7595 12.3639 14.7909 12.2662 14.8596 12.1976L19.0783 7.99024C19.2527 7.81625 19.1547 7.51776 18.911 7.48116L13.0603 6.60223C12.9618 6.58744 12.8771 6.52472 12.8341 6.43484L10.2707 1.06689Z" data-mds="IcStar" vector-effect="non-scaling-stroke"></path></svg><svg class="" data-mds="IcStar" fill="none" height="100%" viewbox="0 0 20 20" width="12" xmlns="http://www.w3.org/2000/svg"><path class="fill-yellow" d="M10.2707 1.06689C10.162 0.839265 9.83799 0.839265 9.72928 1.06689L7.16594 6.43467C7.12297 6.52464 7.03812 6.58739 6.9395 6.60211L1.0893 7.4751C0.84556 7.51147 0.747211 7.80993 0.921583 7.98408L5.14053 12.1976C5.20921 12.2662 5.24046 12.3638 5.2244 12.4595L4.22835 18.3961C4.18708 18.6422 4.44661 18.8281 4.6663 18.71L9.85791 15.9182C9.94663 15.8705 10.0534 15.8705 10.1421 15.9182L15.3337 18.71C15.5534 18.8281 15.8129 18.6422 15.7716 18.3961L14.7756 12.4597C14.7595 12.3639 14.7909 12.2662 14.8596 12.1976L19.0783 7.99024C19.2527 7.81625 19.1547 7.51776 18.911 7.48116L13.0603 6.60223C12.9618 6.58744 12.8771 6.52472 12.8341 6.43484L10.2707 1.06689Z" data-mds="IcStar" vector-effect="non-scaling-stroke"></path></svg><svg class="" data-mds="IcStar" fill="none" height="100%" viewbox="0 0 20 20" width="12" xmlns="http://www.w3.org/2000/svg"><path class="fill-yellow" d="M10.2707 1.06689C10.162 0.839265 9.83799 0.839265 9.72928 1.06689L7.16594 6.43467C7.12297 6.52464 7.03812 6.58739 6.9395 6.60211L1.0893 7.4751C0.84556 7.51147 0.747211 7.80993 0.921583 7.98408L5.14053 12.1976C5.20921 12.2662 5.24046 12.3638 5.2244 12.4595L4.22835 18.3961C4.18708 18.6422 4.44661 18.8281 4.6663 18.71L9.85791 15.9182C9.94663 15.8705 10.0534 15.8705 10.1421 15.9182L15.3337 18.71C15.5534 18.8281 15.8129 18.6422 15.7716 18.3961L14.7756 12.4597C14.7595 12.3639 14.7909 12.2662 14.8596 12.1976L19.0783 7.99024C19.2527 7.81625 19.1547 7.51776 18.911 7.48116L13.0603 6.60223C12.9618 6.58744 12.8771 6.52472 12.8341 6.43484L10.2707 1.06689Z" data-mds="IcStar" vector-effect="non-scaling-stroke"></path></svg><svg class="" data-mds="IcStar" fill="none" height="100%" viewbox="0 0 20 20" width="12" xmlns="http://www.w3.org/2000/svg"><path class="fill-yellow" d="M10.2707 1.06689C10.162 0.839265 9.83799 0.839265 9.72928 1.06689L7.16594 6.43467C7.12297 6.52464 7.03812 6.58739 6.9395 6.60211L1.0893 7.4751C0.84556 7.51147 0.747211 7.80993 0.921583 7.98408L5.14053 12.1976C5.20921 12.2662 5.24046 12.3638 5.2244 12.4595L4.22835 18.3961C4.18708 18.6422 4.44661 18.8281 4.6663 18.71L9.85791 15.9182C9.94663 15.8705 10.0534 15.8705 10.1421 15.9182L15.3337 18.71C15.5534 18.8281 15.8129 18.6422 15.7716 18.3961L14.7756 12.4597C14.7595 12.3639 14.7909 12.2662 14.8596 12.1976L19.0783 7.99024C19.2527 7.81625 19.1547 7.51776 18.911 7.48116L13.0603 6.60223C12.9618 6.58744 12.8771 6.52472 12.8341 6.43484L10.2707 1.06689Z" data-mds="IcStar" vector-effect="non-scaling-stroke"></path></svg><svg class="" data-mds="IcStar" fill="none" height="100%" viewbox="0 0 20 20" width="12" xmlns="http://www.w3.org/2000/svg"><path class="fill-yellow" d="M10.2707 1.06689C10.162 0.839265 9.83799 0.839265 9.72928 1.06689L7.16594 6.43467C7.12297 6.52464 7.03812 6.58739 6.9395 6.60211L1.0893 7.4751C0.84556 7.51147 0.747211 7.80993 0.921583 7.98408L5.14053 12.1976C5.20921 12.2662 5.24046 12.3638 5.2244 12.4595L4.22835 18.3961C4.18708 18.6422 4.44661 18.8281 4.6663 18.71L9.85791 15.9182C9.94663 15.8705 10.0534 15.

In [32]:
# ExpandableContent로 시작하는 class 값을 가진 div 태그를 모두 찾는다
review_tags = reviews_tag.find_all('div', class_ = re.compile(r'^ExpandableContent'))
review_tags

[<div class="ExpandableContent__Container-sc-8yrutl-0 iuidVu gtm-click-button" data-applied-tab="(not set)" data-brand-id="(not set)" data-button-id="review_content" data-button-name="후기내용" data-index="(not set)" data-section-index="31" data-section-name="review"><div class="ExpandableContent__ContentContainer-sc-8yrutl-1 gvkPRD"><div style="max-height: 63px; overflow: hidden; white-space: pre-line;"></div><div style="white-space: pre-line;"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] w-full text-black font-global" data-mds="Typography">여름에 입기 좋은 두께감에 소재도 시원해서 너무 좋아용</span></div><div aria-hidden="true" class="Truncate__MeasureContainer-sc-1gm444l-0 ljgstB" style="max-width: 664.656px;"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] w-full text-black font-global" data-mds="Typography">여름에 입기 좋은 두께감에 소재도 시원해서 너무 좋아용</span><span class="ExpandableContent__MoreButton-sc-8yrutl-2 dyldeY font-global" data-mds="Typography"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] text-gray-600 font-global" data-mds="Typography"> ...</span><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] underline text-gray-600 font-global" data-mds="Typography">더보기</span></span></div></div></div>,
 <div class="ExpandableContent__ContentContainer-sc-8yrutl-1 gvkPRD"><div style="max-height: 63px; overflow: hidden; white-space: pre-line;"></div><div style="white-space: pre-line;"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] w-full text-black font-global" data-mds="Typography">여름에 입기 좋은 두께감에 소재도 시원해서 너무 좋아용</span></div><div aria-hidden="true" class="Truncate__MeasureContainer-sc-1gm444l-0 ljgstB" style="max-width: 664.656px;"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] w-full text-black font-global" data-mds="Typography">여름에 입기 좋은 두께감에 소재도 시원해서 너무 좋아용</span><span class="ExpandableContent__MoreButton-sc-8yrutl-2 dyldeY font-global" data-mds="Typography"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] text-gray-600 font-global" data-mds="Typography"> ...</span><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] underline text-gray-600 font-global" data-mds="Typography">더보기</span></span></div></div>,
 <div class="ExpandableContent__Container-sc-8yrutl-0 iuidVu gtm-click-button" data-applied-tab="(not set)" data-brand-id="(not set)" data-button-id="review_content" data-button-name="후기내용" data-index="(not set)" data-section-index="31" data-section-name="review"><div class="ExpandableContent__ContentContainer-sc-8yrutl-1 gvkPRD"><div style="max-height: 63px; overflow: hidden; white-space: pre-line;"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] w-full text-black font-global">예상 예약 배송일정보다 늦어서 좀 그랬는데
 생각보다 만족스러워요
 각잡힌 빳빳한 원단이 아니라 보들거리는 원단이라</span><span class="ExpandableContent__MoreButton-sc-8yrutl-2 dyldeY font-global" data-mds="Typography"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] text-gray-600 font-global" data-mds="Typography"> ...</span><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] underline text-gray-600 font-global" data-mds="Typography">더보기</span></span></div><div aria-hidden="true" class="Truncate__MeasureContainer-sc-1gm444l-0 ljgstB" style="max-width: 664.656px;"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] w-full text-black font-global" data-mds="Typography">예상 예약 배송일정보다 늦어서 좀 그랬는데
 생각보다 만족스러워요
 각잡힌 빳빳한 원단이 아니라 보들거리는 원단이라</span><span class="ExpandableContent__MoreButton-sc-8yrutl-2 dyldeY font-global" data-mds="Typography"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] text-gray-600 font-global" data-mds="Typography"> ...</span><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] underline text-gray-600 font-global" data-mds="Typography">더보기</span></span></div></div></div>,
 <div class="ExpandableContent__ContentContainer-sc-8yrutl-1 gvkPRD"><div style="max-height: 63px; overflow: hidden; white-space: pre-line;"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] w-full text-black font-global">예상 예약 배송일정보다 늦어서 좀 그랬는데
 생각보다 만족스러워요
 각잡힌 빳빳한 원단이 아니라 보들거리는 원단이라</span><span class="ExpandableContent__MoreButton-sc-8yrutl-2 dyldeY font-global" data-mds="Typography"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] text-gray-600 font-global" data-mds="Typography"> ...</span><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] underline text-gray-600 font-global" data-mds="Typography">더보기</span></span></div><div aria-hidden="true" class="Truncate__MeasureContainer-sc-1gm444l-0 ljgstB" style="max-width: 664.656px;"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] w-full text-black font-global" data-mds="Typography">예상 예약 배송일정보다 늦어서 좀 그랬는데
 생각보다 만족스러워요
 각잡힌 빳빳한 원단이 아니라 보들거리는 원단이라</span><span class="ExpandableContent__MoreButton-sc-8yrutl-2 dyldeY font-global" data-mds="Typography"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] text-gray-600 font-global" data-mds="Typography"> ...</span><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] underline text-gray-600 font-global" data-mds="Typography">더보기</span></span></div></div>,
 <div class="ExpandableContent__Container-sc-8yrutl-0 iuidVu gtm-click-button" data-applied-tab="(not set)" data-brand-id="(not set)" data-button-id="review_content" data-button-name="후기내용" data-index="(not set)" data-section-index="31" data-section-name="review"><div class="ExpandableContent__ContentContainer-sc-8yrutl-1 gvkPRD"><div style="max-height: 63px; overflow: hidden; white-space: pre-line;"></div><div style="white-space: pre-line;"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] w-full text-black font-global" data-mds="Typography">피그먼트 반팔이랑 다르게 재질이 부드러운 편이지만
 한여름에도 편하게 잘 입을것 같습니당
 다른 컬러도 구매하고 싶네요</span></div><div aria-hidden="true" class="Truncate__MeasureContainer-sc-1gm444l-0 ljgstB" style="max-width: 664.656px;"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] w-full text-black font-global" data-mds="Typography">피그먼트 반팔이랑 다르게 재질이 부드러운 편이지만
 한여름에도 편하게 잘 입을것 같습니당
 다른 컬러도 구매하고 싶네요</span><span class="ExpandableContent__MoreButton-sc-8yrutl-2 dyldeY font-global" data-mds="Typography"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] text-gray-600 font-global" data-mds="Typography"> ...</span><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] underline text-gray-600 font-global" data-mds="Typography">더보기</span></span></div></div></div>,
 <div class="ExpandableContent__ContentContainer-sc-8yrutl-1 gvkPRD"><div style="max-height: 63px; overflow: hidden; white-space: pre-line;"></div><div style="white-space: pre-line;"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] w-full text-black font-global" data-mds="Typography">피그먼트 반팔이랑 다르게 재질이 부드러운 편이지만
 한여름에도 편하게 잘 입을것 같습니당
 다른 컬러도 구매하고 싶네요</span></div><div aria-hidden="true" class="Truncate__MeasureContainer-sc-1gm444l-0 ljgstB" style="max-width: 664.656px;"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] w-full text-black font-global" data-mds="Typography">피그먼트 반팔이랑 다르게 재질이 부드러운 편이지만
 한여름에도 편하게 잘 입을것 같습니당
 다른 컬러도 구매하고 싶네요</span><span class="ExpandableContent__MoreButton-sc-8yrutl-2 dyldeY font-global" data-mds="Typography"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] text-gray-600 font-global" data-mds="Typography"> ...</span><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] underline text-gray-600 font-global" data-mds="Typography">더보기</span></span></div></div>,
 <div class="ExpandableContent__Container-sc-8yrutl-0 iuidVu gtm-click-button" data-applied-tab="(not set)" data-brand-id="(not set)" data-button-id="review_content" data-button-name="후기내용" data-index="(not set)" data-section-index="31" data-section-name="review"><div class="ExpandableContent__ContentContainer-sc-8yrutl-1 gvkPRD"><div style="max-height: 63px; overflow: hidden; white-space: pre-line;"></div><div style="white-space: pre-line;"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] w-full text-black font-global" data-mds="Typography">피그먼트 반팔이랑 다르게 재질이 부드러운 편이어서
 한여름에도 편하게 잘 입을것 같습니당
 다른 컬러도 구매하고 싶어용!!!</span></div><div aria-hidden="true" class="Truncate__MeasureContainer-sc-1gm444l-0 ljgstB" style="max-width: 664.656px;"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] w-full text-black font-global" data-mds="Typography">피그먼트 반팔이랑 다르게 재질이 부드러운 편이어서
 한여름에도 편하게 잘 입을것 같습니당
 다른 컬러도 구매하고 싶어용!!!</span><span class="ExpandableContent__MoreButton-sc-8yrutl-2 dyldeY font-global" data-mds="Typography"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] text-gray-600 font-global" data-mds="Typography"> ...</span><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] underline text-gray-600 font-global" data-mds="Typography">더보기</span></span></div></div></div>,
 <div class="ExpandableContent__ContentContainer-sc-8yrutl-1 gvkPRD"><div style="max-height: 63px; overflow: hidden; white-space: pre-line;"></div><div style="white-space: pre-line;"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] w-full text-black font-global" data-mds="Typography">피그먼트 반팔이랑 다르게 재질이 부드러운 편이어서
 한여름에도 편하게 잘 입을것 같습니당
 다른 컬러도 구매하고 싶어용!!!</span></div><div aria-hidden="true" class="Truncate__MeasureContainer-sc-1gm444l-0 ljgstB" style="max-width: 664.656px;"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] w-full text-black font-global" data-mds="Typography">피그먼트 반팔이랑 다르게 재질이 부드러운 편이어서
 한여름에도 편하게 잘 입을것 같습니당
 다른 컬러도 구매하고 싶어용!!!</span><span class="ExpandableContent__MoreButton-sc-8yrutl-2 dyldeY font-global" data-mds="Typography"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] text-gray-600 font-global" data-mds="Typography"> ...</span><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] underline text-gray-600 font-global" data-mds="Typography">더보기</span></span></div></div>,
 <div class="ExpandableContent__Container-sc-8yrutl-0 iuidVu gtm-click-button" data-applied-tab="(not set)" data-brand-id="(not set)" data-button-id="review_content" data-button-name="후기내용" data-index="(not set)" data-section-index="31" data-section-name="review"><div class="ExpandableContent__ContentContainer-sc-8yrutl-1 gvkPRD"><div style="max-height: 63px; overflow: hidden; white-space: pre-line;"></div><div style="white-space: pre-line;"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] w-full text-black font-global" data-mds="Typography">피그먼트 반팔이랑 다르게 재질이 부드러운 편이어서
 한여름에도 편하게 잘 입을것 같습니당
 다른 컬러도 구매하고 싶어용!!!</span></div><div aria-hidden="true" class="Truncate__MeasureContainer-sc-1gm444l-0 ljgstB" style="max-width: 664.656px;"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] w-full text-black font-global" data-mds="Typography">피그먼트 반팔이랑 다르게 재질이 부드러운 편이어서
 한여름에도 편하게 잘 입을것 같습니당
 다른 컬러도 구매하고 싶어용!!!</span><span class="ExpandableContent__MoreButton-sc-8yrutl-2 dyldeY font-global" data-mds="Typography"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] text-gray-600 font-global" data-mds="Typography"> ...</span><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] underline text-gray-600 font-global" data-mds="Typography">더보기</span></span></div></div></div>,
 <div class="ExpandableContent__ContentContainer-sc-8yrutl-1 gvkPRD"><div style="max-height: 63px; overflow: hidden; white-space: pre-line;"></div><div style="white-space: pre-line;"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] w-full text-black font-global" data-mds="Typography">피그먼트 반팔이랑 다르게 재질이 부드러운 편이어서
 한여름에도 편하게 잘 입을것 같습니당
 다른 컬러도 구매하고 싶어용!!!</span></div><div aria-hidden="true" class="Truncate__MeasureContainer-sc-1gm444l-0 ljgstB" style="max-width: 664.656px;"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] w-full text-black font-global" data-mds="Typography">피그먼트 반팔이랑 다르게 재질이 부드러운 편이어서
 한여름에도 편하게 잘 입을것 같습니당
 다른 컬러도 구매하고 싶어용!!!</span><span class="ExpandableContent__MoreButton-sc-8yrutl-2 dyldeY font-global" data-mds="Typography"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] text-gray-600 font-global" data-mds="Typography"> ...</span><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] underline text-gray-600 font-global" data-mds="Typography">더보기</span></span></div></div>,
 <div class="ExpandableContent__Container-sc-8yrutl-0 iuidVu gtm-click-button" data-applied-tab="(not set)" data-brand-id="(not set)" data-button-id="review_content" data-button-name="후기내용" data-index="(not set)" data-section-index="31" data-section-name="review"><div class="ExpandableContent__ContentContainer-sc-8yrutl-1 gvkPRD"><div style="max-height: 63px; overflow: hidden; white-space: pre-line;"></div><div style="white-space: pre-line;"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] w-full text-black font-global" data-mds="Typography">피그먼트 반팔이랑 다르게 재질이 부드러운 편이어서
 한여름에도 편하게 잘 입을것 같습니당
 다른 컬러도 구매하고 싶네용!!!!</span></div><div aria-hidden="true" class="Truncate__MeasureContainer-sc-1gm444l-0 ljgstB" style="max-width: 664.656px;"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] w-full text-black font-global" data-mds="Typography">피그먼트 반팔이랑 다르게 재질이 부드러운 편이어서
 한여름에도 편하게 잘 입을것 같습니당
 다른 컬러도 구매하고 싶네용!!!!</span><span class="ExpandableContent__MoreButton-sc-8yrutl-2 dyldeY font-global" data-mds="Typography"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] text-gray-600 font-global" data-mds="Typography"> ...</span><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] underline text-gray-600 font-global" data-mds="Typography">더보기</span></span></div></div></div>,
 <div class="ExpandableContent__ContentContainer-sc-8yrutl-1 gvkPRD"><div style="max-height: 63px; overflow: hidden; white-space: pre-line;"></div><div style="white-space: pre-line;"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] w-full text-black font-global" data-mds="Typography">피그먼트 반팔이랑 다르게 재질이 부드러운 편이어서
 한여름에도 편하게 잘 입을것 같습니당
 다른 컬러도 구매하고 싶네용!!!!</span></div><div aria-hidden="true" class="Truncate__MeasureContainer-sc-1gm444l-0 ljgstB" style="max-width: 664.656px;"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] w-full text-black font-global" data-mds="Typography">피그먼트 반팔이랑 다르게 재질이 부드러운 편이어서
 한여름에도 편하게 잘 입을것 같습니당
 다른 컬러도 구매하고 싶네용!!!!</span><span class="ExpandableContent__MoreButton-sc-8yrutl-2 dyldeY font-global" data-mds="Typography"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] text-gray-600 font-global" data-mds="Typography"> ...</span><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] underline text-gray-600 font-global" data-mds="Typography">더보기</span></span></div></div>,
 <div class="ExpandableContent__Container-sc-8yrutl-0 iuidVu gtm-click-button" data-applied-tab="(not set)" data-brand-id="(not set)" data-button-id="review_content" data-button-name="후기내용" data-index="(not set)" data-section-index="31" data-section-name="review"><div class="ExpandableContent__ContentContainer-sc-8yrutl-1 gvkPRD"><div style="max-height: 63px; overflow: hidden; white-space: pre-line;"></div><div style="white-space: pre-line;"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] w-full text-black font-global" data-mds="Typography">요즘 힛한 아이템을 구매해봤는디 나름 만족합니다</span></div><div aria-hidden="true" class="Truncate__MeasureContainer-sc-1gm444l-0 ljgstB" style="max-width: 664.656px;"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] w-full text-black font-global" data-mds="Typography">요즘 힛한 아이템을 구매해봤는디 나름 만족합니다</span><span class="ExpandableContent__MoreButton-sc-8yrutl-2 dyldeY font-global" data-mds="Typography"><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] text-gray-600 font-global" data-mds="Typography"> ...</span><span class="text-[13px] leading-[18px] tracking-[0] font-[400] lang-ja-JP:text-[12px] lang-zh-CN:text-[12px] lang-zh-TW:text-[12px] underline text-gray-600 font-global" data-mds="Typography">더보기</span></span></div></div></div>,

In [33]:
[tag.get_text().replace('\n','') for tag in review_tags]

['여름에 입기 좋은 두께감에 소재도 시원해서 너무 좋아용여름에 입기 좋은 두께감에 소재도 시원해서 너무 좋아용\xa0...더보기',
 '여름에 입기 좋은 두께감에 소재도 시원해서 너무 좋아용여름에 입기 좋은 두께감에 소재도 시원해서 너무 좋아용\xa0...더보기',
 '예상 예약 배송일정보다 늦어서 좀 그랬는데생각보다 만족스러워요각잡힌 빳빳한 원단이 아니라 보들거리는 원단이라\xa0...더보기예상 예약 배송일정보다 늦어서 좀 그랬는데생각보다 만족스러워요각잡힌 빳빳한 원단이 아니라 보들거리는 원단이라\xa0...더보기',
 '예상 예약 배송일정보다 늦어서 좀 그랬는데생각보다 만족스러워요각잡힌 빳빳한 원단이 아니라 보들거리는 원단이라\xa0...더보기예상 예약 배송일정보다 늦어서 좀 그랬는데생각보다 만족스러워요각잡힌 빳빳한 원단이 아니라 보들거리는 원단이라\xa0...더보기',
 '피그먼트 반팔이랑 다르게 재질이 부드러운 편이지만 한여름에도 편하게 잘 입을것 같습니당 다른 컬러도 구매하고 싶네요피그먼트 반팔이랑 다르게 재질이 부드러운 편이지만 한여름에도 편하게 잘 입을것 같습니당 다른 컬러도 구매하고 싶네요\xa0...더보기',
 '피그먼트 반팔이랑 다르게 재질이 부드러운 편이지만 한여름에도 편하게 잘 입을것 같습니당 다른 컬러도 구매하고 싶네요피그먼트 반팔이랑 다르게 재질이 부드러운 편이지만 한여름에도 편하게 잘 입을것 같습니당 다른 컬러도 구매하고 싶네요\xa0...더보기',
 '피그먼트 반팔이랑 다르게 재질이 부드러운 편이어서한여름에도 편하게 잘 입을것 같습니당다른 컬러도 구매하고 싶어용!!!피그먼트 반팔이랑 다르게 재질이 부드러운 편이어서한여름에도 편하게 잘 입을것 같습니당다른 컬러도 구매하고 싶어용!!!\xa0...더보기',
 '피그먼트 반팔이랑 다르게 재질이 부드러운 편이어서한여름에도 편하게 잘 입을것 같습니당다른 컬러도 구매하고 싶어용!!!피그먼트 반팔이랑 다르게 재질이 부드러운 편이어서한여름에도 편하게 잘 입을것 같습니당다른 컬러도 구매하고 싶어용!!!\xa0...더보기',
 '피그먼트 반팔이랑 다르게 재질이 부드러운 편이어서한여름에도 편하게 잘 입을것 같습니당다른 컬러도 구매하고 싶어용!!!피그먼트 반팔이랑 다르게 재질이 부드러운 편이어서한여름에도 편하게 잘 입을것 같습니당다른 컬러도 구매하고 싶어용!!!\xa0...더보기',
 '피그먼트 반팔이랑 다르게 재질이 부드러운 편이어서한여름에도 편하게 잘 입을것 같습니당다른 컬러도 구매하고 싶어용!!!피그먼트 반팔이랑 다르게 재질이 부드러운 편이어서한여름에도 편하게 잘 입을것 같습니당다른 컬러도 구매하고 싶어용!!!\xa0...더보기',
 '피그먼트 반팔이랑 다르게 재질이 부드러운 편이어서 한여름에도 편하게 잘 입을것 같습니당 다른 컬러도 구매하고 싶네용!!!!피그먼트 반팔이랑 다르게 재질이 부드러운 편이어서 한여름에도 편하게 잘 입을것 같습니당 다른 컬러도 구매하고 싶네용!!!!\xa0...더보기',
 '피그먼트 반팔이랑 다르게 재질이 부드러운 편이어서 한여름에도 편하게 잘 입을것 같습니당 다른 컬러도 구매하고 싶네용!!!!피그먼트 반팔이랑 다르게 재질이 부드러운 편이어서 한여름에도 편하게 잘 입을것 같습니당 다른 컬러도 구매하고 싶네용!!!!\xa0...더보기',
 '요즘 힛한 아이템을 구매해봤는디 나름 만족합니다요즘 힛한 아이템을 구매해봤는디 나름 만족합니다\xa0...더보기',
 '요즘 힛한 아이템을 구매해봤는디 나름 만족합니다요즘 힛한 아이템을 구매해봤는디 나름 만족합니다\xa0...더보기',
 '쫀쫀하고 약간 두께 좀 있습니다. 쨍해서 코디하기 편해요쫀쫀하고 약간 두께 좀 있습니다. 쨍해서 코디하기 편해요\xa0...더보기',
 '쫀쫀하고 약간 두께 좀 있습니다. 쨍해서 코디하기 편해요쫀쫀하고 약간 두께 좀 있습니다. 쨍해서 코디하기 편해요\xa0...더보기']

In [34]:
import time

In [35]:
driver = webdriver.Chrome()

In [36]:
# 반복문 생성 (상품명 리스트와 link를 이용해서)
review_dict =[]
for name, link in zip(name_list, link_list):
    # print(link)
    # break
    driver.get(link)
    time.sleep(1)
    soup2 = bs(driver.page_source, 'html.parser')
    reviews_tag = soup2.find('div', class_=re.compile(f"^GoodsReviewListSection"))
    try:
        review_tags = reviews_tag.find_all('div', class_=re.compile(r"^ExpandableContent"))
        for tag in review_tags:
            text = tag.get_text().replace('\n', '')
            review_dict.append(
                {
                    '상품명' : name, 
                    '리뷰' : text
                }
            )
    except:
        pass

In [37]:

driver.close()

In [38]:
review_df = pd.DataFrame(review_dict)

In [39]:
# 중복 리뷰는 제거 
review_df.drop_duplicates('리뷰', inplace=True)

In [40]:
# df 와 review_df를 결합(조인 결합)

total_df = pd.merge(df, review_df, on = '상품명', how='left')

In [41]:
total_df

,브랜드,상품명,할인율,판매가격,link,리뷰
0,소버먼트,【건조기 가능】 3-Way 롤업 레이어드 소프트 티셔츠 [9 Color],30%,"29,000원",https://www.musinsa.com/products/6659876,여름에 입기 좋은 두께감에 소재도 시원해서 너무 좋아용여름에 입기 좋은 두께감에 소...
1,소버먼트,【건조기 가능】 3-Way 롤업 레이어드 소프트 티셔츠 [9 Color],30%,"29,000원",https://www.musinsa.com/products/6659876,예상 예약 배송일정보다 늦어서 좀 그랬는데생각보다 만족스러워요각잡힌 빳빳한 원단이 ...
2,소버먼트,【건조기 가능】 3-Way 롤업 레이어드 소프트 티셔츠 [9 Color],30%,"29,000원",https://www.musinsa.com/products/6659876,피그먼트 반팔이랑 다르게 재질이 부드러운 편이지만 한여름에도 편하게 잘 입을것 같습...
3,소버먼트,【건조기 가능】 3-Way 롤업 레이어드 소프트 티셔츠 [9 Color],30%,"29,000원",https://www.musinsa.com/products/6659876,피그먼트 반팔이랑 다르게 재질이 부드러운 편이어서한여름에도 편하게 잘 입을것 같습니...
4,소버먼트,【건조기 가능】 3-Way 롤업 레이어드 소프트 티셔츠 [9 Color],30%,"29,000원",https://www.musinsa.com/products/6659876,피그먼트 반팔이랑 다르게 재질이 부드러운 편이어서 한여름에도 편하게 잘 입을것 같습...
...,...,...,...,...,...,...
162,오오엠엘,피플 슬림 숏 슬리브 멜란지 그레이,20%,"29,520원",https://www.musinsa.com/products/6508556,체험단 이 후기는 제품을 무상으로 제공받아 직접 사용해 본 후 작성되었습니다.배송받...
163,오오엠엘,피플 슬림 숏 슬리브 멜란지 그레이,20%,"29,520원",https://www.musinsa.com/products/6508556,이런 기본티 예쁜걸 찾고 있었는데 프린팅도 예쁘고 핏도 딱 제가 원하던 핏이라 만족...
164,오오엠엘,피플 슬림 숏 슬리브 멜란지 그레이,20%,"29,520원",https://www.musinsa.com/products/6508556,체험단 이 후기는 제품을 무상으로 제공받아 직접 사용해 본 후 작성되었습니다.평소 ...
165,오드스튜디오,"[디지몬 어드벤처] Vamdemon, Gottsumon, and Pumpmon Ov...",10%,"37,800원",https://www.musinsa.com/products/6546927,예뻐요! 프린팅도 진하게 나오고 같이온 스티커도 귀엽고 택에도 아구몬ㅠㅠ 넘 귀여워...
166,오드스튜디오,"[디지몬 어드벤처] Vamdemon, Gottsumon, and Pumpmon Ov...",10%,"37,800원",https://www.musinsa.com/products/6546927,작년에 나오고 끝일줄알았는데 더나와서 좋아요 묘티스몬 못참지작년에 나오고 끝일줄알았...

In [42]:
len(review_df['상품명'].unique())

28